export {
  LUCIDE_ATTRIBUTION,
  LUCIDE_LICENSE,
  isRsIconName,
  lucideIconCount,
  resolveLucideIcon,
} from './lucide'

/** Playground / 文档常用图标（Lucide 全库约 1600+；kebab-case，如 `house`、`trash-2`） */
export const rsCommonIconNames = [
  'house',
  'settings',
  'user',
  'search',
  'plus',
  'x',
  'check',
  'message-square',
  'folder',
  'chevron-right',
  'chevron-down',
  'loader',
  'trash-2',
  'pencil',
  'bell',
  'cloud',
  'download',
  'upload',
  'link',
  'copy',
  'external-link',
  'layout-dashboard',
  'credit-card',
  'shield-check',
] as const satisfies readonly string[]
