import type { ComponentDoc } from '../types'

const size: [string, string] = ["'ssm' | 'sm' | 'md' | 'lg'", "'md'"]
const radius: [string, string] = ["'none' | 'xs' | 'sm' | 'md' | 'lg' | 'full'", '组件默认值']

export const basicComponents: ComponentDoc[] = [
  {
    slug: 'button',
    name: 'RsButton',
    title: 'Button',
    titleZh: '按钮',
    group: 'basic',
    summary: '触发即时操作。',
    description:
      '按钮用于开始一个即时操作。形态（variant）与语义色（tone）正交：variant 控制实心 / 轮廓 / 幽灵 / 文字 / 链接，tone 只改色相。',
    descriptionEn:
      'A button starts an immediate action. Shape (variant) and semantic color (tone) are independent: variant chooses solid, outline, ghost, text, or link; tone only changes hue.',
    whenToUse: [
      '主按钮：一个操作区域只放一个，表示该区域最重要的提交或保存。',
      '次按钮（default / secondary）：取消、重置、并列的次要操作。secondary 是 default 的别名。',
      '幽灵 / 文字 / 链接：更轻的操作。幽灵适合深色或复杂背景。',
      '危险操作：用 tone="danger"。删除、权限变更等建议再加确认。',
      '禁用：行动点不可用时使用，并在附近说明原因。',
      '加载中：异步提交加 loading，不要再叠 disabled。',
      '仅图标：必须提供 tooltip 或 aria-label。',
    ],
    whenToUseEn: [
      'Primary: one per action group. It is the most important submit or save.',
      'Default / secondary: cancel, reset, or peer secondary actions. secondary is an alias of default.',
      'Ghost / text / link: lighter actions. Use ghost on dark or busy backgrounds.',
      'Destructive work: set tone="danger". Confirm deletes and permission changes.',
      'Disabled: when the action is unavailable, explain why nearby.',
      'Loading: set loading on async submit. Do not also set disabled.',
      'Icon-only: always provide tooltip or aria-label.',
    ],
    demos: [
      { id: 'demo-type', title: '形态', titleEn: 'Shape' },
      { id: 'demo-tone', title: '语义色', titleEn: 'Tone' },
      { id: 'demo-size', title: '尺寸', titleEn: 'Size' },
      { id: 'demo-icon', title: '图标', titleEn: 'Icons' },
      { id: 'demo-disabled', title: '禁用', titleEn: 'Disabled' },
      { id: 'demo-loading', title: '加载中', titleEn: 'Loading' },
      { id: 'demo-radius', title: '圆角与描边', titleEn: 'Radius and border' },
      { id: 'demo-group', title: '组合', titleEn: 'Groups' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'variant',
        type: "'primary' | 'secondary' | 'default' | 'ghost' | 'danger' | 'link' | 'text'",
        default: "'primary'",
        description: '形态。secondary 等价 default（轮廓 + 浅底）。danger 为历史实心危险按钮，新代码请用 tone="danger"。',
        descriptionEn:
          'Shape. secondary equals default (outline + tinted fill). danger is a legacy solid destructive style; prefer tone="danger".',
      },
      {
        name: 'tone',
        type: "'neutral' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: '随 variant：primary/link 为 primary，danger 为 danger，其余 neutral',
        defaultEn: 'follows variant: primary/link → primary, danger → danger, else neutral',
        description: '语义色，与 variant 正交。例：描边警告写 variant="default" tone="warning"。',
        descriptionEn: 'Semantic hue, independent of variant. Example: outline warning is variant="default" tone="warning".',
      },
      {
        name: 'size',
        type: size[0],
        default: size[1],
        description: '控件尺寸。未传时跟随 RsConfigProvider.control-size。',
        descriptionEn: 'Control size. Falls back to RsConfigProvider.control-size.',
      },
      {
        name: 'radius',
        type: radius[0],
        default: "'full'",
        description: '圆角档位。默认胶囊；直角界面传 none。',
        descriptionEn: 'Corner radius. Default is pill (full). Pass none for square UI.',
      },
      {
        name: 'type',
        type: "'button' | 'submit' | 'reset'",
        default: "'button'",
        description: '原生 button type，表单里提交用 submit。',
        descriptionEn: 'Native button type. Use submit inside a form.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '不可用。应同时提供原因说明，不要只灰掉。',
        descriptionEn: 'Unavailable. Explain why nearby — do not only gray it out.',
      },
      {
        name: 'loading',
        type: 'boolean',
        default: 'false',
        description: '异步等待：显示旋转并阻止再次点击。不要再加 disabled。',
        descriptionEn: 'Async wait: shows a spinner and blocks further clicks. Do not also set disabled.',
      },
      {
        name: 'bordered',
        type: 'boolean',
        default: 'text/link 为 false，其余 true',
        defaultEn: 'false for text/link, true otherwise',
        description: '是否绘制外边框。',
        descriptionEn: 'Whether to draw the outline.',
      },
      {
        name: 'icon',
        type: 'string',
        description: '前缀图标，Lucide kebab-case 名称。',
        descriptionEn: 'Leading icon. Lucide kebab-case name.',
      },
      {
        name: 'iconSize',
        type: 'number',
        default: '随 size：ssm 12 / sm 14 / md 16 / lg 18',
        defaultEn: 'follows size: ssm 12 / sm 14 / md 16 / lg 18',
        description: '前缀图标边长（px）。未传时跟控件档位，不要在业务里写死另一套。',
        descriptionEn: 'Leading icon edge in px. Falls back to the control size token. Do not invent a second scale in product CSS.',
      },
      {
        name: 'iconOnly',
        type: 'boolean',
        default: 'false',
        description: '仅图标。必须提供 tooltip 或 ariaLabel。',
        descriptionEn: 'Icon only. tooltip or ariaLabel is required.',
      },
      {
        name: 'tooltip',
        type: 'string',
        description: '悬浮提示，Teleport 到 body。',
        descriptionEn: 'Hover label. Teleported to document.body.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '仅图标时的无障碍名称。有 tooltip 时优先用 aria-label 避免重复朗读。',
        descriptionEn: 'Accessible name for icon-only. Prefer aria-label when a tooltip is also shown, to avoid double speech.',
      },
      {
        name: 'revealLabel',
        type: 'boolean',
        default: 'false',
        description: '默认收起文字，悬停展开。需配合默认插槽，适合工具栏。',
        descriptionEn: 'Collapse the label until hover. Requires default slot. Use on dense toolbars.',
      },
    ],
    events: [
      {
        name: 'click',
        type: '(event: MouseEvent) => void',
        description: '原生 button 的 click，直接绑 @click。loading 时 capture 拦住，不会再往外传。没有额外的组件事件。',
        descriptionEn: 'Native button click — bind @click. While loading, capture blocks it. No extra component events.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '按钮文案。icon-only 时仍可作 tooltip 文案；reveal-label 必须有默认插槽。',
        descriptionEn: 'Button label. On icon-only it can still feed the tooltip. reveal-label requires this slot.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在组件 ref 上调 focus / validate。点击走 @click。',
        descriptionEn: 'No defineExpose. Do not call focus or validate on the component ref. Clicks use @click.',
      },
    ],
    tokens: [
      {
        name: '--rs-btn-outline-border',
        default: 'light #6e6e73 / dark #a3a3a3',
        description: '轮廓按钮描边。',
        descriptionEn: 'Outline button border.',
      },
      {
        name: '--rs-btn-secondary-bg',
        default: 'tinted fill',
        description: 'default/secondary 背景。',
        descriptionEn: 'Background for default/secondary.',
      },
      {
        name: '--rs-btn-secondary-bg-hover',
        default: 'primary tint',
        description: '悬浮背景。',
        descriptionEn: 'Hover background.',
      },
      {
        name: '--rs-btn-radius',
        default: 'var(--rs-radius-full)',
        description: '由 radius prop 写入。',
        descriptionEn: 'Written by the radius prop.',
      },
    ],
    faq: [
      {
        q: 'secondary 和 default 有什么区别？',
        a: '没有。secondary 是 default 的别名。新代码写 default 即可。',
        qEn: 'What is the difference between secondary and default?',
        aEn: 'None. secondary is an alias of default. New code can just use default.',
      },
      {
        q: '如何做描边警告或实心成功？',
        a: '描边警告：variant="default" tone="warning"。实心成功：variant="primary" tone="success"。不要写业务 CSS 改颜色。',
        qEn: 'How do I make an outline warning or a solid success button?',
        aEn: 'Outline warning: variant="default" tone="warning". Solid success: variant="primary" tone="success". Do not restyle color in product CSS.',
      },
      {
        q: '还要不要写 variant="danger"？',
        a: '可以，但那是历史实心危险按钮。新代码用任意 variant + tone="danger"。',
        qEn: 'Should I still use variant="danger"?',
        aEn: 'It still works as a legacy solid destructive button. New code should pair any variant with tone="danger".',
      },
      {
        q: '为什么没有 @success / @press 这类组件事件？',
        a: '根节点就是原生 <button>。用 @click、@focus、@keydown。loading 时不要再绑一层自己的防抖，组件已经拦住点击。',
        qEn: 'Why is there no @success or @press component event?',
        aEn: 'The root is a native <button>. Use @click, @focus, and @keydown. Do not add your own click lock on top of loading — the component already blocks it.',
      },
      {
        q: '为什么 ref 上没有 focus？',
        a: 'RsButton 没有 defineExpose。模板 ref 拿不到命令式方法。交互用 @click；要原生 focus 请包一层自己的元素。',
        qEn: 'Why is there no focus on the ref?',
        aEn: 'RsButton has no defineExpose. The template ref has no imperative methods. Use @click. Wrap your own element if you need native focus.',
      },
    ],
    related: ['link', 'dropdown', 'tooltip'],
  },
  {
    slug: 'icon',
    name: 'RsIcon',
    title: 'Icon',
    titleZh: '图标',
    group: 'basic',
    summary: '按名称渲染 Lucide 与业务图标。',
    description:
      '按字符串名称渲染 Lucide 线标，以及工作台内置品牌 mark（mysql、redis、postgres 等）。默认继承 currentColor。按钮、输入框里的图标请走父组件的 icon 属性，不要再包一层 RsIcon 改颜色。',
    descriptionEn:
      'Renders a Lucide stroke, or a built-in brand mark (mysql, redis, postgres, …), by string name. Color inherits currentColor. Inside buttons and inputs, pass the parent icon prop — do not wrap RsIcon just to restyle it.',
    whenToUse: [
      '运行时按名称切换图标，而不是每个文件静态 import SVG。',
      '状态、空态、行内说明等需要独立图标时。',
      '连接树 / 数据源用内置品牌名（rsBrandIconNames），不要另画一套。',
      '可点击的操作请用 RsButton icon，不要给 RsIcon 绑点击。',
      '按钮或输入框内部的装饰图标由父组件负责，RsIcon 只在独立展示时使用。',
    ],
    whenToUseEn: [
      'Switch icons by name at runtime instead of statically importing each SVG.',
      'Standalone status, empty-state, or inline illustration.',
      'Connection trees / data sources: use built-in brand names (rsBrandIconNames). Do not redraw them.',
      'Clickable actions belong on RsButton icon — do not bind click on RsIcon.',
      'Decorative icons inside a button or input are the parent’s job. Use RsIcon only when it stands alone.',
    ],
    demos: [
      { id: 'demo-name', title: '按名称', titleEn: 'By name' },
      { id: 'demo-size', title: '尺寸', titleEn: 'Size' },
      { id: 'demo-color', title: '颜色', titleEn: 'Color' },
      { id: 'demo-label', title: '无障碍', titleEn: 'Accessibility' },
      { id: 'demo-transform', title: '翻转与旋转', titleEn: 'Flip and spin' },
      { id: 'demo-brand', title: '品牌 mark', titleEn: 'Brand marks' },
      { id: 'demo-compose', title: '组合', titleEn: 'Composition' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'name',
        type: 'string',
        description: 'Lucide kebab-case（如 house、trash-2），或内置品牌名如 mysql。未知名称不渲染。',
        descriptionEn: 'Lucide kebab-case (house, trash-2) or a built-in brand name such as mysql. Unknown names render nothing.',
      },
      {
        name: 'size',
        type: "'ssm' | 'sm' | 'md' | 'lg' | number | string",
        default: "'md'",
        description: '边长。档位与控件同一套（ssm 12 / sm 14 / md 16 / lg 18）。独立展示可用数字 px 或 1.5rem。',
        descriptionEn: 'Edge length. Presets match controls (ssm 12 / sm 14 / md 16 / lg 18). Standalone icons may use a px number or 1.5rem.',
      },
      {
        name: 'color',
        type: 'string',
        description: '覆盖颜色。默认 currentColor。品牌 mark 会写入对应 --rs-icon-*-accent。',
        descriptionEn: 'Override color. Default is currentColor. Brand marks write the matching --rs-icon-*-accent.',
      },
      {
        name: 'strokeWidth',
        type: 'number | string',
        default: '1.75',
        description: 'Lucide 线宽。品牌 mark 通常忽略。',
        descriptionEn: 'Lucide stroke width. Brand marks usually ignore this.',
      },
      {
        name: 'label',
        type: 'string',
        description: '有值时作为语义图标（role=img + aria-label）；无值时装饰性（aria-hidden）。',
        descriptionEn: 'When set, the icon is semantic (role=img + aria-label). When omitted, it is decorative (aria-hidden).',
      },
      {
        name: 'flip',
        type: "'horizontal' | 'vertical' | 'both'",
        description: '翻转。指向类图标可用来表示相反方向。',
        descriptionEn: 'Flip. Use on directional icons to point the other way.',
      },
      {
        name: 'rotate',
        type: 'number',
        description: '旋转角度（度）。不要与 spin 同时用。',
        descriptionEn: 'Rotation in degrees. Do not combine with spin.',
      },
      {
        name: 'spin',
        type: 'boolean',
        default: 'false',
        description: '持续旋转。适合 loader。系统开了减少动态时停动画。',
        descriptionEn: 'Continuous spin. Use for loaders. Animation stops when the user prefers reduced motion.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。原生监听会落到 svg，可点击操作请绑 RsButton。',
        descriptionEn: 'No component events. Native listeners fall through to the svg. Bind actions on RsButton.',
      },
    ],
    slots: [
      {
        name: '—',
        type: 'none',
        description: '没有插槽。图形由 name 决定。',
        descriptionEn: 'No slots. The glyph comes from name.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在图标 ref 上调方法。可点击操作用 RsButton。',
        descriptionEn: 'No defineExpose. Do not call methods on the icon ref. Clickable actions belong on RsButton.',
      },
    ],
    tokens: [
      {
        name: '--rs-icon-color',
        default: 'currentColor',
        description: 'Lucide 线标默认色。',
        descriptionEn: 'Default Lucide stroke color.',
      },
      {
        name: '--rs-icon-mysql-accent',
        default: '#4479a1 / #5a9fd4',
        description: 'MySQL mark。',
        descriptionEn: 'MySQL mark.',
      },
      {
        name: '--rs-icon-redis-accent',
        default: '#dc382d / #ff6f61',
        description: 'Redis mark。',
        descriptionEn: 'Redis mark.',
      },
      {
        name: '--rs-icon-postgres-accent',
        default: '#336791 / #6a9ec4',
        description: 'PostgreSQL mark。',
        descriptionEn: 'PostgreSQL mark.',
      },
      {
        name: '--rs-icon-mongodb-accent',
        default: '#47a248 / #5cb85c',
        description: 'MongoDB mark。',
        descriptionEn: 'MongoDB mark.',
      },
    ],
    faq: [
      {
        q: '找不到图标名怎么办？',
        a: 'Lucide 用 kebab-case（trash-2，不是 Trash2）。未知 name 不渲染、不报错。品牌名见 rsBrandIconNames。',
        qEn: 'What if I cannot find a name?',
        aEn: 'Lucide uses kebab-case (trash-2, not Trash2). An unknown name renders nothing and does not throw. Brand names are listed in rsBrandIconNames.',
      },
      {
        q: '品牌色为什么是灰的？',
        a: '需要引入 niuma-ui/brand-icons.css。不引入则走 currentColor。不要在业务里写死十六进制。',
        qEn: 'Why are brand marks gray?',
        aEn: 'Import niuma-ui/brand-icons.css. Without it, marks use currentColor. Do not hard-code hex in product CSS.',
      },
      {
        q: '要不要给每个图标加 label？',
        a: '旁边已有文字时不要加，让它保持装饰性。只有图标本身表达含义时才传 label。可点击请用 RsButton。',
        qEn: 'Should every icon have a label?',
        aEn: 'No. If nearby text already names it, leave it decorative. Pass label only when the icon itself carries meaning. Clickable icons belong on RsButton.',
      },
      {
        q: '点图标为什么没反应？',
        a: 'RsIcon 是展示，不发 click / hover 组件事件。需要可感知的操作时用 RsButton icon。不要给 RsIcon 绑 @click 当按钮——没有焦点环，键盘也到不了。',
        qEn: 'Why does clicking the icon do nothing?',
        aEn: 'RsIcon is presentational. It does not emit click or hover component events. Put the action on RsButton icon. Do not bind @click on RsIcon as a button — there is no focus ring and the keyboard cannot reach it.',
      },
      {
        q: '能在 ref 上调 setName 或 spin 吗？',
        a: '不能。没有 defineExpose。改 name / spin 走 props。',
        qEn: 'Can I call setName or spin on the ref?',
        aEn: 'No. There is no defineExpose. Change name / spin through props.',
      },
    ],
    related: ['button', 'empty'],
  },
  {
    slug: 'link',
    name: 'RsLink',
    title: 'Link',
    titleZh: '链接',
    group: 'basic',
    summary: '文字链接。',
    description:
      '原生 <a> 文字链接，不包 headless 原语。外观跟 tone（默认 primary），可禁用。按钮形态的导航请用 RsButton variant="link"。',
    descriptionEn:
      'A native <a> text link. It does not wrap a headless primitive. Color follows tone (default primary). Button-shaped navigation belongs on RsButton variant="link".',
    whenToUse: [
      '段落、描述列表、帮助文案里的导航文字。',
      '需要与正文混排，而不是独立按钮时。',
      '外链：target="_blank"，组件会补 noopener noreferrer。',
      '字号跟正文 inherit，不要再传 size。控件四档请用 RsButton。',
      '独立动作（工具栏、表格操作）请用 RsButton variant="link"。',
    ],
    whenToUseEn: [
      'Navigation inside a paragraph, description list, or help text.',
      'When the link must sit in running text, not as a standalone control.',
      'Outbound URLs: set target="_blank". The component adds noopener noreferrer.',
      'Type size inherits from the prose. Do not add a size prop. Control sizes belong on RsButton.',
      'Standalone actions (toolbar, table row) belong on RsButton variant="link".',
    ],
    demos: [
      { id: 'demo-basic', title: '基本用法', titleEn: 'Basic' },
      { id: 'demo-underline', title: '下划线', titleEn: 'Underline' },
      { id: 'demo-tone', title: '语义色', titleEn: 'Tone' },
      { id: 'demo-inherit', title: '跟正文', titleEn: 'Follows text' },
      { id: 'demo-icon', title: '图标', titleEn: 'Icons' },
      { id: 'demo-disabled', title: '禁用', titleEn: 'Disabled' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-compose', title: '组合', titleEn: 'Composition' },
    ],
    props: [
      {
        name: 'href',
        type: 'string',
        description: '链接地址。禁用时不输出 href。',
        descriptionEn: 'URL. Omitted from the DOM when disabled.',
      },
      {
        name: 'target',
        type: "'_self' | '_blank' | '_parent' | '_top'",
        default: "'_self'",
        defaultEn: "'_self'",
        description: '原生 target。外链用 _blank。',
        descriptionEn: 'Native target. Use _blank for outbound URLs.',
      },
      {
        name: 'rel',
        type: 'string',
        description: '原生 rel。target="_blank" 时自动合并 noopener noreferrer。',
        descriptionEn: 'Native rel. target="_blank" always merges noopener noreferrer.',
      },
      {
        name: 'underline',
        type: "'always' | 'hover' | 'none'",
        default: "'hover'",
        defaultEn: "'hover'",
        description: '下划线时机。hover 在悬停与 :focus-visible 时出现。',
        descriptionEn: 'When to show the underline. hover also appears on :focus-visible.',
      },
      {
        name: 'tone',
        type: "'primary' | 'neutral' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'primary'",
        defaultEn: "'primary'",
        description: '语义色。不要用业务 CSS 改颜色。',
        descriptionEn: 'Semantic hue. Do not restyle color in product CSS.',
      },
      {
        name: 'icon',
        type: 'string',
        description: '前缀图标，Lucide kebab-case。装饰性，名称走默认插槽。',
        descriptionEn: 'Leading icon. Lucide kebab-case. Decorative; the name is the default slot.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '不可跳转。去掉 href，并设置 aria-disabled 与 tabindex="-1"。',
        descriptionEn: 'Not navigable. Drops href and sets aria-disabled plus tabindex="-1".',
      },
    ],
    events: [
      {
        name: 'click',
        type: '(event: MouseEvent) => void',
        description: '根节点是原生 <a>，直接绑 @click。没有 defineEmits。禁用时组件拦住跳转。演示里请 @click.prevent 以免离开本页。',
        descriptionEn: 'The root is a native <a>. Bind @click. There is no defineEmits. Disabled clicks are blocked. Use @click.prevent in the docs so you stay on the page.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '链接文案。有 icon 时仍是可访问名称。',
        descriptionEn: 'Link text. Still the accessible name when icon is set.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。',
        descriptionEn: 'Nothing is exposed.',
      },
    ],
    tokens: [
      {
        name: '--rs-link-tone',
        default: 'var(--rs-primary)',
        description: '由 tone 写入的色相。',
        descriptionEn: 'Hue written by tone.',
      },
      {
        name: '--rs-link-tone-hover',
        default: 'var(--rs-primary-hover)',
        description: '悬停 / 按下色相。',
        descriptionEn: 'Hover and active hue.',
      },
      {
        name: '--rs-primary / --rs-primary-hover',
        default: 'theme',
        description: '默认 tone=primary 时的色。随 data-rs-theme。',
        descriptionEn: 'Default tone=primary colors. Follow data-rs-theme.',
      },
      {
        name: '--rs-muted',
        default: 'theme',
        description: '禁用色。',
        descriptionEn: 'Disabled color.',
      },
      {
        name: '--rs-focus-ring',
        default: 'theme',
        description: ':focus-visible 描边。',
        descriptionEn: 'Focus-visible ring.',
      },
    ],
    faq: [
      {
        q: '和 RsButton variant="link" 怎么选？',
        a: '混在句子里的跳转用 RsLink。工具栏或表格里的独立动作用按钮。RsLink 是原生 <a>，不包其它组件库。',
        qEn: 'When should I use RsButton variant="link" instead?',
        aEn: 'Use RsLink inside a sentence. Use a button for a standalone toolbar or table action. RsLink is a native <a> and does not wrap another component library.',
      },
      {
        q: '为什么不用 Vue Router 的 to？',
        a: '组件只做 UI。路由由宿主的 <a href> 或自己的 RouterLink 处理，避免公开 API 绑死某一套路由库。',
        qEn: 'Why is there no to prop for Vue Router?',
        aEn: 'The component is UI only. Routing stays with the host <a href> or the host RouterLink, so the public API does not lock to one router.',
      },
      {
        q: '为什么没有 size / theme？',
        a: '链接跟正文混排：字号 inherit，颜色跟 data-rs-theme / RsConfigProvider。四档控件尺寸和主题开关不要做在文字链上，请用 RsButton 或页面级 Provider。',
        qEn: 'Why is there no size or theme prop?',
        aEn: 'A text link sits in prose: font-size inherits, color follows data-rs-theme / RsConfigProvider. Control sizes and theme switches do not belong on the link. Use RsButton or the page-level provider.',
      },
      {
        q: '点了为什么跳走？有没有组件 click 事件？',
        a: '根节点就是 <a>，没有 defineEmits。要留在本页请 @click.prevent。禁用时组件会 preventDefault。',
        qEn: 'Why does the click navigate away? Is there a component click event?',
        aEn: 'The root is an <a>. There is no defineEmits. Stay on the page with @click.prevent. Disabled links already call preventDefault.',
      },
    ],
    related: ['button', 'breadcrumb'],
  },
  {
    slug: 'badge',
    name: 'RsBadge',
    title: 'Badge',
    titleZh: '徽标',
    group: 'basic',
    summary: '状态芯片与可选角标。',
    description:
      '默认是状态芯片：只写 variant + 默认插槽，短词或状态文案。传入 count 或 dot 后走国际角标：有插槽时插槽是宿主、标记挂在角上；没有插槽时只渲染数字或点。与 Tag 相比更紧凑、不可关闭。没有组件事件。',
    descriptionEn:
      'Default is a status chip: variant plus the default slot (a short word or status). count or dot switches to the overlay mark used by Ant / Element / MUI: the slot is the host and the mark sits on the corner; without a slot only the number or dot renders. Unlike Tag it cannot be closed. No component events.',
    whenToUse: [
      '标题、列表旁的状态词（进行中 / 已失败）用芯片：只传 variant 和插槽。',
      '按钮、头像、图标上的未读数或小圆点：传 count / dot，并把宿主放进默认插槽。',
      '只要一枚独立数字、没有宿主时：只传 count。',
      '需要关闭或筛选请用 Tag；可点击操作请绑 RsButton，不要给芯片绑 click。',
    ],
    whenToUseEn: [
      'Status words next to a title or row (In progress / Failed) use the chip: variant and the slot only.',
      'Unread counts or a dot on a button, avatar, or icon: pass count / dot and put the host in the default slot.',
      'A standalone number with no host: pass count only.',
      'Closable or filter marks belong on Tag. Bind actions on RsButton; do not treat the chip as a button.',
    ],
    demos: [
      { id: 'demo-type', title: '状态芯片', titleEn: 'Status chip' },
      { id: 'demo-count', title: '计数', titleEn: 'Count' },
      { id: 'demo-overlay', title: '角标', titleEn: 'Overlay' },
      { id: 'demo-dot', title: '圆点', titleEn: 'Dot' },
      { id: 'demo-zero', title: '零值', titleEn: 'Zero' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'variant',
        type: "'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'default'",
        defaultEn: "'default'",
        description: '语义色，芯片与角标共用。不要用业务 CSS 改颜色。未读计数常见写法是 variant="danger"。',
        descriptionEn:
          'Semantic hue for both chip and mark. Do not restyle color in product CSS. Unread counts usually use variant="danger".',
      },
      {
        name: 'count',
        type: 'number',
        description:
          '角标数字。与默认插槽同时出现时，插槽是宿主。省略时保持原来的芯片。0 默认不显示，除非 showZero。',
        descriptionEn:
          'Overlay count. With a default slot, the slot is the host. Omit it to keep the original chip. 0 is hidden unless showZero is set.',
      },
      {
        name: 'max',
        type: 'number',
        default: '99',
        defaultEn: '99',
        description: '超过后显示 {max}+。只在传了 count 时生效。',
        descriptionEn: 'Show {max}+ when count is larger. Only applies when count is set.',
      },
      {
        name: 'dot',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '小圆点，不计数字。与 count 同时出现时只显示点。',
        descriptionEn: 'A small dot instead of a number. Wins over count when both are set.',
      },
      {
        name: 'showZero',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: 'count 为 0 时仍显示 0。',
        descriptionEn: 'Still show 0 when count is 0.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。芯片本身不可点。角标宿主上的 click 仍走宿主（如 RsButton）。',
        descriptionEn:
          'No component events. The chip is not a control. Clicks on an overlay host stay on the host (for example RsButton).',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description:
          '芯片模式下是徽标文案。传了 count / dot 时是角标宿主（按钮、头像、图标）。不要把可关闭标签放进来。',
        descriptionEn:
          'Chip text when count / dot are omitted. Overlay host (button, avatar, icon) when count or dot is set. Do not put a closable tag here.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在徽标 ref 上调方法。',
        descriptionEn: 'No defineExpose. Do not call methods on the badge ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-badge-padding-y / --rs-badge-padding-x',
        default: '0.125rem / 0.625rem',
        description: '芯片内边距。数值与旧版一致，不要改成 space 档以免视觉漂移。',
        descriptionEn: 'Chip padding. Same values as before; do not swap in space steps or the chip will grow.',
      },
      {
        name: '--rs-badge-dot-size',
        default: 'var(--rs-space-sm)',
        description: '圆点边长。',
        descriptionEn: 'Dot size.',
      },
      {
        name: '--rs-badge-count-min',
        default: '1.125rem',
        description: '独立数字 / 角标数字的最小宽高。',
        descriptionEn: 'Minimum size for a numeric mark.',
      },
      {
        name: '--rs-badge-ring',
        default: 'var(--rs-surface)',
        description: '角标与宿主之间的描边，避免叠在深色按钮上糊掉。',
        descriptionEn: 'Ring between the overlay mark and its host so the mark stays visible on dark buttons.',
      },
      {
        name: '--rs-*-container / --rs-on-*-container',
        default: 'theme',
        description: '各 variant 的浅底深字。随 data-rs-theme。',
        descriptionEn: 'Tinted fill and on-container text per variant. Follows data-rs-theme.',
      },
      {
        name: '--rs-font-size-xs / --rs-radius-full',
        default: 'theme',
        description: '芯片字号与胶囊圆角。',
        descriptionEn: 'Chip type size and pill radius.',
      },
    ],
    faq: [
      {
        q: '这是 Ant Design 那种包一层的 Badge 吗？原来的写法会不会坏？',
        a: '两种模式在同一个组件里。只写 <RsBadge variant="primary">进行中</RsBadge> 仍是原来的状态芯片，根节点还是 span.rs-badge。加上 count 或 dot 之后才变成角标：有插槽就包宿主，没有插槽就只显示数字或点。',
        qEn: 'Is this the Ant Design wrapper Badge? Will existing markup break?',
        aEn: 'Both modes live on one component. <RsBadge variant="primary">In progress</RsBadge> is still the original chip — root remains span.rs-badge. count or dot switches to the overlay: a slot becomes the host; without a slot only the number or dot renders.',
      },
      {
        q: '和 RsTag 怎么选？',
        a: 'Badge 更紧凑，不可关闭，也可挂在控件角上。需要关闭、筛选、禁用请用 Tag。',
        qEn: 'When should I use RsTag instead?',
        aEn: 'Badge is more compact, cannot close, and can sit on a control corner. Closable, filter, or disabled marks belong on Tag.',
      },
      {
        q: '为什么没有 tone / size / offset / ribbon / status？',
        a: '色相沿用已有 variant，避免再开一条轴把旧调用方拆开。芯片保持紧凑，不做四档控件尺寸。offset / ribbon / Ant status+text 没有实现，不要在文档或业务里当已有 API 用。',
        qEn: 'Why is there no tone, size, offset, ribbon, or status?',
        aEn: 'Hue stays on the existing variant so old callers do not split across two axes. The chip stays compact — no control-size scale. offset, ribbon, and Ant status+text are not implemented; do not treat them as public API.',
      },
      {
        q: '点了为什么没反应？有没有组件 click 事件？',
        a: '没有 defineEmits。芯片不是按钮。要可感知的点击，把 RsButton 放进默认插槽并传 count / dot，事件绑在按钮上。',
        qEn: 'Why does a click do nothing? Is there a component click event?',
        aEn: 'There is no defineEmits. The chip is not a button. For a click you can feel, put RsButton in the default slot with count / dot and bind the event on the button.',
      },
    ],
    related: ['tag', 'avatar', 'button'],
  },
  {
    slug: 'tag',
    name: 'RsTag',
    title: 'Tag',
    titleZh: '标签',
    group: 'basic',
    summary: '分类与状态标签。',
    description:
      '标签用于标记对象属性、筛选条件或状态。根节点是 span，不是按钮。可关闭、可禁用，尺寸与圆角走统一档位。关闭钮是 RsButton，仍带 .rs-tag__close。',
    descriptionEn:
      'A tag marks an attribute, filter, or status. The root is a span, not a button. It can close and disable. Size and radius follow the shared scale. The close control is RsButton and still has .rs-tag__close.',
    whenToUse: [
      '展示分类、环境、状态等离散属性。',
      '需要用户移除某个已选项时（closable）。关闭后由宿主删数据。',
      '一组可增删的标签请用 DynamicTags。不可关闭的紧凑状态芯片请用 Badge。',
    ],
    whenToUseEn: [
      'Show a discrete attribute such as category, environment, or status.',
      'Use closable when the user may remove the item. The host deletes the data after close.',
      'An editable group belongs on DynamicTags. A compact status chip that cannot close belongs on Badge.',
    ],
    demos: [
      { id: 'demo-type', title: '语义色', titleEn: 'Tone' },
      { id: 'demo-close', title: '可关闭与胶囊', titleEn: 'Closable and pill' },
      { id: 'demo-size', title: '尺寸', titleEn: 'Size' },
      { id: 'demo-radius', title: '圆角', titleEn: 'Radius' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'variant',
        type: "'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'default'",
        defaultEn: "'default'",
        description: '语义色。标签只有色相、没有形态轴，不要再传 tone。不要用业务 CSS 改颜色。',
        descriptionEn: 'Semantic hue. The tag has no shape axis — do not pass tone. Do not restyle color in product CSS.',
      },
      {
        name: 'closable',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '显示关闭按钮（RsButton，仅图标）。点关闭发 close，不自己从 DOM 卸掉。',
        descriptionEn: 'Show a close control (icon-only RsButton). close fires; the tag does not unmount itself.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '禁用关闭。关闭钮走原生 disabled。',
        descriptionEn: 'Disable close. The close control uses native disabled.',
      },
      {
        name: 'round',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '胶囊圆角快捷开关，等价 radius="full"。',
        descriptionEn: 'Pill shortcut. Same as radius="full".',
      },
      {
        name: 'size',
        type: size[0],
        default: size[1],
        defaultEn: size[1],
        description: '控件尺寸。未传时跟随 RsConfigProvider.control-size。',
        descriptionEn: 'Control size. Falls back to RsConfigProvider.control-size.',
      },
      {
        name: 'radius',
        type: radius[0],
        default: "'sm'",
        defaultEn: "'sm'",
        description: '圆角档位。round 为 true 时强制 full。',
        descriptionEn: 'Corner radius. Forced to full when round is true.',
      },
    ],
    events: [
      {
        name: 'close',
        type: '(event: MouseEvent) => void',
        description: '点击关闭。disabled 时不发。由宿主从列表里移除该项。点正文没有组件 click。',
        descriptionEn:
          'Fires on close. Not emitted when disabled. The host removes the item. The label has no component click.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '标签文案。没有 prefix / icon 插槽。',
        descriptionEn: 'Tag label. There is no prefix or icon slot.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在标签 ref 上调 remove / close。移除走 @close。',
        descriptionEn: 'No defineExpose. Do not call remove or close on the tag ref. Removal uses @close.',
      },
    ],
    tokens: [
      {
        name: '--rs-tag-font-weight',
        default: 'var(--rs-font-weight-regular)',
        description: '标签字重。',
        descriptionEn: 'Tag font weight.',
      },
      {
        name: '--rs-tag-border-alpha',
        default: '40%',
        description: '语义色描边与色相的混合比例。',
        descriptionEn: 'Mix ratio for the semantic border.',
      },
      {
        name: '--rs-tag-radius',
        default: 'var(--rs-radius-sm)',
        description: '由 radius / round 写入。不要 :deep 改边角。',
        descriptionEn: 'Set by radius / round. Do not restyle corners with :deep.',
      },
      {
        name: '--rs-tag-pad-y-sm / --rs-tag-pad-y-md',
        default: '0.0625rem / 0.125rem',
        description: 'sm / md 垂直内边距。数值与旧版一致，不要改成 space 档以免视觉漂移。',
        descriptionEn: 'Vertical padding for sm / md. Same values as before; do not swap in space steps.',
      },
      {
        name: '--rs-*-container / --rs-on-*-container',
        default: 'theme',
        description: '各 variant 的浅底深字。随 data-rs-theme。',
        descriptionEn: 'Tinted fill and on-container text per variant. Follows data-rs-theme.',
      },
    ],
    faq: [
      {
        q: '点关闭后标签为什么还在？',
        a: '组件只发 close。列表数据由宿主删。一组可增删请用 DynamicTags。',
        qEn: 'Why is the tag still there after close?',
        aEn: 'The component only emits close. The host deletes the item. Use DynamicTags for an editable group.',
      },
      {
        q: '和 RsBadge 怎么选？',
        a: 'Badge 更紧凑、不可关闭，也可挂在控件角上。需要关闭、筛选、禁用请用 Tag。',
        qEn: 'When should I use RsBadge instead?',
        aEn: 'Badge is more compact, cannot close, and can sit on a control corner. Closable, filter, or disabled marks belong on Tag.',
      },
      {
        q: '为什么没有 tone / color / checkable / icon？',
        a: '色相沿用已有 variant，避免再开一条轴把旧调用方拆开。color 十六进制、checkable、独立 icon 插槽没有实现，不要当已有 API 用。',
        qEn: 'Why is there no tone, color, checkable, or icon?',
        aEn: 'Hue stays on the existing variant so old callers do not split across two axes. Hex color, checkable, and a separate icon slot are not implemented; do not treat them as public API.',
      },
      {
        q: '点标签正文为什么没反应？有没有 click？',
        a: '没有组件 click。正文在 span 里。可感知的操作只有关闭钮上的 close，或把标签放进可点的宿主。',
        qEn: 'Why does a click on the label do nothing? Is there a click event?',
        aEn: 'There is no component click. The label lives on a span. The only component event is close on the close control, or put the tag inside a clickable host.',
      },
    ],
    related: ['dynamic-tags', 'badge'],
  },
  {
    slug: 'divider',
    name: 'RsDivider',
    title: 'Divider',
    titleZh: '分割线',
    group: 'basic',
    summary: '区隔内容的水平或垂直线。',
    description:
      '分割线切开内容区块。无标题时根节点是原生 hr（隐式 separator）。中间有标题时是 div，因为 hr 不能包内容。没有 label / type / plain / contentPosition。',
    descriptionEn:
      'A divider splits content. With no title the root is a native hr (implicit separator). With a title it is a div, because hr cannot wrap content. There is no label, type, plain, or contentPosition prop.',
    whenToUse: [
      '表单分组、卡片区块之间需要视觉分隔。',
      '工具栏文字或按钮之间用 orientation="vertical"。父级必须是横向 flex。',
      '需要可点的操作请用 RsButton，不要给分割线绑 click。',
    ],
    whenToUseEn: [
      'Separate form groups or card sections.',
      'Use orientation="vertical" between toolbar text or buttons. The parent must be a horizontal flex row.',
      'Clickable actions belong on RsButton. Do not bind click on the divider.',
    ],
    demos: [
      { id: 'demo-h', title: '水平分割', titleEn: 'Horizontal' },
      { id: 'demo-label', title: '中间标题', titleEn: 'Label' },
      { id: 'demo-v', title: '垂直分割', titleEn: 'Vertical' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'orientation',
        type: "'horizontal' | 'vertical'",
        default: "'horizontal'",
        defaultEn: "'horizontal'",
        description: '方向。竖线时默认插槽不渲染。不要用 type 代替。',
        descriptionEn: 'Direction. The default slot does not render on a vertical rule. Do not use type instead.',
      },
      {
        name: 'dashed',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '虚线描边。',
        descriptionEn: 'Dashed stroke.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。分割线不是控件。',
        descriptionEn: 'No component events. The divider is not a control.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '水平分割线中间的标题。竖线忽略。没有 label prop。',
        descriptionEn: 'Title in the middle of a horizontal rule. Ignored when vertical. There is no label prop.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在分割线 ref 上调方法。',
        descriptionEn: 'No defineExpose. Do not call methods on the divider ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-divider-color',
        default: 'var(--rs-border)',
        description: '描边色。随 data-rs-theme。',
        descriptionEn: 'Stroke color. Follows data-rs-theme.',
      },
      {
        name: '--rs-divider-width',
        default: '1px',
        description: '描边厚度。',
        descriptionEn: 'Stroke thickness.',
      },
      {
        name: '--rs-divider-gap',
        default: 'var(--rs-space-md)',
        description: '水平外边距与标题左右内边距。',
        descriptionEn: 'Block margin on a horizontal rule, and inline padding around the title.',
      },
    ],
    faq: [
      {
        q: '为什么没有 label / type / plain / 标题左对齐？',
        a: '标题只走默认插槽。方向是 orientation，不是 type。plain 和左/右标题没有实现，不要当已有 API 用。',
        qEn: 'Why is there no label, type, plain, or left-aligned title?',
        aEn: 'The title is the default slot. Direction is orientation, not type. plain and left/right title placement are not implemented; do not treat them as public API.',
      },
      {
        q: '点了为什么没反应？有没有 click？',
        a: '没有 defineEmits。分割线不是按钮。可感知的点击绑在旁边的 RsButton 上。',
        qEn: 'Why does a click do nothing? Is there a click event?',
        aEn: 'There is no defineEmits. The divider is not a button. Bind a click you can feel on a nearby RsButton.',
      },
      {
        q: '竖线为什么看不见？',
        a: '竖线高度跟父级走。把 RsDivider 放进横向 flex 行，不要单独放在块级容器里。',
        qEn: 'Why is the vertical rule invisible?',
        aEn: 'The vertical rule takes its height from the parent. Put RsDivider in a horizontal flex row, not alone in a block container.',
      },
    ],
    related: ['card', 'fieldset'],
  },
  {
    slug: 'avatar',
    name: 'RsAvatar',
    title: 'Avatar',
    titleZh: '头像',
    group: 'basic',
    summary: '用户或对象的头像，失败时回退文案。',
    description:
      '展示用户、项目或连接的头像。图片失败时回退 fallback 文案，或从 name 取缩写，再没有则用 icon。尺寸只有 sm / md / lg，没有 ssm。',
    descriptionEn:
      'An avatar for a user, project, or connection. If the image fails: fallback text, then initials from name, then icon. Sizes are sm / md / lg only — no ssm.',
    whenToUse: [
      '列表、评论、顶栏需要识别主体时。',
      '没有图片资源时用文字或图标回退保持占位一致。',
    ],
    whenToUseEn: [
      'Identify a subject in a list, comment, or header.',
      'Keep the same footprint with text or icon fallback when there is no image.',
    ],
    demos: [
      { id: 'demo-basic', title: '图片与文字回退', titleEn: 'Image and fallback' },
      { id: 'demo-size', title: '尺寸', titleEn: 'Size' },
      { id: 'demo-shape', title: '形状', titleEn: 'Shape' },
      { id: 'demo-tone', title: '回退色', titleEn: 'Fallback tone' },
      { id: 'demo-slot', title: '自定义回退', titleEn: 'Custom fallback' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'src',
        type: 'string',
        description: '图片地址。失败时走回退。',
        descriptionEn: 'Image URL. Falls back when it fails.',
      },
      {
        name: 'alt',
        type: 'string',
        description: '图片替代文本。未传时用 name。',
        descriptionEn: 'Image alternative text. Falls back to name.',
      },
      {
        name: 'name',
        type: 'string',
        description: '显示名。无 fallback 时取最多两个字母的缩写。',
        descriptionEn: 'Display name. Without fallback, up to two initials are used.',
      },
      {
        name: 'fallback',
        type: 'string',
        description: '无图或失败时的文案，优先于 name 缩写。',
        descriptionEn: 'Fallback text when there is no image. Wins over initials from name.',
      },
      {
        name: 'icon',
        type: 'string',
        default: "'user'",
        defaultEn: "'user'",
        description: '没有文字回退时的 Lucide 图标名。',
        descriptionEn: 'Lucide name used when there is no text fallback.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        default: "'md'",
        defaultEn: "'md'",
        description: '头像边长档位。不是控件四档，没有 ssm。',
        descriptionEn: 'Avatar edge. Not the four control sizes — no ssm.',
      },
      {
        name: 'shape',
        type: "'circle' | 'square'",
        default: "'circle'",
        defaultEn: "'circle'",
        description: '圆形或小圆角方形。',
        descriptionEn: 'Circle or a slightly rounded square.',
      },
      {
        name: 'tone',
        type: "'default' | 'primary' | 'success' | 'warning' | 'danger'",
        default: "'primary'",
        defaultEn: "'primary'",
        description: '回退底的语义色。',
        descriptionEn: 'Semantic hue for the fallback surface.',
      },
      {
        name: 'label',
        type: 'string',
        description: '无障碍名称。未传时用 alt 或 name。',
        descriptionEn: 'Accessible name. Falls back to alt or name.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。头像不是按钮。可感知的点击绑在旁边的 RsButton 上。',
        descriptionEn: 'No component events. The avatar is not a button. Bind a click you can feel on a nearby RsButton.',
      },
    ],
    slots: [
      {
        name: 'fallback',
        type: '—',
        description: '自定义回退内容，覆盖文字缩写与默认图标。',
        descriptionEn: 'Custom fallback. Replaces initials and the default icon.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在头像 ref 上调 setSrc。',
        descriptionEn: 'No defineExpose. Do not call setSrc on the avatar ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-*-container / --rs-on-*-container',
        default: 'theme',
        description: '回退底的语义色。随 data-rs-theme。',
        descriptionEn: 'Fallback surface hues. Follow data-rs-theme.',
      },
    ],
    faq: [
      {
        q: '点了为什么没反应？有没有 click？',
        a: '没有 defineEmits。头像不是控件。要可感知的点击，把操作绑在 RsButton 上。',
        qEn: 'Why does a click do nothing? Is there a click event?',
        aEn: 'There is no defineEmits. The avatar is not a control. Bind a click you can feel on RsButton.',
      },
      {
        q: '为什么没有 ssm / 角标？',
        a: '尺寸只有 sm / md / lg。角标请把 RsAvatar 放进 RsBadge 的默认插槽并传 count / dot。',
        qEn: 'Why is there no ssm or badge overlay?',
        aEn: 'Sizes are sm / md / lg only. For a badge, put RsAvatar in the RsBadge default slot and pass count / dot.',
      },
    ],
    related: ['badge', 'card'],
  },
  {
    slug: 'card',
    name: 'RsCard',
    title: 'Card',
    titleZh: '卡片',
    group: 'basic',
    summary: '承载一组相关内容的容器。',
    description:
      '卡片将标题、操作与主体收进同一表面。size 是疏密，不是控件高度。表单分区请用 Fieldset，不要用 Card 冒充分组语义。',
    descriptionEn:
      'A card groups a title, actions, and body on one surface. size is density, not control height. Form sections belong on Fieldset — do not fake grouping with Card.',
    whenToUse: [
      '仪表盘指标、设置区块、预览摘要等需要独立表面时。',
      '需要标题栏 + 内容 + 可选页脚的信息组。',
    ],
    whenToUseEn: [
      'An independent surface for a dashboard metric, settings block, or preview.',
      'A heading plus body, with an optional footer.',
    ],
    demos: [
      { id: 'demo-basic', title: '基本用法', titleEn: 'Basic' },
      { id: 'demo-variant', title: '表面', titleEn: 'Surface' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'as',
        type: 'string',
        default: "'section'",
        defaultEn: "'section'",
        description: '根元素标签。',
        descriptionEn: 'Root element tag.',
      },
      {
        name: 'title',
        type: 'string',
        description: '标题。也可用 #header。',
        descriptionEn: 'Title. Or use #header.',
      },
      {
        name: 'description',
        type: 'string',
        description: '标题下的说明。',
        descriptionEn: 'Supporting text under the title.',
      },
      {
        name: 'variant',
        type: "'grouped' | 'plain' | 'outlined' | 'filled' | 'glass'",
        default: "'grouped'",
        description: '表面风格。grouped 偏工作台分层；outlined / filled 偏信息面板。',
        descriptionEn: 'Surface. grouped is layered workbench; outlined / filled suit info panels.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        default: "'md'",
        description: '疏密：内边距与标题字号。不是控件 size。',
        descriptionEn: 'Density: padding and title size. Not control size.',
      },
      {
        name: 'radius',
        type: radius[0],
        default: "'md'",
        description: '卡片圆角。不跟随 ConfigProvider.controlRadius。',
        descriptionEn: 'Card radius. Does not follow ConfigProvider.controlRadius.',
      },
      {
        name: 'padding',
        type: 'boolean',
        default: 'true',
        description: 'body 是否使用密度内边距。表格 / 图表可贴边传 false。',
        descriptionEn: 'Whether the body uses density padding. Pass false for a flush table or chart.',
      },
      {
        name: 'elevated',
        type: 'boolean',
        default: 'false',
        description: '抬升阴影。',
        descriptionEn: 'Raised shadow.',
      },
      {
        name: 'borderless',
        type: 'boolean',
        default: 'false',
        description: '去掉边框、阴影与标题分隔，背景透明。',
        descriptionEn: 'Drop border, shadow, and the header rule. Background is transparent.',
      },
      {
        name: 'hoverable',
        type: 'boolean',
        default: 'false',
        description: '悬停轻微抬升，适合可点选的卡片。',
        descriptionEn: 'Slight lift on hover. Use on a clickable card.',
      },
      {
        name: 'clip',
        type: 'boolean',
        default: 'false',
        description: '裁切溢出。默认 false，避免表格 / 下拉被切掉。',
        descriptionEn: 'Clip overflow. Default false so tables and dropdowns are not cut.',
      },
      {
        name: 'fill',
        type: 'boolean',
        default: 'false',
        description: '占满父级高度，body 纵向伸展。',
        descriptionEn: 'Fill the parent height and stretch the body.',
      },
    ],
    slots: [
      {
        name: 'cover',
        type: '—',
        description: '顶部封面。',
        descriptionEn: 'Top cover.',
      },
      {
        name: 'header',
        type: '—',
        description: '自定义标题区，覆盖 title / description。',
        descriptionEn: 'Custom heading. Replaces title / description.',
      },
      {
        name: 'actions',
        type: '—',
        description: '标题行右侧操作。',
        descriptionEn: 'Actions on the right of the heading.',
      },
      {
        name: 'default',
        type: '—',
        description: '主体。',
        descriptionEn: 'Body.',
      },
      {
        name: 'footer',
        type: '—',
        description: '页脚。',
        descriptionEn: 'Footer.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。hoverable 只抬升阴影，不是 click。',
        descriptionEn: 'No component events. hoverable only lifts the shadow — it is not a click.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在卡片 ref 上调 open / close。',
        descriptionEn: 'No defineExpose. Do not call open or close on the card ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-card-border / --rs-card-body-bg / --rs-card-title-fg',
        default: 'theme',
        description: '边框、主体底、标题色。随 data-rs-theme。',
        descriptionEn: 'Border, body fill, and title color. Follow data-rs-theme.',
      },
      {
        name: '--rs-card-radius',
        default: 'var(--rs-radius)',
        description: '由 radius 写入。不跟随 ConfigProvider.controlRadius。',
        descriptionEn: 'Set by radius. Does not follow ConfigProvider.controlRadius.',
      },
    ],
    faq: [
      {
        q: '和 Fieldset 怎么选？',
        a: 'Card 是表面。表单分组必须用 Fieldset / legend，不要用 Card 冒充。',
        qEn: 'When should I use Fieldset instead?',
        aEn: 'Card is a surface. Form groups belong on Fieldset / legend — do not fake that with Card.',
      },
      {
        q: '点了为什么没反应？',
        a: '没有组件 click。hoverable 只是阴影。可点卡片包在按钮或链接里。',
        qEn: 'Why does a click do nothing?',
        aEn: 'There is no component click. hoverable is only a shadow. Wrap a clickable card in a button or link.',
      },
    ],
    related: ['stat-card', 'fieldset', 'container'],
  },
  {
    slug: 'container',
    name: 'RsContainer',
    title: 'Container',
    titleZh: '容器',
    group: 'basic',
    summary: '限制内容宽度并提供统一内边距。',
    description:
      '页面级内容容器，控制最大宽度、水平内边距与是否居中。maxWidth / padding / columns / gap 可传断点对象。文档页与设置页用它统一版心。',
    descriptionEn:
      'A page-level content shell for max width, horizontal padding, and centering. maxWidth / padding / columns / gap accept a breakpoint map. Use it to keep docs and settings on one measure.',
    whenToUse: [
      '需要把正文限制在可读宽度内。',
      '多页面共用同一套边距时。',
      '需要简单 12 列栅格时开 grid。',
    ],
    whenToUseEn: [
      'Keep body text inside a readable measure.',
      'Share one padding scale across pages.',
      'Turn on grid for a simple 12-column layout.',
    ],
    demos: [
      { id: 'demo-basic', title: '基本用法', titleEn: 'Basic' },
      { id: 'demo-fluid', title: '铺满', titleEn: 'Fluid' },
      { id: 'demo-grid', title: '栅格', titleEn: 'Grid' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'maxWidth',
        type: "'sm' | 'md' | 'lg' | 'xl' | 'full' | Responsive",
        default: "'lg'",
        description: '最大内容宽度。fluid 为 true 时忽略。',
        descriptionEn: 'Max content width. Ignored when fluid is true.',
      },
      {
        name: 'padding',
        type: "'none' | 'sm' | 'md' | 'lg' | Responsive",
        default: "'md'",
        description: '水平内边距。',
        descriptionEn: 'Horizontal padding.',
      },
      {
        name: 'centered',
        type: 'boolean',
        default: 'true',
        description: '在父级内水平居中。',
        descriptionEn: 'Center horizontally in the parent.',
      },
      {
        name: 'fluid',
        type: 'boolean',
        default: 'false',
        description: '占满父级宽度，忽略 maxWidth。',
        descriptionEn: 'Fill the parent width and ignore maxWidth.',
      },
      {
        name: 'tag',
        type: 'string',
        default: "'div'",
        description: '根元素标签。',
        descriptionEn: 'Root element tag.',
      },
      {
        name: 'grid',
        type: 'boolean',
        default: 'false',
        description: '启用栅格。未传 columns 时为 12 列。',
        descriptionEn: 'Enable the grid. Defaults to 12 columns when columns is omitted.',
      },
      {
        name: 'columns',
        type: 'number | Responsive',
        default: '12',
        description: '栅格列数。',
        descriptionEn: 'Grid column count.',
      },
      {
        name: 'gap',
        type: "'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | Responsive",
        default: "'md'",
        description: '栅格间距。',
        descriptionEn: 'Grid gap.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '容器内容。',
        descriptionEn: 'Container content.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。容器不是控件。',
        descriptionEn: 'No component events. The container is not a control.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。改宽度走 max-width / fluid。',
        descriptionEn: 'No defineExpose. Change width with max-width / fluid.',
      },
    ],
    tokens: [
      {
        name: '--rs-container-max-sm / md / lg / xl / full',
        default: '40rem / 48rem / 64rem / 80rem / 100%',
        description: 'maxWidth 各档。不要写死像素宽。',
        descriptionEn: 'maxWidth steps. Do not hard-code a pixel width.',
      },
    ],
    faq: [
      {
        q: '和 Card 怎么选？',
        a: 'Container 管版心宽度。Card 是一块表面。不要用 Card 当整页版心。',
        qEn: 'When should I use Card instead?',
        aEn: 'Container sets the page measure. Card is a surface. Do not use Card as the page shell.',
      },
    ],
    related: ['card', 'scrollbar'],
  },
  {
    slug: 'scrollbar',
    name: 'RsScrollbar',
    title: 'Scrollbar',
    titleZh: '滚动条',
    group: 'basic',
    summary: '自定义滚动区域。',
    description:
      '在固定高度容器内提供与主题一致的滚动条。方向用 orientation，不是 direction。侧栏、下拉面板、日志预览应优先使用。',
    descriptionEn:
      'A themed scrollbar in a fixed-height pane. Direction is orientation, not direction. Prefer it in sidebars, menus, and log previews.',
    whenToUse: [
      '侧栏、弹层、分栏中需要内部滚动。',
      '需要隐藏原生滚动条并保持键盘可达时。',
    ],
    whenToUseEn: [
      'Inner scroll in a sidebar, overlay, or split pane.',
      'Hide the native scrollbar and keep keyboard access.',
    ],
    demos: [
      { id: 'demo-basic', title: '纵向滚动', titleEn: 'Vertical' },
      { id: 'demo-both', title: '双向', titleEn: 'Both axes' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'orientation',
        type: "'vertical' | 'horizontal' | 'both'",
        default: "'both'",
        defaultEn: "'both'",
        description: '显示哪根滚动条。不要用 direction。',
        descriptionEn: 'Which scrollbar to show. Do not use direction.',
      },
      {
        name: 'type',
        type: "'auto' | 'always' | 'scroll' | 'hover'",
        default: "'hover'",
        defaultEn: "'hover'",
        description: '滚动条显隐策略。',
        descriptionEn: 'When the scrollbar is visible.',
      },
      {
        name: 'scrollHideDelay',
        type: 'number',
        default: '600',
        defaultEn: '600',
        description: '滚动结束后延迟隐藏的毫秒数（type 为 hover / scroll 时）。',
        descriptionEn: 'Milliseconds before hide after scroll (hover / scroll types).',
      },
      {
        name: 'height',
        type: 'string | number',
        default: "'14rem'",
        defaultEn: "'14rem'",
        description: '视口高度。数字按 px。',
        descriptionEn: 'Viewport height. A number is px.',
      },
      {
        name: 'maxHeight',
        type: 'string | number',
        description: '最大高度。',
        descriptionEn: 'Max height.',
      },
      {
        name: 'minHeight',
        type: 'string | number',
        description: '最小高度。',
        descriptionEn: 'Min height.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '可滚动内容。',
        descriptionEn: 'Scrollable content.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件 scroll / change。滚动是视口上的原生行为。',
        descriptionEn: 'No component scroll or change event. Scrolling is native on the viewport.',
      },
    ],
    methods: [
      {
        name: 'scrollTop',
        type: '() => void',
        description: '宿主调用。把视口滚到顶部。',
        descriptionEn: 'Host call. Scroll the viewport to the top.',
      },
      {
        name: 'scrollTopLeft',
        type: '() => void',
        description: '宿主调用。把视口滚到左上角。',
        descriptionEn: 'Host call. Scroll the viewport to the top-left.',
      },
      {
        name: 'getViewport',
        type: '() => HTMLElement | undefined',
        description: '宿主调用。返回视口 DOM；尚未挂载时为 undefined。',
        descriptionEn: 'Host call. Return the viewport element, or undefined before mount.',
      },
    ],
    tokens: [
      {
        name: '--rs-scrollbar-size / --rs-scrollbar-padding',
        default: '13px / 2px',
        description: '滑轨厚度与内边距。',
        descriptionEn: 'Track thickness and padding.',
      },
    ],
    faq: [
      {
        q: '为什么没有 direction？',
        a: '方向字段是 orientation。direction 不是公开 API。',
        qEn: 'Why is there no direction prop?',
        aEn: 'The field is orientation. direction is not public API.',
      },
      {
        q: '怎么滚回顶部？',
        a: '模板 ref 调 scrollTop()。没有组件 scroll 事件。',
        qEn: 'How do I scroll back to the top?',
        aEn: 'Call scrollTop() on the template ref. There is no component scroll event.',
      },
    ],
    related: ['virtual-list', 'split-pane'],
  },
]
