import type { ComponentDoc } from '../types'

const size: [string, string] = ["'ssm' | 'sm' | 'md' | 'lg'", "'md'"]
const radius: [string, string] = ["'none' | 'xs' | 'sm' | 'md' | 'lg' | 'full'", '组件默认值']

export const basicComponents: ComponentDoc[] = [
  {
    slug: 'button',
    name: 'RsButton',
    title: 'Button',
    titleZh: '按钮',
    group: 'basic',
    summary: '触发即时操作。',
    description:
      '按钮用于开始一个即时操作。形态（variant）与语义色（tone）正交：variant 控制实心 / 轮廓 / 幽灵 / 文字 / 链接，tone 只改色相。'
    whenToUse: [
      '主操作、次操作、危险操作需要明确视觉层级时。',
      '工具栏中的图标按钮，需配合 tooltip / aria-label 提供名称。',
      '异步提交时用 loading 锁定点击，并保持旋转指示直到结束。',
    ],
    props: [
      {
        name: 'variant',
        type: "'primary' | 'secondary' | 'default' | 'ghost' | 'danger' | 'link' | 'text'",
        default: "'primary'",
        description: '形态。secondary 等价 default（轮廓 + 浅底）。danger 为历史实心危险按钮。',
      },
      {
        name: 'tone',
        type: "'neutral' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: '随 variant：primary/link 为 primary，danger 为 danger，其余 neutral',
        description: '语义色，与 variant 正交。例：variant="default" tone="warning"。',
      },
      { name: 'size', type: size[0], default: size[1], description: '控件尺寸，跟随 ConfigProvider.control-size。' },
      { name: 'radius', type: radius[0], default: "'full'", description: '圆角档位。直角界面传 none。' },
      { name: 'type', type: "'button' | 'submit' | 'reset'", default: "'button'", description: '原生 button type。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用。' },
      { name: 'loading', type: 'boolean', default: 'false', description: '加载中：展示旋转指示并禁止点击。' },
      { name: 'bordered', type: 'boolean', default: 'text/link 为 false，其余 true', description: '是否绘制外边框。' },
      { name: 'icon', type: 'string', description: '前缀图标，Lucide kebab-case 名称。' },
      { name: 'iconOnly', type: 'boolean', default: 'false', description: '仅图标。必须提供 tooltip 或 ariaLabel。' },
      { name: 'tooltip', type: 'string', description: '悬浮提示，Teleport 到 body。' },
      { name: 'ariaLabel', type: 'string', description: '仅图标时的无障碍名称。' },
      { name: 'revealLabel', type: 'boolean', default: 'false', description: '默认收起文字，悬停展开。需配合默认插槽。' },
    ],
    slots: [{ name: 'default', type: '—', description: '按钮文案。' }],
    tokens: [
      { name: '--rs-btn-outline-border', default: '亮色 #6e6e73 / 暗色 #a3a3a3', description: '轮廓按钮描边。' },
      { name: '--rs-btn-secondary-bg', default: '浅底', description: 'default/secondary 背景。' },
      { name: '--rs-btn-secondary-bg-hover', default: '主色浅底', description: '悬浮背景。' },
      { name: '--rs-btn-radius', default: 'var(--rs-radius-full)', description: '由 radius prop 写入。' },
    ],
    faq: [
      {
        q: 'secondary 和 default 有什么区别？',
        a: '没有。secondary 是 default 的别名，便于从「主/次操作」语义迁移。推荐新代码写 default 或直接写 secondary。',
      },
      {
        q: '如何做「描边警告按钮」？',
        a: '使用 variant="default" tone="warning"，不要再写业务 CSS 去改颜色。',
      },
    ],
    related: ['link', 'dropdown', 'tooltip'],
  },
  {
    slug: 'icon',
    name: 'RsIcon',
    title: 'Icon',
    titleZh: '图标',
    group: 'basic',
    summary: '按名称渲染 Lucide 与业务图标。',
    description:
      '图标组件按字符串名称渲染 Lucide，以及工作台内置品牌 mark（mysql、redis、postgres 等）。尺寸优先跟随控件档位，业务不要硬编码 px，除非图标脱离控件独立展示。',
    whenToUse: [
      '按钮、输入框、空状态等需要语义图标时。',
      '需要在运行时按名称切换图标，而不是每个文件静态 import 图标组件。',
      '连接树 / 数据源需要品牌 mark 时，用内置名（见 rsBrandIconNames），不要另画一套。',
    ],
    props: [
      { name: 'name', type: 'string', description: '图标名，Lucide kebab-case，或内置品牌名如 mysql。' },
      { name: 'size', type: 'number', description: '像素边长。控件内通常由父组件传入档位默认值。' },
      { name: 'color', type: 'string', description: '覆盖颜色。品牌 mark 会写入对应 --rs-icon-*-accent。' },
      { name: 'label', type: 'string', description: '有值时作为语义图标（role=img）；无值时装饰性。' },
    ],
    tokens: [
      { name: '--rs-icon-color', default: 'currentColor', description: 'Lucide 线标默认色。' },
      { name: '--rs-icon-mysql-accent', default: '#4479a1 / #5a9fd4', description: 'MySQL mark。' },
      { name: '--rs-icon-redis-accent', default: '#dc382d / #ff6f61', description: 'Redis mark。' },
      { name: '--rs-icon-postgres-accent', default: '#336791 / #6a9ec4', description: 'PostgreSQL mark。' },
      { name: '--rs-icon-mongodb-accent', default: '#47a248 / #5cb85c', description: 'MongoDB mark。' },
    ],
    related: ['button', 'empty'],
  },
  {
    slug: 'link',
    name: 'RsLink',
    title: 'Link',
    titleZh: '链接',
    group: 'basic',
    summary: '文字链接。',
    description: '用于页面内跳转或打开外部文档的文字链接。外观跟随主色，可禁用。按钮形态的导航请用 RsButton variant="link"。',
    whenToUse: [
      '段落或描述列表中的导航文字。',
      '需要与正文混排，而不是独立按钮时。',
    ],
    props: [
      { name: 'href', type: 'string', description: '链接地址。' },
      { name: 'target', type: 'string', description: '原生 target，外链建议 _blank。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用跳转。' },
    ],
    slots: [{ name: 'default', type: '—', description: '链接文案。' }],
    related: ['button', 'breadcrumb'],
  },
  {
    slug: 'badge',
    name: 'RsBadge',
    title: 'Badge',
    titleZh: '徽标',
    group: 'basic',
    summary: '状态与数量标记。',
    description: '徽标用于展示状态、计数或分类标签的轻量标记。颜色走 variant，与 Tag 相比更紧凑、不可关闭。',
    whenToUse: [
      '需要在标题、头像或菜单旁标记数量 / 状态时。',
      '只需色块文字、不需要关闭或交互时（关闭请用 Tag）。',
    ],
    props: [
      {
        name: 'variant',
        type: "'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'default'",
        description: '语义色。',
      },
    ],
    slots: [{ name: 'default', type: '—', description: '徽标内容。' }],
    related: ['tag', 'avatar'],
  },
  {
    slug: 'tag',
    name: 'RsTag',
    title: 'Tag',
    titleZh: '标签',
    group: 'basic',
    summary: '分类与状态标签。',
    description: '标签用于标记对象属性、筛选条件或状态。可关闭、可禁用，尺寸与圆角走统一档位。',
    whenToUse: [
      '展示分类、环境、状态等离散属性。',
      '需要用户移除某个已选项时（closable）。',
      '一组可增删的标签请用 DynamicTags。',
    ],
    props: [
      {
        name: 'variant',
        type: "'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'default'",
        description: '语义色。',
      },
      { name: 'closable', type: 'boolean', default: 'false', description: '显示关闭按钮。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用关闭与交互。' },
      { name: 'round', type: 'boolean', default: 'false', description: '胶囊圆角，等价 radius="full"。' },
      { name: 'size', type: size[0], description: '尺寸。' },
      { name: 'radius', type: radius[0], default: "'sm'", description: '圆角档位。' },
    ],
    events: [{ name: 'close', type: '(event: MouseEvent) => void', description: '点击关闭。' }],
    slots: [{ name: 'default', type: '—', description: '标签文案。' }],
    related: ['dynamic-tags', 'badge'],
  },
  {
    slug: 'divider',
    name: 'RsDivider',
    title: 'Divider',
    titleZh: '分割线',
    group: 'basic',
    summary: '区隔内容的水平或垂直线。',
    description: '分割线用于分隔不同内容区块。支持水平 / 垂直，以及中间标题。',
    whenToUse: [
      '表单分组、卡片区块之间需要视觉分隔。',
      '工具栏按钮组之间的竖线分隔。',
    ],
    props: [
      { name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'", description: '方向。' },
      { name: 'dashed', type: 'boolean', default: 'false', description: '虚线。' },
      { name: 'label', type: 'string', description: '中间标题。也可用默认插槽。' },
    ],
    slots: [{ name: 'default', type: '—', description: '分割线标题。' }],
    related: ['card', 'fieldset'],
  },
  {
    slug: 'avatar',
    name: 'RsAvatar',
    title: 'Avatar',
    titleZh: '头像',
    group: 'basic',
    summary: '用户或对象的头像，失败时回退文案。',
    description: '展示用户、项目或连接的头像。图片加载失败时回退到文字缩写。',
    whenToUse: [
      '列表、评论、顶栏需要识别主体时。',
      '没有图片资源时用文字回退保持占位一致。',
    ],
    props: [
      { name: 'src', type: 'string', description: '图片地址。' },
      { name: 'alt', type: 'string', description: '替代文本。' },
      { name: 'fallback', type: 'string', description: '无图或失败时的文案。' },
      { name: 'size', type: size[0], description: '尺寸。' },
    ],
    related: ['badge', 'card'],
  },
  {
    slug: 'card',
    name: 'RsCard',
    title: 'Card',
    titleZh: '卡片',
    group: 'basic',
    summary: '承载一组相关内容的容器。',
    description: '卡片将标题、操作与主体收进同一表面。表单分区请用 Fieldset，不要用 Card 冒充分组语义。',
    whenToUse: [
      '仪表盘指标、设置区块、预览摘要等需要独立表面时。',
      '需要标题栏 + 内容 + 可选页脚的信息组。',
    ],
    props: [
      { name: 'title', type: 'string', description: '标题。也可用 #header。' },
      { name: 'variant', type: 'string', description: '表面变体。' },
      { name: 'size', type: 'string', description: '内边距档位。' },
    ],
    slots: [
      { name: 'header', type: '—', description: '自定义标题区。' },
      { name: 'default', type: '—', description: '主体。' },
      { name: 'footer', type: '—', description: '页脚。' },
    ],
    related: ['stat-card', 'fieldset', 'container'],
  },
  {
    slug: 'container',
    name: 'RsContainer',
    title: 'Container',
    titleZh: '容器',
    group: 'basic',
    summary: '限制内容宽度并提供统一内边距。',
    description: '页面级内容容器，控制最大宽度、水平内边距与是否居中。文档页与设置页用它统一版心。',
    whenToUse: [
      '需要把正文限制在可读宽度内。',
      '多页面共用同一套边距时。',
    ],
    props: [
      { name: 'maxWidth', type: "'sm' | 'md' | 'lg' | 'xl' | 'full'", description: '最大宽度档位。' },
      { name: 'padding', type: "'none' | 'sm' | 'md' | 'lg'", description: '内边距。' },
      { name: 'centered', type: 'boolean', description: '水平居中。' },
    ],
    related: ['card', 'scrollbar'],
  },
  {
    slug: 'scrollbar',
    name: 'RsScrollbar',
    title: 'Scrollbar',
    titleZh: '滚动条',
    group: 'basic',
    summary: '自定义滚动区域。',
    description: '在固定高度容器内提供与主题一致的滚动条。侧栏、下拉面板、日志预览应优先使用，避免各端原生滚动条风格分裂。',
    whenToUse: [
      '侧栏、弹层、分栏中需要内部滚动。',
      '需要隐藏原生滚动条并保持键盘可达时。',
    ],
    props: [
      { name: 'direction', type: "'vertical' | 'horizontal'", description: '滚动方向。' },
    ],
    slots: [{ name: 'default', type: '—', description: '可滚动内容。' }],
    related: ['virtual-list', 'split-pane'],
  },
]
