import type { ComponentDoc } from '../types'

export const dataComponents: ComponentDoc[] = [
  {
    slug: 'table',
    name: 'RsTable',
    title: 'Table',
    titleZh: '表格',
    group: 'data',
    summary: '结构化数据：排序、选择、虚拟滚动、编辑与树表。',
    description:
      '工作台核心数据控件。支持排序、行选择、虚拟滚动、单元格/行编辑与树列表。架构、SSR、图表适配见仓库 docs/rs-table-*.md。子能力（单元格编辑、行提交、树表）在本站分页说明。',
    whenToUse: [
      '二维结构化数据，需要列对齐、排序或选择。',
      '上万行时开启虚拟滚动，不要用原生 table 硬渲。',
      '层级 + 列对齐用树表；纯层级用 Tree。',
    ],
    props: [
      { name: 'columns', type: 'RsTableColumn[]', description: '列定义。' },
      { name: 'data / rows', type: 'T[]', description: '行数据。' },
      { name: 'rowKey', type: 'string | ((row) => string)', description: '行标识。' },
      { name: 'virtual', type: 'boolean', description: '虚拟滚动。' },
      { name: 'selectable', type: 'boolean', description: '行选择。' },
    ],
    slots: [{ name: 'cell / empty', type: '—', description: '单元格与空态。' }],
    faq: [
      {
        q: '和原生 table 或第三方网格怎么选？',
        a: '本组件面向控制台：主题 Token、行编辑、树表与虚拟滚动一体。极端单元格数量或 Excel 公式请评估专用网格。',
      },
    ],
    related: ['table-tree', 'pagination', 'virtual-list'],
  },
  {
    slug: 'table-cell-edit',
    name: 'RsTable',
    title: 'Table',
    titleZh: '单元格编辑',
    group: 'data',
    summary: '表格内就地编辑单元格。',
    description: '在单元格内打开编辑器并写回行数据。适合少量字段的快速改值；整行校验与提交见行提交。',
    whenToUse: ['运维配置表、可改的状态列。'],
    props: [{ name: 'columns[].editable', type: 'boolean | Editor', description: '列是否可编辑及编辑器。' }],
    related: ['table', 'table-row-commit'],
  },
  {
    slug: 'table-row-commit',
    name: 'RsTable',
    title: 'Table',
    titleZh: '行提交',
    group: 'data',
    summary: '行级编辑、校验后提交。',
    description: '进入行编辑，确认后一次性提交。适合需要校验多列再落库的场景。',
    whenToUse: ['新增行、修改后需要确认/取消。'],
    props: [{ name: 'rowEdit', type: 'boolean | options', description: '行编辑模式。' }],
    related: ['table', 'form'],
  },
  {
    slug: 'table-row-select',
    name: 'RsTable',
    title: 'Table',
    titleZh: '行多选',
    group: 'data',
    summary: '不依赖 Checkbox 列的行选择。',
    description: '点击行或键盘漫游进行多选，适用于密度高、不希望再占一列勾选框的控制台。',
    whenToUse: ['批量操作但不想增加勾选列。'],
    props: [{ name: 'rowSelect', type: 'options', description: '行选择交互。' }],
    related: ['table', 'checkbox'],
  },
  {
    slug: 'table-tree',
    name: 'RsTable',
    title: 'Table',
    titleZh: '树列表',
    group: 'data',
    summary: '带列的树：缩进、过滤、懒加载与虚拟。',
    description: '对象树需要属性列时用树表。纯导航树用 RsTree。',
    whenToUse: ['库 / 表 / 列、进程树、权限树且每节点有多列属性。'],
    props: [
      { name: 'tree', type: 'boolean | options', description: '启用树模式。' },
      { name: 'lazy', type: 'boolean', description: '懒加载子节点。' },
    ],
    related: ['table', 'tree'],
  },
  {
    slug: 'tree',
    name: 'RsTree',
    title: 'Tree',
    titleZh: '树',
    group: 'data',
    summary: '层级数据：勾选、拖拽、过滤与虚拟。',
    description: '文件树、对象树、权限树。支持勾选、拖拽排序、过滤与虚拟滚动。表单里选节点用 TreeSelect。',
    whenToUse: ['主导航或资源树。', '需要列对齐时用树表。'],
    props: [
      { name: 'data', type: 'TreeNode[]', description: '节点。' },
      { name: 'selectable / checkable', type: 'boolean', description: '选中 / 勾选。' },
      { name: 'draggable', type: 'boolean', description: '拖拽。' },
      { name: 'virtual', type: 'boolean', description: '虚拟滚动。' },
    ],
    related: ['tree-select', 'table-tree'],
  },
  {
    slug: 'virtual-list',
    name: 'RsVirtualList',
    title: 'VirtualList',
    titleZh: '虚拟列表',
    group: 'data',
    summary: '只渲染可视区的长列表。',
    description: '日志行、命令面板结果等一维长列表。二维数据用 Table 的虚拟模式。',
    whenToUse: ['数千条以上的一维列表。'],
    props: [
      { name: 'items', type: 'T[]', description: '数据。' },
      { name: 'itemSize', type: 'number', description: '行高。' },
    ],
    related: ['table', 'log', 'scrollbar'],
  },
  {
    slug: 'descriptions',
    name: 'RsDescriptions',
    title: 'Descriptions',
    titleZh: '描述列表',
    group: 'data',
    summary: '只读字段的键值展示。',
    description: '详情页展示只读属性。编辑请用 Form。',
    whenToUse: ['资源详情、只读配置摘要。'],
    props: [
      { name: 'column', type: 'number', description: '列数。' },
      { name: 'size', type: 'string', description: '密度。' },
    ],
    slots: [{ name: 'default', type: '—', description: 'DescriptionsItem。' }],
    related: ['form', 'card'],
  },
  {
    slug: 'stat-card',
    name: 'RsStatCard',
    title: 'StatCard',
    titleZh: '指标卡',
    group: 'data',
    summary: '单个指标的摘要卡片。',
    description: '仪表盘上的 KPI：标题、数值、辅助说明与趋势位。',
    whenToUse: ['概览页需要扫读几个核心数字。'],
    props: [
      { name: 'title', type: 'string', description: '指标名。' },
      { name: 'value', type: 'string | number', description: '数值。' },
    ],
    related: ['card', 'descriptions'],
  },
]
