import type { ComponentDoc } from '../types'

export const dataComponents: ComponentDoc[] = [
  {
    slug: 'table',
    name: 'RsTable',
    title: 'Table',
    titleZh: '表格',
    group: 'data',
    summary: '结构化数据：排序、选择、虚拟滚动、编辑与树表。',
    description:
      '工作台核心数据控件。支持排序、行选择、虚拟滚动、单元格/行编辑与树列表。架构、SSR、图表适配见仓库 docs/rs-table-*.md。子能力（单元格编辑、行提交、树表）在本站分页说明。',
    whenToUse: [
      '二维结构化数据，需要列对齐、排序或选择。',
      '上万行时开启虚拟滚动，不要用原生 table 硬渲。',
      '层级 + 列对齐用树表；纯层级用 Tree。',
    ],
    props: [
      { name: 'columns', type: 'RsTableColumn[]', description: '列定义。' },
      { name: 'data / rows', type: 'T[]', description: '行数据。' },
      { name: 'rowKey', type: 'string | ((row) => string)', description: '行标识。' },
      { name: 'virtual', type: 'boolean', description: '虚拟滚动。' },
      { name: 'selectable', type: 'boolean', description: '行选择。' },
    ],
    slots: [{ name: 'cell / empty', type: '—', description: '单元格与空态。' }],
    faq: [
      {
        q: '和原生 table 或第三方网格怎么选？',
        a: '本组件面向控制台：主题 Token、行编辑、树表与虚拟滚动一体。极端单元格数量或 Excel 公式请评估专用网格。',
      },
    ],
    related: ['table-tree', 'pagination', 'virtual-list'],
  },
  {
    slug: 'table-cell-edit',
    name: 'RsTable',
    title: 'Table',
    titleZh: '单元格编辑',
    group: 'data',
    summary: '表格内就地编辑单元格。',
    description: '在单元格内打开编辑器并写回行数据。适合少量字段的快速改值；整行校验与提交见行提交。',
    whenToUse: ['运维配置表、可改的状态列。'],
    props: [{ name: 'columns[].editable', type: 'boolean | Editor', description: '列是否可编辑及编辑器。' }],
    related: ['table', 'table-row-commit'],
  },
  {
    slug: 'table-row-commit',
    name: 'RsTable',
    title: 'Table',
    titleZh: '行提交',
    group: 'data',
    summary: '行级编辑、校验后提交。',
    description: '进入行编辑，确认后一次性提交。适合需要校验多列再落库的场景。',
    whenToUse: ['新增行、修改后需要确认/取消。'],
    props: [{ name: 'rowEdit', type: 'boolean | options', description: '行编辑模式。' }],
    related: ['table', 'form'],
  },
  {
    slug: 'table-row-select',
    name: 'RsTable',
    title: 'Table',
    titleZh: '行多选',
    group: 'data',
    summary: '不依赖 Checkbox 列的行选择。',
    description: '点击行或键盘漫游进行多选，适用于密度高、不希望再占一列勾选框的控制台。',
    whenToUse: ['批量操作但不想增加勾选列。'],
    props: [{ name: 'rowSelect', type: 'options', description: '行选择交互。' }],
    related: ['table', 'checkbox'],
  },
  {
    slug: 'table-tree',
    name: 'RsTable',
    title: 'Table',
    titleZh: '树列表',
    group: 'data',
    summary: '带列的树：缩进、过滤、懒加载与虚拟。',
    description: '对象树需要属性列时用树表。纯导航树用 RsTree。',
    whenToUse: ['库 / 表 / 列、进程树、权限树且每节点有多列属性。'],
    props: [
      { name: 'tree', type: 'boolean | options', description: '启用树模式。' },
      { name: 'lazy', type: 'boolean', description: '懒加载子节点。' },
    ],
    related: ['table', 'tree'],
  },
  {
    slug: 'tree',
    name: 'RsTree',
    title: 'Tree',
    titleZh: '树',
    group: 'data',
    summary: '层级数据：勾选、拖拽、过滤与虚拟。',
    description: '文件树、对象树、权限树。支持勾选、拖拽排序、过滤与虚拟滚动。表单里选节点用 TreeSelect。',
    whenToUse: ['主导航或资源树。', '需要列对齐时用树表。'],
    props: [
      { name: 'data', type: 'TreeNode[]', description: '节点。' },
      { name: 'selectable / checkable', type: 'boolean', description: '选中 / 勾选。' },
      { name: 'draggable', type: 'boolean', description: '拖拽。' },
      { name: 'virtual', type: 'boolean', description: '虚拟滚动。' },
    ],
    related: ['tree-select', 'table-tree'],
  },
  {
    slug: 'virtual-list',
    name: 'RsVirtualList',
    title: 'VirtualList',
    titleZh: '虚拟列表',
    group: 'data',
    summary: '只渲染可视区的长列表。',
    description:
      '日志行、命令面板、消息流等一维长列表。根是原生 overflow，不包 Reka。定高、按索引变高，或先估算再量内容。二维数据用 Table 的虚拟模式。',
    descriptionEn:
      'One-dimensional lists: logs, command results, message streams. The root is native overflow — no Reka. Sizes can be fixed, a function of the index, or measured. Use Table virtual for two-dimensional data.',
    whenToUse: [
      '同一份数据有数千行，只滚动、不切页。',
      '行高固定，或能按索引算出来。内容高度未知时用 itemSize="auto"。',
      '要分页、跳转、每页条数用 Pagination。子节点不多、要画滚动条用 Scrollbar。表格行用 Table virtual。',
    ],
    whenToUseEn: [
      'One dataset with thousands of rows that scrolls and does not page.',
      'Row size is fixed, or a function of the index. Use itemSize="auto" when content height is unknown.',
      'Use Pagination to page. Use Scrollbar when every child should mount. Use Table virtual for grid rows.',
    ],
    demos: [
      { id: 'demo-basic', title: '定高', titleEn: 'Fixed size' },
      { id: 'demo-variable', title: '按索引变高', titleEn: 'Variable size' },
      { id: 'demo-active', title: '当前项', titleEn: 'Active row' },
      { id: 'demo-horizontal', title: '横向', titleEn: 'Horizontal' },
      { id: 'demo-auto', title: '测量高度', titleEn: 'Measured size' },
      { id: 'demo-empty', title: '空态', titleEn: 'Empty' },
      { id: 'demo-keyboard', title: '键盘', titleEn: 'Keyboard' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-infinite', title: '无限滚动', titleEn: 'Infinite scroll' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'items',
        type: 'T[]',
        description: '数据。空数组显示 #empty。',
        descriptionEn: 'Items. An empty array shows #empty.',
      },
      {
        name: 'itemSize',
        type: "number | ((index: number) => number) | 'auto'",
        default: '32',
        defaultEn: '32',
        description: '主轴尺寸（纵向是高，横向是宽）。函数按索引返回像素。auto 先用 estimateSize，再量可见项。',
        descriptionEn: 'Main-axis size (height when vertical, width when horizontal). A function returns pixels for that index. auto estimates, then measures visible items.',
      },
      {
        name: 'estimateSize',
        type: 'number',
        default: '32',
        defaultEn: '32',
        description: 'itemSize 为 auto 时，测量前的估算像素。',
        descriptionEn: 'Estimated pixels before measurement when itemSize is auto.',
      },
      {
        name: 'height',
        type: 'number | string',
        default: '240',
        defaultEn: '240',
        description: '交叉轴高度。数字按 px。0 或百分比由父级撑满，内部测量可视长度。',
        descriptionEn: 'Cross-axis height. A number is px. 0 or a percentage fills the parent; the viewport length is measured.',
      },
      {
        name: 'overscan',
        type: 'number',
        default: '4',
        defaultEn: '4',
        description: '可视区两侧多渲染的条数。',
        descriptionEn: 'Extra items rendered on each side of the viewport.',
      },
      {
        name: 'v-model:active-index',
        type: 'number | null',
        default: 'null',
        defaultEn: 'null',
        description: '当前项。变化后滚进视口，默认居中。',
        descriptionEn: 'Active index. Changes scroll it into view, centered by default.',
      },
      {
        name: 'layoutActive',
        type: 'boolean',
        description: 'keep-alive 外层变为可见时重测视口并读回滚动位置。',
        descriptionEn: 'When a keep-alive parent becomes visible, remeasure the viewport and read the scroll position back.',
      },
      {
        name: 'radius',
        type: "'none' | 'xs' | 'sm' | 'md' | 'lg' | 'full'",
        default: "'sm'",
        defaultEn: "'sm'",
        description: '外层圆角。直角传 none。',
        descriptionEn: 'Outer radius. Pass none for square corners.',
      },
      {
        name: 'orientation',
        type: "'vertical' | 'horizontal'",
        default: "'vertical'",
        defaultEn: "'vertical'",
        description: '滚动轴。横向时 itemSize 是宽。',
        descriptionEn: 'Scroll axis. When horizontal, itemSize is the width.',
      },
      {
        name: 'itemKey',
        type: '(item: T, index: number) => string | number',
        description: '稳定键。不传时用索引，滚动时复用同一批节点。',
        descriptionEn: 'Stable key. Defaults to the index so the same nodes are reused while scrolling.',
      },
      {
        name: 'keyboard',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '方向键 / Home / End 移动当前项。默认关，避免抢走外层键盘。打开后根是 listbox。',
        descriptionEn: 'Arrow keys / Home / End move the active item. Off by default so a parent can keep the keys. On makes the root a listbox.',
      },
      {
        name: 'bordered',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '外框。嵌进已有表面时关掉。',
        descriptionEn: 'Outer frame. Turn off when the list sits in an existing surface.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '可访问名称。keyboard 且未传时用 virtualList.label。',
        descriptionEn: 'Accessible name. When keyboard is on and this is omitted, virtualList.label is used.',
      },
      {
        name: 'id',
        type: 'string',
        description: '根节点 id。不传时自动生成，供 aria-activedescendant。',
        descriptionEn: 'Root id. Generated when omitted, for aria-activedescendant.',
      },
    ],
    events: [
      {
        name: 'scroll',
        type: '[event: Event]',
        description: '原生滚动。载荷是 Event，读 event.target 的 scrollTop / scrollLeft。',
        descriptionEn: 'Native scroll. The payload is the Event; read scrollTop / scrollLeft on event.target.',
      },
      {
        name: 'update:activeIndex',
        type: '[index: number | null]',
        description: 'v-model:active-index。点击或键盘改当前项时发出。',
        descriptionEn: 'v-model:active-index. Emitted when a click or key changes the active item.',
      },
      {
        name: 'change',
        type: '[index: number, item: T]',
        description: '点击一行，或键盘移到另一行。',
        descriptionEn: 'A row click, or a key that moves to another row.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '{ item: T, index: number }',
        description: '可见项。只渲染窗口，不要在外面再 v-for 全量数据。',
        descriptionEn: 'A visible item. Only the window is rendered; do not v-for the full list outside.',
      },
      {
        name: 'empty',
        type: '—',
        description: 'items 为空。不传时用 virtualList.empty。',
        descriptionEn: 'Shown when items is empty. Defaults to virtualList.empty.',
      },
    ],
    methods: [
      {
        name: 'scrollToIndex',
        type: "(index: number, align?: 'nearest' | 'center' | 'start' | 'end') => void",
        description: '宿主调用。把该项滚进视口。align 默认 center。越界无操作。',
        descriptionEn: 'Host call. Scroll that index into view. align defaults to center. Out of range does nothing.',
      },
      {
        name: 'scrollToOffset',
        type: '(offset: number) => void',
        description: '宿主调用。滚到内容偏移（像素，从起点算）。超长列表会映射到压缩后的滚动条。',
        descriptionEn: 'Host call. Scroll to a content offset in pixels from the start. Very long lists map onto the compressed scrollbar.',
      },
      {
        name: 'getScrollOffset',
        type: '() => number',
        description: '宿主调用。返回内容偏移。未挂载时按当前状态估算。',
        descriptionEn: 'Host call. Return the content offset. Before mount, estimate from current state.',
      },
      {
        name: 'getViewport',
        type: '() => HTMLElement | undefined',
        description: '宿主调用。返回滚动根节点。未挂载时为 undefined。',
        descriptionEn: 'Host call. Return the scroll root, or undefined before mount.',
      },
      {
        name: 'focus',
        type: '() => void',
        description: '宿主调用。聚焦滚动根。keyboard 为 true 时根在 Tab 序里。',
        descriptionEn: 'Host call. Focus the scroll root. The root is in tab order when keyboard is true.',
      },
    ],
    tokens: [
      {
        name: '--rs-virtual-list-border / --rs-virtual-list-bg / --rs-virtual-list-fg',
        default: 'theme',
        description: '边框、表面、文字。随 data-rs-theme。',
        descriptionEn: 'Border, surface, and text. Follow data-rs-theme.',
      },
      {
        name: '--rs-virtual-list-accent / --rs-virtual-list-accent-width / --rs-virtual-list-active-bg',
        default: 'primary / 0.125rem / mix',
        description: '当前项色条与底。色条在逻辑起点，RTL 跟书写方向。',
        descriptionEn: 'Active bar and fill. The bar sits on the logical start edge so RTL follows writing direction.',
      },
      {
        name: '--rs-virtual-list-radius',
        default: 'runtime',
        description: '由 radius 写入，对应 --rs-radius-*。',
        descriptionEn: 'Written from radius, mapped to --rs-radius-*.',
      },
      {
        name: '--rs-focus-ring-width / --rs-focus-border',
        default: 'theme',
        description: 'keyboard 时的焦点环。',
        descriptionEn: 'Focus ring when keyboard is on.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 overflow。业务与文档站不要 import reka-ui。滚动、窗口和 scrollToIndex 语义与原来相同。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is native overflow. Apps and the docs site must not import reka-ui. Scroll, the window, and scrollToIndex behave as before.',
      },
      {
        q: 'itemSize 函数为什么以前看起来没生效？',
        a: '现在按索引累加高度。函数请保持稳定引用，不要在模板里每次渲染新建，否则万行会反复重算。',
        qEn: 'Why did an itemSize function seem ignored?',
        aEn: 'Heights are now summed per index. Keep the function referentially stable. An inline template function rebuilds the table on every render.',
      },
      {
        q: '和 Scrollbar、Pagination、Table 怎么选？',
        a: '子节点都要挂上用 Scrollbar。切页用 Pagination。列对齐用 Table virtual。这里只做一维窗口。',
        qEn: 'When should I use Scrollbar, Pagination, or Table instead?',
        aEn: 'Use Scrollbar when every child should mount. Use Pagination to page. Use Table virtual for aligned columns. This component is a one-dimensional window.',
      },
      {
        q: '点击为什么会改当前项？日志键盘呢？',
        a: '点击发 change，并写 v-model:active-index。keyboard 默认 false，方向键留给外层（例如 RsLog）。',
        qEn: 'Why does a click change the active row? What about log keyboard?',
        aEn: 'A click emits change and writes v-model:active-index. keyboard defaults to false so arrow keys stay with the parent (for example RsLog).',
      },
      {
        q: '怎么做无限滚动？',
        a: '听 scroll。距底部小于约一屏时把下一页追加进 items，并用 loading 挡住重复请求。滚到底会继续触发，所以请求中和已到底都要直接返回。组件不内置分页或接口。',
        qEn: 'How do I infinite-scroll?',
        aEn: 'Listen to scroll. Append the next page to items when the end is about a screen away, and ignore further events while a request is in flight or the list is finished. The component does not page or fetch.',
      },
      {
        q: '上百万行会不会把滚动条撑爆？',
        a: '总高度超过 800 万像素时压缩滚动条，屏幕上的行仍是真实像素。scroll 的 Event 不变。卸载会取消动画帧、断开 ResizeObserver，并清掉「滚动中」定时器。',
        qEn: 'Will a million rows blow the scrollbar?',
        aEn: 'Past 8 million pixels the scrollbar is compressed; on-screen rows stay real pixels. The scroll Event is unchanged. Unmount cancels animation frames, disconnects ResizeObserver, and clears the scrolling timer.',
      },
    ],
    related: ['table', 'log', 'scrollbar', 'pagination'],
  },
  {
    slug: 'descriptions',
    name: 'RsDescriptions',
    title: 'Descriptions',
    titleZh: '描述列表',
    group: 'data',
    summary: '只读字段的键值栅格。',
    description:
      '详情页把只读属性排成标签与值。根内是原生 dl，条目是 dt / dd，不包 Reka。数据走 items，自定义内容走默认插槽里的 RsDescriptionsItem。编辑用 Form，大量行列用 Table。没有组件事件，也没有 defineExpose。',
    descriptionEn:
      'A read-only label and value grid for detail pages. The list is a native dl and each entry is dt / dd — no Reka. Pass items, or put RsDescriptionsItem in the default slot. Use Form to edit and Table for large grids. No component events and no defineExpose.',
    whenToUse: [
      '资源详情、配置摘要、只读键值，需要列对齐。',
      '要改值用 Form。上千行或要排序、选择用 Table。单个 KPI 用 StatCard。',
      '不要把它当表格：没有排序、虚拟滚动或单元格编辑。',
    ],
    whenToUseEn: [
      'Resource details and read-only key-value summaries that need aligned labels.',
      'Use Form to edit, Table for thousands of rows or sorting and selection, StatCard for one KPI.',
      'This is not a table: no sorting, virtualization, or cell editing.',
    ],
    demos: [
      { id: 'demo-basic', title: '数据驱动', titleEn: 'Items' },
      { id: 'demo-border', title: '边框', titleEn: 'Border' },
      { id: 'demo-placement', title: '标签位置', titleEn: 'Label placement' },
      { id: 'demo-span', title: '列与跨列', titleEn: 'Columns and span' },
      { id: 'demo-size', title: '尺寸', titleEn: 'Size' },
      { id: 'demo-radius', title: '圆角', titleEn: 'Radius' },
      { id: 'demo-colon', title: '冒号', titleEn: 'Colon' },
      { id: 'demo-label', title: '标签列', titleEn: 'Label column' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-empty', title: '空值', titleEn: 'Empty values' },
      { id: 'demo-scene', title: '详情页', titleEn: 'Detail page' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'title',
        type: 'string',
        description: '标题。未传且无 #title 时不渲染标题。有标题时作为 dl 的可访问名称。',
        descriptionEn: 'Heading. Omitted when neither the prop nor #title is set. When present, it names the dl.',
      },
      {
        name: 'items',
        type: 'RsDescriptionsItemData[]',
        default: '[]',
        defaultEn: '[]',
        description: '数据条目：label、value、span、key。有默认插槽时不渲染 items。',
        descriptionEn: 'Data rows: label, value, span, key. Ignored when the default slot is set.',
      },
      {
        name: 'columns',
        type: 'number',
        default: '3',
        defaultEn: '3',
        description: '列数。小于 1 或非数字时回退到至少 1 列（非数字回退 3）。不是 column。',
        descriptionEn: 'Column count. Values below 1 or non-numeric fall back to at least 1 (non-numeric falls back to 3). The prop name is columns, not column.',
      },
      {
        name: 'labelPlacement',
        type: "'left' | 'top'",
        default: "'left'",
        defaultEn: "'left'",
        description: '标签在值的左侧或上方。',
        descriptionEn: 'Place the label to the side or above the value.',
      },
      {
        name: 'bordered',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '表格外框与单元格分隔。关掉后只剩键值，没有描边。',
        descriptionEn: 'Outer frame and cell rules. Turn off for plain key-value pairs.',
      },
      {
        name: 'size',
        type: "'ssm' | 'sm' | 'md' | 'lg'",
        description: '密度。未传跟 Form / RsConfigProvider.controlSize，再回退 md。',
        descriptionEn: 'Density. Omit to follow Form or RsConfigProvider.controlSize, then md.',
      },
      {
        name: 'radius',
        type: 'RsRadius',
        description: '有边框时的圆角。未传跟 ConfigProvider.controlRadius，再回退 md。',
        descriptionEn: 'Corner radius when bordered. Omit to follow ConfigProvider.controlRadius, then md.',
      },
      {
        name: 'colon',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '标签后追加冒号。字符走 label.colon（zh-CN 全角，en-US 半角），对读屏隐藏。',
        descriptionEn: 'Append a colon after labels. The glyph is label.colon (fullwidth in zh-CN, ASCII in en-US) and is hidden from assistive tech.',
      },
      {
        name: 'labelWidth',
        type: 'number | string',
        description: '左标签列宽。数字按 px。空串、负数和含 ; { } 或 url( 的字符串忽略。',
        descriptionEn: 'Side-label column width. A number is pixels. Empty, negative, and strings containing ; { } or url( are ignored.',
      },
      {
        name: 'labelAlign',
        type: "'start' | 'center' | 'end'",
        default: "'start'",
        defaultEn: "'start'",
        description: '标签在单元格内对齐。start / end 跟书写方向，不要用 left / right。',
        descriptionEn: 'Label alignment inside the cell. start / end follow writing direction. Do not use left / right.',
      },
      {
        name: 'emptyText',
        type: 'string',
        description: '替换 null / undefined。未传走 descriptions.empty（两种内置语言都是 —）。空字符串不显示占位。0 和 "" 不受影响。',
        descriptionEn: 'Replacement for null / undefined. Omit to use descriptions.empty (— in both built-in locales). An empty string hides the placeholder. 0 and "" are unchanged.',
      },
      {
        name: 'id',
        type: 'string',
        description: '根节点 id。',
        descriptionEn: 'Root id.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '覆盖 dl 的可访问名称。未传且有标题时用标题的 aria-labelledby。',
        descriptionEn: 'Override the dl accessible name. When omitted and a title exists, the dl uses aria-labelledby.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。描述列表不是控件。操作放在 #extra 或值里的 RsButton 上。',
        descriptionEn: 'No component events. A description list is not a control. Put actions on RsButton in #extra or in a value.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: 'RsDescriptionsItem。一旦传入，items 不再渲染。',
        descriptionEn: 'RsDescriptionsItem children. When set, items are not rendered.',
      },
      {
        name: 'title',
        type: '—',
        description: '自定义标题。优先于 title。',
        descriptionEn: 'Custom heading. Wins over title.',
      },
      {
        name: 'extra',
        type: '—',
        description: '标题行末尾的操作，例如编辑按钮。',
        descriptionEn: 'Actions at the end of the heading row, such as an edit button.',
      },
      {
        name: 'item-${key}',
        type: '—',
        description: '某条 items 的值。key 缺省时用下标。优先于 value。',
        descriptionEn: 'Value for one items row. The index is used when key is omitted. Wins over value.',
      },
      {
        name: 'label-${key}',
        type: '—',
        description: '某条 items 的标签。key 缺省时用下标。优先于 label。',
        descriptionEn: 'Label for one items row. The index is used when key is omitted. Wins over label.',
      },
      {
        name: 'label（RsDescriptionsItem）',
        type: '—',
        description: '子项自定义标签。优先于 label prop。',
        descriptionEn: 'Custom label on RsDescriptionsItem. Wins over the label prop.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在描述列表 ref 上调方法。',
        descriptionEn: 'No defineExpose. Do not call methods on the descriptions ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-descriptions-border / radius / label-bg',
        default: 'theme',
        description: '外框、圆角、标签底。随 data-rs-theme。不要写死 hex。',
        descriptionEn: 'Frame, radius, and label wash. Follow data-rs-theme. Do not hard-code hex.',
      },
      {
        name: '--rs-descriptions-title / label-fg / value-fg',
        default: 'theme',
        description: '标题、标签、值的文字色。默认接 --rs-text-primary / --rs-text-secondary。',
        descriptionEn: 'Title, label, and value color. They follow --rs-text-primary and --rs-text-secondary.',
      },
      {
        name: '--rs-descriptions-label-width',
        default: '7.5rem',
        description: '左标签列宽。labelWidth 只覆盖当前这一份。',
        descriptionEn: 'Side-label column width. labelWidth overrides it for that instance.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。列表是原生 dl，条目是 dt / dd。业务与文档站不要 import reka-ui。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The list is a native dl and each entry is dt / dd. Apps and the docs site must not import reka-ui.',
      },
      {
        q: '为什么 prop 叫 columns 而不是 column？',
        a: '公开名称一直是 columns。不要再加 column 别名。响应式列数由调用方传入数字，组件不订阅 matchMedia，避免监听泄漏。',
        qEn: 'Why is the prop columns and not column?',
        aEn: 'The public name has always been columns. There is no column alias. Pass a number for responsive layouts. The component does not subscribe to matchMedia, so it does not leak a listener.',
      },
      {
        q: '为什么没有 labelStyle / contentStyle？',
        a: '颜色和圆角走 --rs-descriptions-*、size、radius。列宽用 labelWidth，对齐用 labelAlign。不要在组件上写内联色值。',
        qEn: 'Why is there no labelStyle or contentStyle?',
        aEn: 'Color and radius use --rs-descriptions-*, size, and radius. Width is labelWidth and alignment is labelAlign. Do not pass inline colors.',
      },
      {
        q: '空值为什么是破折号？0 会不会被当成空？',
        a: '只有 null / undefined 显示 descriptions.empty（内置语言是 —）。0 和空字符串原样显示。要改占位传 emptyText，或用 registerRsLocale 覆盖 descriptions.empty。',
        qEn: 'Why is the empty marker an em dash? Does 0 count as empty?',
        aEn: 'Only null and undefined use descriptions.empty (— in the built-in locales). 0 and an empty string render as themselves. Pass emptyText, or override descriptions.empty with registerRsLocale.',
      },
      {
        q: '点了为什么没反应？有没有 click？',
        a: '没有 defineEmits。可感知的点击绑在 #extra 或值里的 RsButton 上。',
        qEn: 'Why does a click do nothing? Is there a click event?',
        aEn: 'There is no defineEmits. Bind a click you can feel on RsButton in #extra or in a value.',
      },
      {
        q: '字段很多会不会卡、会不会泄漏？',
        a: '布局是 CSS grid，不测量、不挂 ResizeObserver、定时器或窗口监听，卸载时没有要摘的订阅。几十条详情没问题。上千行改用 Table 的虚拟滚动。',
        qEn: 'Will a long list jank or leak?',
        aEn: 'Layout is CSS grid. There is no measurement, ResizeObserver, timer, or window listener, and nothing to detach on unmount. Dozens of fields are fine. Use Table virtualization for thousands of rows.',
      },
    ],
    related: ['form', 'card', 'stat-card', 'table'],
  },
  {
    slug: 'stat-card',
    name: 'RsStatCard',
    title: 'StatCard',
    titleZh: '指标卡',
    group: 'data',
    summary: '一张卡片上的一个 KPI：名称、数值、单位与涨跌。',
    description:
      '概览页扫读单个指标。根是原生 section，不包 Reka。label 是名称，不是标题层级。数字默认原样输出，只有 format 或 precision 才按当前 locale 走 Intl。涨跌方向和好坏分开。整块表面用 Card，键值明细用 Descriptions，可编辑数字用 InputNumber。没有组件事件，也没有 defineExpose。',
    descriptionEn:
      'One KPI for an overview. The root is a native section — no Reka. label is the metric name, not a heading level. Numbers render as raw text until format or precision turns on Intl for the current locale. Trend direction is separate from whether the change is good. Use Card for a surface, Descriptions for a key-value list, and InputNumber to edit a number. No component events and no defineExpose.',
    whenToUse: [
      '概览页需要扫读几个核心数字，并带单位或相对上一时段的变化。',
      '同一数字要随 RsConfigProvider.locale 分组、紧凑记法或货币位置变化时，传数字并打开 format。',
      '整页内容容器用 Card。只读字段表用 Descriptions。用户要改的数用 InputNumber。',
    ],
    whenToUseEn: [
      'An overview needs a few core numbers, with a unit or a change from the previous period.',
      'Pass a number and turn on format when grouping, compact notation, or currency placement must follow RsConfigProvider.locale.',
      'Use Card for a content surface, Descriptions for a read-only field list, and InputNumber when the user edits the number.',
    ],
    demos: [
      { id: 'demo-basic', title: '基本用法', titleEn: 'Basic' },
      { id: 'demo-loading', title: '加载', titleEn: 'Loading' },
      { id: 'demo-format', title: '数字与货币', titleEn: 'Numbers and currency' },
      { id: 'demo-trend', title: '涨跌', titleEn: 'Trend' },
      { id: 'demo-affix', title: '单位', titleEn: 'Units' },
      { id: 'demo-size', title: '疏密', titleEn: 'Density' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'label',
        type: 'string',
        description: '指标名。渲染为 p，不是 h1–h6，避免一排 KPI 污染大纲。不是 title。',
        descriptionEn: 'Metric name. Rendered as a p, not h1–h6, so a row of KPIs does not flood the outline. The prop is label, not title.',
      },
      {
        name: 'value',
        type: 'string | number',
        description: '数值。字符串原样显示。有限数字在 format / precision 打开后按 locale 格式化。',
        descriptionEn: 'The figure. Strings render as written. Finite numbers are formatted for the locale only when format or precision is set.',
      },
      {
        name: 'description',
        type: 'string',
        description: '数值下的说明，例如统计区间。',
        descriptionEn: 'Caption under the figure, such as the time window.',
      },
      {
        name: 'accent',
        type: "'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'primary'",
        defaultEn: "'primary'",
        description: '顶角色条。只表示指标类别，不表示涨跌好坏。',
        descriptionEn: 'Top bar. It marks the metric, not whether a trend is good or bad.',
      },
      {
        name: 'loading',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '用骨架代替数值、单位和涨跌，并设 aria-busy。说明和默认插槽仍在。组件内部不排定时器。',
        descriptionEn: 'Replace the figure, units, and trend with a skeleton and set aria-busy. The caption and default slot stay. The component does not start a timer.',
      },
      {
        name: 'prefix',
        type: 'string',
        description: '数值前的短文本。货币符号优先用 format.style=currency，由 locale 决定符号在前还是在后。',
        descriptionEn: 'Short text before the figure. For money, prefer format.style=currency so the locale places the symbol.',
      },
      {
        name: 'suffix',
        type: 'string',
        description: '数值后的单位，例如 ms、req/s。书写方向下仍跟在数字后面。',
        descriptionEn: 'Unit after the figure, such as ms or req/s. It stays after the number in reading order.',
      },
      {
        name: 'trend',
        type: "'up' | 'down' | 'flat'",
        description: '变化方向。上升不自动当成好消息。箭头对读屏隐藏，方向词走 statCard.trend.*。',
        descriptionEn: 'Change direction. Up is not automatically good. The mark is hidden from assistive tech; the word comes from statCard.trend.*.',
      },
      {
        name: 'delta',
        type: 'string | number',
        description: '变化量。字符串原样；数字跟随 format / precision。0 会显示。',
        descriptionEn: 'Change amount. Strings render as written; numbers follow format / precision. 0 is shown.',
      },
      {
        name: 'trendTone',
        type: "'neutral' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'neutral'",
        defaultEn: "'neutral'",
        description: '涨跌文字色。与 trend 独立：错误率上升用 danger，收入上升用 success。',
        descriptionEn: 'Trend text color, independent of trend. An error-rate increase uses danger; a revenue increase uses success.',
      },
      {
        name: 'format',
        type: 'boolean | Intl.NumberFormatOptions',
        default: 'false',
        defaultEn: 'false',
        description: 'false 保持原文。true 用当前 locale 的默认分组。对象传给 Intl.NumberFormat，例如 notation: compact 或 style: currency。',
        descriptionEn: 'false keeps the raw text. true uses the current locale grouping. An object is passed to Intl.NumberFormat, such as notation: compact or style: currency.',
      },
      {
        name: 'precision',
        type: 'number',
        description: '定点小数位数（0–20）。即使 format 为 false 也会格式化数字。字符串 value 不受影响。',
        descriptionEn: 'Fixed fraction digits (0–20). Formats numbers even when format is false. String values are unchanged.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        default: "'md'",
        defaultEn: "'md'",
        description: '疏密：内边距与数值字号。不是控件 size，没有 ssm。',
        descriptionEn: 'Density: padding and figure size. Not control size — no ssm.',
      },
      {
        name: 'id',
        type: 'string',
        description: '根节点 id。',
        descriptionEn: 'Root id.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '把整张卡标成命名区域。默认不设，避免一排 KPI 都变成 landmark。',
        descriptionEn: 'Name the card as a region. Omit it so a row of KPIs does not become a row of landmarks.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。可点的指标卡请在外面包链接或按钮，不要给 StatCard 绑 click。',
        descriptionEn: 'No component events. Wrap a clickable metric in a link or button — do not bind click on StatCard.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '数值和说明下面的附加内容，例如进度或操作按钮。loading 时仍渲染。',
        descriptionEn: 'Extra content under the figure and caption, such as a meter or an action. Still rendered while loading.',
      },
      {
        name: 'value',
        type: '—',
        description: '自定义数值。优先于 value。前后仍可加 prefix / suffix。',
        descriptionEn: 'Custom figure. Wins over value. prefix / suffix can still sit beside it.',
      },
      {
        name: 'prefix',
        type: '—',
        description: '自定义前缀，优先于 prefix。',
        descriptionEn: 'Custom prefix. Wins over prefix.',
      },
      {
        name: 'suffix',
        type: '—',
        description: '自定义后缀，优先于 suffix。',
        descriptionEn: 'Custom suffix. Wins over suffix.',
      },
      {
        name: 'icon',
        type: '—',
        description: '名称行末尾的装饰图标，对读屏隐藏。',
        descriptionEn: 'Decorative icon at the end of the name row. Hidden from assistive tech.',
      },
      {
        name: 'trend',
        type: '—',
        description: '自定义涨跌行，优先于 trend / delta。',
        descriptionEn: 'Custom trend row. Wins over trend / delta.',
      },
      {
        name: 'description',
        type: '—',
        description: '自定义说明，优先于 description。',
        descriptionEn: 'Custom caption. Wins over description.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在指标卡 ref 上调 open / close。',
        descriptionEn: 'No defineExpose. Do not call open or close on the stat card ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-border / --rs-surface / --rs-shadow-sm / --rs-radius',
        default: 'theme',
        description: '边框、表面、阴影、圆角。随 data-rs-theme。',
        descriptionEn: 'Border, surface, shadow, and radius. Follow data-rs-theme.',
      },
      {
        name: '--rs-text-primary / --rs-text-secondary',
        default: 'theme',
        description: '数值与名称、说明的文字色。不写 --rs-text / --rs-muted。',
        descriptionEn: 'Figure, name, and caption color. Do not use --rs-text or --rs-muted.',
      },
      {
        name: '--rs-primary / --rs-success / --rs-warning / --rs-danger / --rs-info',
        default: 'theme',
        description: '色条与 trendTone。accent 写入 --rs-stat-accent。',
        descriptionEn: 'Bar and trendTone. accent sets --rs-stat-accent.',
      },
      {
        name: '--rs-surface-hover',
        default: 'theme',
        description: '加载骨架底色。',
        descriptionEn: 'Loading skeleton fill.',
      },
      {
        name: '--rs-font-size-* / --rs-font-weight-* / --rs-space-*',
        default: 'theme',
        description: '字号、字重、疏密内边距。数值使用 tabular-nums。',
        descriptionEn: 'Type size, weight, and density padding. Figures use tabular-nums.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 section。业务与文档站不要 import reka-ui。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is a native section. Apps and the docs site must not import reka-ui.',
      },
      {
        q: '为什么 prop 叫 label 而不是 title？',
        a: '指标名不是页面标题。用 p 而不是标题标签，一排 KPI 不会打乱大纲。内容卡的标题仍是 Card 的 title。',
        qEn: 'Why is the prop label and not title?',
        aEn: 'A metric name is not a page heading. It is a p, not a heading, so a row of KPIs does not rewrite the outline. Card title is still the heading for a content card.',
      },
      {
        q: '12480 为什么没有千分位？',
        a: '默认关闭格式化，已有页面不会突然变成 12,480 或 1.2万。传数字并设 format，或传 precision。已经拼好的字符串（例如 0.12%）保持原样。',
        qEn: 'Why does 12480 have no grouping separator?',
        aEn: 'Formatting is off by default, so existing pages do not suddenly show 12,480 or 1.2万. Pass a number with format, or pass precision. A string you already built, such as 0.12%, stays as written.',
      },
      {
        q: '上升是不是就是变好？',
        a: '不是。trend 只表示方向，trendTone 表示好坏。错误率上升用 trend="up" trend-tone="danger"。不要只靠颜色：箭头旁有方向词给读屏。',
        qEn: 'Does up mean the metric improved?',
        aEn: 'No. trend is direction and trendTone is whether that is good. An error-rate increase is trend="up" and trend-tone="danger". Color is not the only signal: assistive tech hears the direction word.',
      },
      {
        q: '货币符号该放 prefix 吗？',
        a: '不要。符号在前还是在后、小数位和货币代码都跟 locale。用 format 的 style: currency 与 currency。prefix / suffix 留给 ms、req/s 这种你自己控制的单位。',
        qEn: 'Should the currency symbol go in prefix?',
        aEn: 'No. Symbol placement, fraction digits, and the currency code follow the locale. Use format with style: currency and currency. Keep prefix / suffix for units you control, such as ms or req/s.',
      },
      {
        q: '点了为什么没反应？数值变化会不会被读屏打断？',
        a: '没有 defineEmits，也没有 aria-live。数值更新不会自动播报。需要播报时把卡片放进你自己的 live region。可点操作放在默认插槽的 RsButton 里，或把整张卡包进链接。',
        qEn: 'Why does a click do nothing? Will a value change interrupt a screen reader?',
        aEn: 'There is no defineEmits and no aria-live. Value updates are not announced. Wrap the card in your own live region when they should be. Put a clickable action on RsButton in the default slot, or wrap the card in a link.',
      },
      {
        q: '加载和格式化会不会泄漏或卡顿？',
        a: '没有定时器、窗口监听或 ResizeObserver，卸载时没有要摘的订阅。骨架动画是 CSS，减少动态时停住。Intl.NumberFormat 最多留 24 个，相同 locale 与选项会复用。非法选项回退成原文，不抛错。不要在这里做数字滚动动画。',
        qEn: 'Can loading or formatting leak or jank?',
        aEn: 'There is no timer, window listener, or ResizeObserver, and nothing to detach on unmount. The skeleton is CSS and stops under reduced motion. At most 24 Intl.NumberFormat instances are kept, and the same locale plus options are reused. Invalid options fall back to the raw text and do not throw. Do not add a count-up animation here.',
      },
    ],
    related: ['card', 'descriptions', 'input-number'],
  },
]
