import type { ComponentDoc } from '../types'

export const dataComponents: ComponentDoc[] = [
  {
    slug: 'table',
    name: 'RsTable',
    title: 'Table',
    titleZh: '表格',
    group: 'data',
    summary: '结构化数据：排序、选择、虚拟滚动、编辑与树表。',
    description:
      '外壳是 role=region，表是 role=grid，不包 Reka。列用 columns，行用 data，稳定标识用 row-key。排序、勾选、筛选、虚拟滚动、合计和右键都在这一页。单元格即时提交、整行确认、点行多选和树表分页说明。',
    descriptionEn:
      'The shell is role=region and the table is role=grid — no Reka. columns are the columns, data is the rows, and row-key is the stable id. Sort, selection, filter, virtual scroll, summary, and the context menu are on this page. Cell commit, row commit, click-to-select, and the tree table have their own pages.',
    whenToUse: [
      '二维数据要对齐成列，并要排序、勾选或筛选。',
      '行数上千时给 height 并打开 virtual，不要一次画出全部 tr。',
      '每个节点还有多列属性时用树表。只有名称和图标时用 Tree。',
      '公式、合并单元格或百万格用专用网格，不要把本表当成 Excel。',
    ],
    whenToUseEn: [
      'Align records into columns and sort, select, or filter them.',
      'Set height and virtual once there are thousands of rows. Do not paint every tr.',
      'Use the tree table when each node has several columns. Use Tree when a node is only a label and an icon.',
      'Use a dedicated grid for formulas, merged cells, or millions of cells. This is not a spreadsheet.',
    ],
    demos: [
      { id: 'demo-basic', title: '列与行', titleEn: 'Columns and rows' },
      { id: 'demo-sort', title: '排序', titleEn: 'Sort' },
      { id: 'demo-select', title: '勾选', titleEn: 'Checkbox selection' },
      { id: 'demo-filter', title: '筛选', titleEn: 'Filter' },
      { id: 'demo-size', title: '尺寸与条纹', titleEn: 'Size and stripes' },
      { id: 'demo-empty', title: '空态与加载', titleEn: 'Empty and loading' },
      { id: 'demo-virtual', title: '虚拟滚动', titleEn: 'Virtual scroll' },
      { id: 'demo-slot', title: '单元格插槽', titleEn: 'Cell slot' },
      { id: 'demo-summary', title: '合计', titleEn: 'Summary' },
      { id: 'demo-group', title: '分组', titleEn: 'Group' },
      { id: 'demo-menu', title: '右键', titleEn: 'Context menu' },
      { id: 'demo-methods', title: '实例 API', titleEn: 'Instance API' },
      { id: 'demo-radio', title: '单选', titleEn: 'Radio' },
      { id: 'demo-locked', title: '有的行不能选', titleEn: 'Some rows cannot be selected' },
      { id: 'demo-expand', title: '明细行', titleEn: 'Detail row' },
      { id: 'demo-fixed', title: '固定列', titleEn: 'Fixed columns' },
      { id: 'demo-column-filter', title: '列头筛选', titleEn: 'Header filter' },
      { id: 'demo-multi-sort', title: '多列排序', titleEn: 'Multi-sort' },
      { id: 'demo-remote-sort', title: '远程排序', titleEn: 'Remote sort' },
      { id: 'demo-column-order', title: '拖列', titleEn: 'Reorder columns' },
      { id: 'demo-row-drag', title: '拖行', titleEn: 'Reorder rows' },
      { id: 'demo-resize', title: '列宽', titleEn: 'Resize columns' },
      { id: 'demo-infinite', title: '滚到底再要一页', titleEn: 'Load the next page' },
      { id: 'demo-index', title: '行号与省略', titleEn: 'Index and ellipsis' },
      { id: 'demo-header', title: '自定义列头', titleEn: 'Custom header' },
      { id: 'demo-highlight', title: '高亮当前行', titleEn: 'Highlight the current row' },
      { id: 'demo-theme', title: '主题与方向', titleEn: 'Theme and direction' },
      { id: 'demo-keyboard', title: '键盘', titleEn: 'Keyboard' },
    ],
    props: [
      { name: 'columns', type: 'RsTableColumn<T>[]', description: '列。key、title、width、align（left / center / right，right 画成 text-align: end）、sortable、editable、summary。', descriptionEn: 'Columns. key, title, width, align (left / center / right; right paints as text-align: end), sortable, editable, summary.' },
      { name: 'data', type: 'T[]', description: '行。没有 rows 别名。', descriptionEn: 'Rows. There is no rows alias.' },
      { name: 'rowKey', type: 'string | ((row, index) => string)', description: '稳定行标识。虚拟滚动和选择都靠它。', descriptionEn: 'Stable row id. Virtual scroll and selection depend on it.' },
      { name: 'loading', type: 'boolean', default: 'false', defaultEn: 'false', description: '加载中。表格仍在，aria-busy。', descriptionEn: 'Loading. The grid stays and sets aria-busy.' },
      { name: 'bordered', type: 'boolean', default: 'true', defaultEn: 'true', description: '外边框。', descriptionEn: 'Outer border.' },
      { name: 'columnBordered', type: 'boolean', default: 'false', defaultEn: 'false', description: '列分隔线，走 border-inline-end。', descriptionEn: 'Column dividers, using border-inline-end.' },
      { name: 'rounded', type: 'boolean', default: 'false', defaultEn: 'false', description: '外容器圆角。嵌在已有圆角里时可关掉。', descriptionEn: 'Rounds the shell. Turn it off when the parent is already rounded.' },
      { name: 'fill', type: 'boolean', default: 'false', defaultEn: 'false', description: '撑满父级高度，自己成为滚动容器。', descriptionEn: 'Fills the parent height and becomes the scroll container.' },
      { name: 'compact', type: 'boolean', default: 'false', defaultEn: 'false', description: '为 true 时行高按 sm。', descriptionEn: 'When true, row height follows sm.' },
      { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", defaultEn: "'md'", description: '行高。表格自己的尺寸，不跟 Form。', descriptionEn: 'Row height. The table’s own size; it does not follow Form.' },
      { name: 'scrollX', type: 'number | string', description: '横向最小宽度。数字按 px。', descriptionEn: 'Minimum horizontal width. A number is px.' },
      { name: 'selectable', type: 'boolean', default: 'false', defaultEn: 'false', description: '允许选择。checkbox / radio 出勾选列，row 不出列。', descriptionEn: 'Enables selection. checkbox and radio add a column; row does not.' },
      { name: 'selectionType', type: "'checkbox' | 'radio' | 'row'", default: "'checkbox'", defaultEn: "'checkbox'", description: '选择形态。', descriptionEn: 'Selection mode.' },
      { name: 'v-model:selected-row-keys', type: 'string[]', description: '受控选中键。不传则用 defaultSelectedRowKeys。', descriptionEn: 'Controlled selected keys. Omit it to use defaultSelectedRowKeys.' },
      { name: 'defaultSelectedRowKeys', type: 'string[]', default: '[]', defaultEn: '[]', description: '非受控初始选中。', descriptionEn: 'Initial selection when not controlled.' },
      { name: 'rowSelectable', type: '(row, index) => boolean', description: '这一行能否被选。', descriptionEn: 'Whether this row can be selected.' },
      { name: 'expandable', type: 'boolean', default: 'false', defaultEn: 'false', description: '明细展开行。与树表、分组互斥。', descriptionEn: 'Detail expansion. Mutually exclusive with the tree and with grouping.' },
      { name: 'v-model:expanded-row-keys', type: 'string[]', description: '受控展开键。', descriptionEn: 'Controlled expanded keys.' },
      { name: 'defaultExpandedRowKeys', type: 'string[]', default: '[]', defaultEn: '[]', description: '非受控初始展开。', descriptionEn: 'Initial expansion when not controlled.' },
      { name: 'rowExpandable', type: '(row, index) => boolean', description: '这一行能否展开明细。', descriptionEn: 'Whether this row can expand a detail.' },
      { name: 'expandRowHeight', type: 'number', description: '明细行高度，给虚拟滚动估算。', descriptionEn: 'Detail row height, used by the virtual scroller.' },
      { name: 'treeConfig', type: 'RsTableTreeConfig<T>', description: '树表。children 字段、缩进列、懒加载。与 expandable、groupBy 互斥。', descriptionEn: 'Tree table. Children field, indent column, lazy load. Mutually exclusive with expandable and groupBy.' },
      { name: 'striped', type: 'boolean', default: 'false', defaultEn: 'false', description: '斑马纹。', descriptionEn: 'Zebra rows.' },
      { name: 'showIndex', type: 'boolean', default: 'false', defaultEn: 'false', description: '行号列。', descriptionEn: 'Index column.' },
      { name: 'indexWidth', type: 'number', default: '48', defaultEn: '48', description: '行号列宽（px）。', descriptionEn: 'Index column width in px.' },
      { name: 'showHeader', type: 'boolean', default: 'true', defaultEn: 'true', description: '为 false 时表头视觉隐藏，th 仍在，供读屏。', descriptionEn: 'When false the header is visually hidden. The th cells stay for assistive tech.' },
      { name: 'remoteSort', type: 'boolean', default: 'false', defaultEn: 'false', description: '只发排序事件，不在本地重排。', descriptionEn: 'Emits sort and does not reorder locally.' },
      { name: 'filterText', type: 'string', description: '跨列包含筛选。比较用 toLocaleLowerCase。', descriptionEn: 'Cross-column includes filter. Compare uses toLocaleLowerCase.' },
      { name: 'filterKeys', type: 'string[]', description: 'filterText 只看这些列。', descriptionEn: 'filterText only searches these columns.' },
      { name: 'v-model:column-filters', type: 'Record<string, string>', description: '受控列头筛选。', descriptionEn: 'Controlled per-column header filters.' },
      { name: 'defaultColumnFilters', type: 'Record<string, string>', description: '非受控初始列筛选。', descriptionEn: 'Initial column filters when not controlled.' },
      { name: 'groupBy', type: 'string | ((row) => string)', description: '分组字段。与树表、明细展开互斥。', descriptionEn: 'Group field. Mutually exclusive with the tree and with detail expansion.' },
      { name: 'groupLabel', type: '(key: string) => string', description: '分组标题。', descriptionEn: 'Group title.' },
      { name: 'v-model:sort', type: 'RsTableSortState | null', description: '单列排序。字符串比较跟当前 locale。自定义 sorter 不经过 locale。', descriptionEn: 'Single-column sort. String compare follows the active locale. A custom sorter does not.' },
      { name: 'defaultSort', type: 'RsTableSortState | null', description: '非受控初始排序。', descriptionEn: 'Initial sort when not controlled.' },
      { name: 'multiSort', type: 'boolean', default: 'false', defaultEn: 'false', description: '多列排序。', descriptionEn: 'Multi-column sort.' },
      { name: 'maxSort', type: 'number', default: '3', defaultEn: '3', description: '多列排序最多保留几列。', descriptionEn: 'How many columns multi-sort keeps.' },
      { name: 'v-model:sorts', type: 'RsTableSortState[]', description: '受控多列排序。', descriptionEn: 'Controlled multi-sort.' },
      { name: 'defaultSorts', type: 'RsTableSortState[]', default: '[]', defaultEn: '[]', description: '非受控初始多列排序。', descriptionEn: 'Initial multi-sort when not controlled.' },
      { name: 'columnDraggable', type: 'boolean', default: 'false', defaultEn: 'false', description: '拖拽列顺序。', descriptionEn: 'Drag to reorder columns.' },
      { name: 'v-model:column-order', type: 'string[]', description: '受控列顺序。', descriptionEn: 'Controlled column order.' },
      { name: 'defaultColumnOrder', type: 'string[]', default: '[]', defaultEn: '[]', description: '非受控初始列顺序。', descriptionEn: 'Initial column order when not controlled.' },
      { name: 'rowDraggable', type: 'boolean', default: 'false', defaultEn: 'false', description: '拖拽行。落下位置由 row-drop 交给宿主，组件不改 data。', descriptionEn: 'Drag rows. row-drop tells the host where to drop; the table does not mutate data.' },
      { name: 'rowDragTrigger', type: "'handle' | 'row'", default: "'handle'", defaultEn: "'handle'", description: '手柄或整行拖拽。', descriptionEn: 'Grip or whole-row drag.' },
      { name: 'rowDropMode', type: 'RsTableRowDropMode', default: "'reorder'", defaultEn: "'reorder'", description: '放下语义。', descriptionEn: 'Drop behavior.' },
      { name: 'rowDraggableWhen', type: '(row, index) => boolean', description: '这一行能否拖。', descriptionEn: 'Whether this row can be dragged.' },
      { name: 'rowDropTargetWhen', type: '(row, index) => boolean', description: '这一行能否作为放下目标。', descriptionEn: 'Whether this row can be a drop target.' },
      { name: 'canRowDrop', type: '(dragKeys, dropKey) => boolean', description: '这一次放下是否允许。', descriptionEn: 'Whether this drop is allowed.' },
      { name: 'virtual', type: 'boolean', description: '强制虚拟滚动。未传时，fill 且行数超过 virtualAutoThreshold 会自动打开。', descriptionEn: 'Forces virtual scrolling. When omitted, fill still virtualizes after virtualAutoThreshold.' },
      { name: 'virtualAutoThreshold', type: 'number', default: '50', defaultEn: '50', description: '自动虚拟化的行数阈值。0 关闭自动。', descriptionEn: 'Row count that turns virtualization on. 0 disables the automatic path.' },
      { name: 'virtualColumns', type: "boolean | 'auto'", default: "'auto'", defaultEn: "'auto'", description: '横向只渲染可视列。', descriptionEn: 'Renders only the horizontal window of columns.' },
      { name: 'virtualColumnsAutoThreshold', type: 'number', default: '40', defaultEn: '40', description: '自动列虚拟化的列数。0 关闭。', descriptionEn: 'Column count that turns column virtualization on. 0 disables it.' },
      { name: 'virtualColumnOverscan', type: 'number', default: '2', defaultEn: '2', description: '横向窗口两侧多渲染的列数。', descriptionEn: 'Extra columns rendered on each side.' },
      { name: 'height', type: 'number | string', description: '视口高度。数字按 px。', descriptionEn: 'Viewport height. A number is px.' },
      { name: 'rowHeight', type: 'number', description: '行高像素。未传跟 size。', descriptionEn: 'Row height in px. Follows size when omitted.' },
      { name: 'overscan', type: 'number', default: '4', defaultEn: '4', description: '纵向窗口两侧多渲染的行数。', descriptionEn: 'Extra rows rendered on each side.' },
      { name: 'infinite', type: 'boolean', description: '接近底部发 load-more。', descriptionEn: 'Emits load-more near the bottom.' },
      { name: 'hasMore', type: 'boolean', description: '是否还有下一页。', descriptionEn: 'Whether another page exists.' },
      { name: 'loadingMore', type: 'boolean', description: '正在加载下一页。', descriptionEn: 'The next page is loading.' },
      { name: 'infiniteDistance', type: 'number', default: '80', defaultEn: '80', description: '距底部多少像素触发 load-more。', descriptionEn: 'Pixels from the bottom that emit load-more.' },
      { name: 'virtualOnInfinite', type: 'boolean', default: 'true', defaultEn: 'true', description: '无限加载时仍虚拟化。', descriptionEn: 'Keep virtualization on while loading pages.' },
      { name: 'resizable', type: 'boolean', default: 'false', defaultEn: 'false', description: '拖拽列宽。', descriptionEn: 'Drag to resize columns.' },
      { name: 'columnLayout', type: "'auto' | 'fixed'", default: "'auto'", defaultEn: "'auto'", description: '列宽算法。', descriptionEn: 'Column width algorithm.' },
      { name: 'initialColumnWidths', type: 'Record<string, number>', description: '初始列宽。', descriptionEn: 'Initial column widths.' },
      { name: 'minColumnWidth', type: 'number', default: '48', defaultEn: '48', description: '列宽下限（px）。', descriptionEn: 'Minimum column width in px.' },
      { name: 'maxColumnWidth', type: 'number', default: '640', defaultEn: '640', description: '列宽上限（px）。', descriptionEn: 'Maximum column width in px.' },
      { name: 'selectOnContextmenu', type: 'boolean', description: '右键时先选中该行。', descriptionEn: 'Select the row before opening the menu.' },
      { name: 'contextMenuItems', type: '(row, selectedRows) => RsContextMenuItem[]', description: '右键项。菜单是本库 RsContextMenu。', descriptionEn: 'Context menu items. The menu is this library’s RsContextMenu.' },
      { name: 'contextMenu', type: 'boolean', default: 'true', defaultEn: 'true', description: '关掉后不拦截右键。', descriptionEn: 'When false, the table does not take the context menu.' },
      { name: 'cellTooltip', type: 'boolean', default: 'true', defaultEn: 'true', description: '溢出或列 tooltip 时显示共享提示。', descriptionEn: 'Shows the shared tip on overflow or a column tooltip.' },
      { name: 'cellTooltipDelay', type: 'number', default: '300', defaultEn: '300', description: '提示延迟（毫秒）。', descriptionEn: 'Tip delay in milliseconds.' },
      { name: 'headerTooltip', type: 'boolean', default: 'true', defaultEn: 'true', description: '表头提示。', descriptionEn: 'Header tips.' },
      { name: 'cellFocus', type: "'fill' | 'outline' | 'none'", default: "'fill'", defaultEn: "'fill'", description: '焦点格视觉。none 仍走键盘，只是不画内底。', descriptionEn: 'Focus-cell paint. none still moves with the keyboard and skips the fill.' },
      { name: 'editable', type: 'boolean', default: 'false', defaultEn: 'false', description: '允许单元格编辑。列还要 editable。', descriptionEn: 'Allows cell editing. The column must be editable too.' },
      { name: 'editTrigger', type: "'click' | 'dblclick'", default: "'dblclick'", defaultEn: "'dblclick'", description: '进入编辑的指针。', descriptionEn: 'Pointer that starts an edit.' },
      { name: 'editGutter', type: 'boolean', default: 'true', defaultEn: 'true', description: '行提交时显示行首确认列。', descriptionEn: 'Shows the confirm gutter when row commit is on.' },
      { name: 'editGutterWidth', type: 'number', default: '32', defaultEn: '32', description: '确认列宽（px）。', descriptionEn: 'Gutter width in px.' },
      { name: 'highlightRow', type: 'boolean', default: 'false', defaultEn: 'false', description: '高亮一行。', descriptionEn: 'Highlights one row.' },
      { name: 'v-model:highlighted-row-key', type: 'string', description: '受控高亮行。', descriptionEn: 'Controlled highlighted row.' },
      { name: 'defaultHighlightedRowKey', type: 'string', description: '非受控初始高亮。', descriptionEn: 'Initial highlight when not controlled.' },
      { name: 'highlightRowOnClick', type: 'boolean', default: 'true', defaultEn: 'true', description: '点击写入高亮。', descriptionEn: 'A click writes the highlight.' },
      { name: 'rowCommit', type: 'boolean', default: 'false', defaultEn: 'false', description: '改动先留在行草稿，确认后才发 row-edit-commit。', descriptionEn: 'Edits stay in a row draft until confirm emits row-edit-commit.' },
      { name: 'rowPending', type: '(row, index) => boolean', description: '宿主标记这一行仍有未提交改动。', descriptionEn: 'Host marks this row as still dirty.' },
      { name: 'showRowStatus', type: 'boolean', default: 'true', defaultEn: 'true', description: '行状态列。', descriptionEn: 'Row status column.' },
      { name: 'allowNull', type: 'boolean', default: 'true', defaultEn: 'true', description: '编辑时可把值设为 NULL。', descriptionEn: 'An edit can set the value to NULL.' },
      { name: 'nullLabel', type: 'string', description: '空值文案。未传走 table.nullValue。', descriptionEn: 'Empty-value label. Falls back to table.nullValue.' },
      { name: 'editFocusMode', type: 'RsTableCellEditFocusMode', default: "'end'", defaultEn: "'end'", description: '进入编辑时光标位置。', descriptionEn: 'Caret placement when an edit starts.' },
      { name: 'editKeyboard', type: 'boolean', default: 'true', defaultEn: 'true', description: '编辑键盘：Tab、方向键、撤销。', descriptionEn: 'Edit keyboard: Tab, arrows, undo.' },
      { name: 'editUndo', type: 'boolean', default: 'true', defaultEn: 'true', description: 'Ctrl+Z / Ctrl+Y。', descriptionEn: 'Ctrl+Z / Ctrl+Y.' },
      { name: 'editUndoLimit', type: 'number', default: '50', defaultEn: '50', description: '撤销栈长度。', descriptionEn: 'Undo stack length.' },
      { name: 'editPaste', type: 'boolean', default: 'true', defaultEn: 'true', description: '从剪贴板粘贴进格子。', descriptionEn: 'Paste from the clipboard into cells.' },
      { name: 'editBatch', type: 'boolean', default: 'true', defaultEn: 'true', description: '允许批量提交。', descriptionEn: 'Allows a batch commit.' },
      { name: 'summaryMode', type: "'client' | 'server'", default: "'client'", defaultEn: "'client'", description: '合计在本地算，或直接展示 summaryData。', descriptionEn: 'Summarize locally, or show summaryData as-is.' },
      { name: 'summaryData', type: 'RsTableSummaryData | null', description: '服务端合计。', descriptionEn: 'Server summary.' },
      { name: 'showSummary', type: 'boolean', default: 'false', defaultEn: 'false', description: '显示合计行。列上有 summary 时也会出现。', descriptionEn: 'Shows the summary row. A column summary also shows it.' },
      { name: 'features', type: 'RsTableFeature<T>[]', description: '实例扩展。不要在业务里重写引擎。', descriptionEn: 'Instance features. Do not reimplement the engine in an app.' },
      { name: 'viewKey', type: 'string | number', description: '视图切换时重置滚动。', descriptionEn: 'Resets scroll when the view identity changes.' },
      { name: 'layoutActive', type: 'boolean', description: '为 false 时先记住滚动，再激活时写回。给 keep-alive。', descriptionEn: 'When false, scroll is remembered and restored when active again. For keep-alive.' },
      { name: 'ariaLabel', type: 'string', description: '网格名称。未传走 table.a11yLabel。', descriptionEn: 'Accessible name. Falls back to table.a11yLabel.' },
    ],
    events: [
      { name: 'row-click', type: '(row, index)', description: '点击行。', descriptionEn: 'A row was clicked.' },
      { name: 'row-dblclick', type: '(row, index)', description: '双击行。', descriptionEn: 'A row was double-clicked.' },
      { name: 'cell-view', type: '(row, column, index)', description: '查看单元格。', descriptionEn: 'A cell was viewed.' },
      { name: 'row-contextmenu', type: '(row, index, event)', description: '行上右键。', descriptionEn: 'Context menu on a row.' },
      { name: 'context-menu-select', type: '(key, row, selectedRows)', description: '选中右键项。', descriptionEn: 'A context menu item was chosen.' },
      { name: 'update:sort', type: 'RsTableSortState | null', description: '单列排序变化。', descriptionEn: 'Single-column sort changed.' },
      { name: 'update:sorts', type: 'RsTableSortState[]', description: '多列排序变化。', descriptionEn: 'Multi-sort changed.' },
      { name: 'sorts-change', type: 'RsTableSortState[]', description: '多列排序变化（同 update:sorts）。', descriptionEn: 'Multi-sort changed (same payload as update:sorts).' },
      { name: 'update:columnOrder', type: 'string[]', description: '列顺序变化。', descriptionEn: 'Column order changed.' },
      { name: 'column-order-change', type: 'string[]', description: '列顺序变化。', descriptionEn: 'Column order changed.' },
      { name: 'update:columnFilters', type: 'Record<string, string>', description: '列筛选变化。', descriptionEn: 'Column filters changed.' },
      { name: 'column-filters-change', type: 'Record<string, string>', description: '列筛选变化。', descriptionEn: 'Column filters changed.' },
      { name: 'row-drop', type: '(dragKeys, dropKey, position)', description: '行放下。组件不改 data。', descriptionEn: 'A row was dropped. The table does not mutate data.' },
      { name: 'row-drag-start', type: '(dragKeys, event)', description: '开始拖行。', descriptionEn: 'A row drag started.' },
      { name: 'update:selectedRowKeys', type: 'string[]', description: '选中键变化。', descriptionEn: 'Selected keys changed.' },
      { name: 'update:expandedRowKeys', type: 'string[]', description: '展开键变化。', descriptionEn: 'Expanded keys changed.' },
      { name: 'selection-change', type: 'string[]', description: '选中键变化。', descriptionEn: 'Selected keys changed.' },
      { name: 'expand-change', type: 'string[]', description: '展开键变化。', descriptionEn: 'Expanded keys changed.' },
      { name: 'load-more', type: '()', description: '接近底部且还有更多。', descriptionEn: 'Near the bottom while another page exists.' },
      { name: 'column-resize', type: '(key, width)', description: '列宽拖完。', descriptionEn: 'A column finished resizing.' },
      { name: 'update:highlightedRowKey', type: 'string | undefined', description: '高亮行变化。', descriptionEn: 'Highlighted row changed.' },
      { name: 'highlight-change', type: 'string | undefined', description: '高亮行变化。', descriptionEn: 'Highlighted row changed.' },
      { name: 'cell-edit-start', type: '(row, column, index)', description: '进入编辑。', descriptionEn: 'An edit started.' },
      { name: 'cell-edit-dialog', type: '(row, column, index, draft)', description: '需要弹出编辑。', descriptionEn: 'The cell wants a dialog editor.' },
      { name: 'cell-edit-commit', type: '(row, column, index, value, previous)', description: '单元格提交。宿主写回 data。', descriptionEn: 'A cell committed. The host writes data.' },
      { name: 'cell-edit-cancel', type: '(row, column, index)', description: '取消单元格编辑。', descriptionEn: 'A cell edit was cancelled.' },
      { name: 'cell-edit-invalid', type: '(row, column, index, message, value)', description: '校验失败。', descriptionEn: 'Validation failed.' },
      { name: 'cell-edit-batch-commit', type: '(column, changes)', description: '批量提交。', descriptionEn: 'A batch commit.' },
      { name: 'cell-edit-undo', type: '(entry)', description: '撤销。', descriptionEn: 'Undo.' },
      { name: 'cell-edit-redo', type: '(entry)', description: '重做。', descriptionEn: 'Redo.' },
      { name: 'cell-edit-reject', type: '(row, index, reason?)', description: '拒绝这一行的编辑。', descriptionEn: 'The row edit was rejected.' },
      { name: 'row-edit-commit', type: '(row, index, changes)', description: '整行确认。', descriptionEn: 'The row was confirmed.' },
      { name: 'row-edit-rollback', type: '(row, index)', description: '整行撤销。', descriptionEn: 'The row was reverted.' },
    ],
    slots: [
      { name: 'empty', type: '—', description: '没有行时替换 table.empty。', descriptionEn: 'Replaces table.empty when there are no rows.' },
      { name: 'summary', type: '—', description: '自定义合计行，盖过内置合计。', descriptionEn: 'Custom summary row. Replaces the built-in summary.' },
      { name: 'group', type: '{ key, label }', description: '分组行。', descriptionEn: 'Group row.' },
      { name: 'expand', type: '{ row, index }', description: '明细展开内容。', descriptionEn: 'Detail expansion.' },
      { name: '[columnKey]', type: '{ row, column, index }', description: '单元格。插槽名是列 key。', descriptionEn: 'Cell. The slot name is the column key.' },
      { name: 'header-[columnKey]', type: '{ column }', description: '列头。', descriptionEn: 'Column header.' },
      { name: 'edit-[columnKey]', type: '{ row, column, index, draft, error, update, commit, cancel }', description: '自定义编辑器。', descriptionEn: 'Custom editor.' },
    ],
    methods: [
      { name: 'apiVersion', type: 'string', description: '表格 API 契约版本，当前 1.0.0。', descriptionEn: 'Table API contract version. Currently 1.0.0.' },
      { name: 'getRowByKey', type: '(rowKey: string) => T | undefined', description: '按 key 取行。没有则 undefined。', descriptionEn: 'Row by key. undefined when missing.' },
      { name: 'getRowByIndex', type: '(index: number) => T | undefined', description: '按视图序号取行。', descriptionEn: 'Row by view index.' },
      { name: 'getColumnValues', type: '(colKey: string) => unknown[]', description: '当前视图该列的值。', descriptionEn: 'Values of that column in the current view.' },
      { name: 'getCellValue', type: '(rowKey: string, colKey: string) => unknown', description: '一个格子的值。', descriptionEn: 'One cell value.' },
      { name: 'getViewRows', type: '() => T[]', description: '筛选和排序后的业务行，不含分组伪行。', descriptionEn: 'Business rows after filter and sort, without group placeholders.' },
      { name: 'getSelectedRows', type: '() => T[]', description: '当前选中行。', descriptionEn: 'Currently selected rows.' },
      { name: 'getSelectedRowKeys', type: '() => string[]', description: '当前选中键的副本。', descriptionEn: 'A copy of the selected keys.' },
      { name: 'getAnalyticsSnapshot', type: '() => RsTableAnalyticsSnapshot<T>', description: '给图表用的当前快照。', descriptionEn: 'Current snapshot for a chart.' },
      { name: 'subscribeAnalytics', type: '(listener) => () => void', description: '订阅快照。返回的函数必须调用，否则监听留到表格卸载。', descriptionEn: 'Subscribes to snapshots. Call the returned function or the listener stays until the table unmounts.' },
      { name: 'getHighlightedRowKey', type: '() => string | undefined', description: '当前高亮行。', descriptionEn: 'Current highlighted row.' },
      { name: 'setHighlightedRowKey', type: '(key: string | undefined) => void', description: '设置高亮行。', descriptionEn: 'Sets the highlighted row.' },
      { name: 'cancelCellEdit', type: '() => void', description: '取消当前格编辑。', descriptionEn: 'Cancels the active cell edit.' },
      { name: 'cancelAllEdits', type: '() => void', description: '取消全部编辑。', descriptionEn: 'Cancels every edit.' },
      { name: 'getDirtyCellKeys', type: '() => string[]', description: '未提交的格子。', descriptionEn: 'Cells that are still dirty.' },
      { name: 'getCellError', type: '(rowKey, colKey) => string | undefined', description: '格子错误。没有则 undefined。', descriptionEn: 'Cell error. undefined when there is none.' },
      { name: 'setCellError', type: '(rowKey, colKey, message: string | null) => void', description: '写入或清掉格子错误。', descriptionEn: 'Sets or clears a cell error.' },
      { name: 'stageCell', type: '(cell: RsTableStagedCell) => void', description: '把一个格子放进草稿。', descriptionEn: 'Stages one cell.' },
      { name: 'rejectRowEdit', type: '(rowKey: string, reason?: string) => void', description: '拒绝这一行。', descriptionEn: 'Rejects that row.' },
      { name: 'undoEdit', type: '() => void', description: '撤销一步。', descriptionEn: 'Undoes one edit.' },
      { name: 'redoEdit', type: '() => void', description: '重做一步。', descriptionEn: 'Redoes one edit.' },
      { name: 'commitRowEdits', type: '(rowKey: string) => void', description: '提交这一行草稿。', descriptionEn: 'Commits that row’s draft.' },
      { name: 'rollbackRowEdits', type: '(rowKey: string) => void', description: '撤销这一行草稿。', descriptionEn: 'Reverts that row’s draft.' },
      { name: 'getActiveFeatureIds', type: '() => string[]', description: '当前挂上的 feature id。', descriptionEn: 'Ids of the features that are mounted.' },
      { name: 'getToolbarItems', type: '() => RsTableToolbarItem[]', description: 'feature 贡献的工具条项。', descriptionEn: 'Toolbar items contributed by features.' },
      { name: 'getOverlayContributions', type: '() => RsTableOverlayContribution[]', description: 'feature 贡献的浮层描述。', descriptionEn: 'Overlay descriptions contributed by features.' },
    ],
    tokens: [
      { name: '--rs-table-bg', default: 'var(--rs-surface)', description: '表体背景。跟表面色。', descriptionEn: 'Body background. Follows the surface.' },
      { name: '--rs-table-fg', default: 'var(--rs-text-primary)', description: '正文。', descriptionEn: 'Body text.' },
      { name: '--rs-table-header-fg', default: 'var(--rs-text-primary)', description: '表头文字。', descriptionEn: 'Header text.' },
      { name: '--rs-table-border', default: 'var(--rs-border)', description: '外边框。', descriptionEn: 'Outer border.' },
      { name: '--rs-table-row-hover', default: 'var(--rs-item-hover)', description: '行悬停。', descriptionEn: 'Row hover.' },
      { name: '--rs-table-row-selected', default: 'color-mix(primary, body)', description: '选中行。', descriptionEn: 'Selected row.' },
      { name: '--rs-table-row-stripe', default: 'color-mix(text, surface)', description: '斑马纹。', descriptionEn: 'Zebra stripe.' },
      { name: '--rs-table-sort-active-fg', default: 'var(--rs-primary)', description: '当前排序图标。', descriptionEn: 'Active sort icon.' },
      { name: '--rs-table-drop-indicator', default: 'var(--rs-primary)', description: '拖拽插入线。', descriptionEn: 'Drag insertion line.' },
      { name: '--rs-table-resize-handle', default: 'var(--rs-text-tertiary)', description: '列宽手柄。', descriptionEn: 'Column resize handle.' },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是 role=grid，右键是本库菜单。业务与文档站不要 import reka-ui。data、排序、选择、虚拟滚动和编辑语义与原来相同。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is role=grid and the menu is this library’s. Apps and the docs site must not import reka-ui. data, sort, selection, virtual scroll, and edit behave as before.',
      },
      {
        q: '和原生 table、Tree、专用网格怎么选？',
        a: '十来行静态表用原生 table。只有层级用 Tree。要列对齐、排序、编辑和虚拟滚动用本组件。公式或百万格用专用网格。',
        qEn: 'How do I choose among a native table, Tree, and a dedicated grid?',
        aEn: 'Use a native table for a dozen static rows. Use Tree for hierarchy alone. Use this component for columns, sort, edit, and virtual scroll. Use a dedicated grid for formulas or millions of cells.',
      },
      {
        q: '排序为什么不按我的语言排？',
        a: '默认字符串比较跟 RsConfigProvider 的 locale。列上的 sorter 由你自己比较，组件不会再套一层 locale。',
        qEn: 'Why does sort ignore my language?',
        aEn: 'The default string compare follows the RsConfigProvider locale. A column sorter is yours; the table does not wrap it.',
      },
      {
        q: '拖完行数据为什么没变？',
        a: 'row-drop 只报告 dragKeys、dropKey 和 position。宿主改 data。',
        qEn: 'Why did the rows not move after a drop?',
        aEn: 'row-drop only reports dragKeys, dropKey, and position. The host updates data.',
      },
    ],
    related: ['table-cell-edit', 'table-row-commit', 'table-row-select', 'table-tree', 'pagination', 'virtual-list'],
  },
  {
    slug: 'table-cell-edit',
    name: 'RsTable',
    title: 'Table',
    titleZh: '单元格编辑',
    group: 'data',
    summary: '表格内就地编辑单元格。',
    description: '表级 editable 加上列 editable。默认双击进入，失焦或回车发 cell-edit-commit。宿主把值写回 data。整行确认见行提交。完整契约在表格页。',
    descriptionEn: 'Turn on editable on the table and on the column. Double-click opens the editor. Blur or Enter emits cell-edit-commit. The host writes the value back onto data. A whole-row confirm is the row-commit page. The full contract is on the table page.',
    whenToUse: ['少量字段要在格子里改完就提交。', '改完要先看一整行再落库时，用行提交。'],
    whenToUseEn: ['Commit a few fields as soon as the cell closes.', 'Use row commit when several columns must be reviewed before they are saved.'],
    demos: [
      { id: 'demo-basic', title: '单元格即时提交', titleEn: 'Commit a cell' },
      { id: 'demo-click', title: '单击进入', titleEn: 'Edit on click' },
      { id: 'demo-invalid', title: '校验失败', titleEn: 'Validation' },
      { id: 'demo-select', title: '下拉选项', titleEn: 'Select' },
      { id: 'demo-editor', title: '自己的编辑器', titleEn: 'Custom editor' },
    ],
    props: [
      { name: 'editable', type: 'boolean', default: 'false', defaultEn: 'false', description: '打开表级编辑。', descriptionEn: 'Turns on table editing.' },
      { name: 'columns[].editable', type: 'boolean', description: '这一列可编辑。', descriptionEn: 'This column is editable.' },
      { name: 'editTrigger', type: "'click' | 'dblclick'", default: "'dblclick'", defaultEn: "'dblclick'", description: '进入编辑的指针。列上的值优先于表级。', descriptionEn: 'Pointer that starts an edit. A column value wins over the table.' },
      { name: 'columns[].valueType', type: "'text' | 'number' | 'date' | 'datetime' | 'boolean' | 'select' | 'textarea'", description: '内置编辑器。select 的选项在 editorOptions.options。', descriptionEn: 'Built-in editor. Select choices live in editorOptions.options.' },
      { name: 'columns[].validator', type: '(value, row, index) => string | null | Promise<…>', description: '返回字符串则拒绝提交，并发 cell-edit-invalid。', descriptionEn: 'A string rejects the commit and emits cell-edit-invalid.' },
    ],
    events: [
      { name: 'cell-edit-commit', type: '(row, column, index, value, previous)', description: '提交。宿主写回 data。', descriptionEn: 'Committed. The host writes data.' },
      { name: 'cell-edit-cancel', type: '(row, column, index)', description: '取消。', descriptionEn: 'Cancelled.' },
      { name: 'cell-edit-invalid', type: '(row, column, index, message, value)', description: '校验失败。', descriptionEn: 'Validation failed.' },
    ],
    slots: [{ name: 'edit-[columnKey]', type: '{ draft, update, commit, cancel }', description: '自定义编辑器。', descriptionEn: 'Custom editor.' }],
    methods: [{ name: 'cancelCellEdit', type: '() => void', description: '取消当前格。其余方法见表格页。', descriptionEn: 'Cancels the active cell. The rest of the API is on the table page.' }],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。编辑器是本库 Input / Select / DatePicker。', qEn: 'Do I still need reka-ui?', aEn: 'No. The editor is this library’s Input, Select, or DatePicker.' },
    ],
    related: ['table', 'table-row-commit'],
  },
  {
    slug: 'table-row-commit',
    name: 'RsTable',
    title: 'Table',
    titleZh: '行提交',
    group: 'data',
    summary: '行级编辑，确认后一次提交。',
    description: 'row-commit 把改动留在行草稿。行首确认后才发 row-edit-commit，撤销发 row-edit-rollback。没有 rowEdit 这个 prop。完整契约在表格页。',
    descriptionEn: 'row-commit keeps edits in a row draft. Confirm emits row-edit-commit. Revert emits row-edit-rollback. There is no rowEdit prop. The full contract is on the table page.',
    whenToUse: ['多列改完要一次落库。', '格子改完就要生效时，用单元格编辑。'],
    whenToUseEn: ['Save several columns in one commit.', 'Use cell edit when a cell should apply as soon as it closes.'],
    demos: [{ id: 'demo-basic', title: '整行确认', titleEn: 'Commit a row' }],
    props: [
      { name: 'editable', type: 'boolean', default: 'false', defaultEn: 'false', description: '打开编辑。', descriptionEn: 'Turns on editing.' },
      { name: 'rowCommit', type: 'boolean', default: 'false', defaultEn: 'false', description: '确认后才提交整行。', descriptionEn: 'Commit the row only after confirm.' },
    ],
    events: [
      { name: 'row-edit-commit', type: '(row, index, changes)', description: '确认。宿主写回 data。', descriptionEn: 'Confirmed. The host writes data.' },
      { name: 'row-edit-rollback', type: '(row, index)', description: '撤销这一行草稿。', descriptionEn: 'The row draft was reverted.' },
    ],
    methods: [
      { name: 'commitRowEdits', type: '(rowKey: string) => void', description: '代码里提交这一行。', descriptionEn: 'Commits that row from code.' },
      { name: 'rollbackRowEdits', type: '(rowKey: string) => void', description: '代码里撤销这一行。', descriptionEn: 'Reverts that row from code.' },
    ],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。确认和撤销是本库按钮。', qEn: 'Do I still need reka-ui?', aEn: 'No. Confirm and revert are this library’s buttons.' },
    ],
    related: ['table', 'table-cell-edit'],
  },
  {
    slug: 'table-row-select',
    name: 'RsTable',
    title: 'Table',
    titleZh: '行多选',
    group: 'data',
    summary: '不占勾选列的行选择。',
    description: 'selectable 加 selection-type="row"。单击替换，Ctrl 或 ⌘ 追加，Shift 范围选。没有 rowSelect 这个 prop。要勾选列用表格页的 checkbox。',
    descriptionEn: 'selectable plus selection-type="row". Click replaces, Ctrl or Command adds, Shift selects a range. There is no rowSelect prop. Use checkbox on the table page when you want a check column.',
    whenToUse: ['密度高，不想再占一列勾选框。', '要全选框时用 selection-type="checkbox"。'],
    whenToUseEn: ['The list is dense and a checkbox column is not wanted.', 'Use selection-type="checkbox" when you need a select-all box.'],
    demos: [
      { id: 'demo-basic', title: '点击行多选', titleEn: 'Select by clicking the row' },
      { id: 'demo-locked', title: '有的行不能点选', titleEn: 'Some rows cannot be selected' },
    ],
    props: [
      { name: 'selectable', type: 'boolean', default: 'false', defaultEn: 'false', description: '允许选择。', descriptionEn: 'Enables selection.' },
      { name: 'selectionType', type: "'row'", default: "'checkbox'", defaultEn: "'checkbox'", description: '设为 row 时不渲染勾选列。', descriptionEn: 'row does not render a checkbox column.' },
      { name: 'v-model:selected-row-keys', type: 'string[]', description: '受控选中键。', descriptionEn: 'Controlled selected keys.' },
      { name: 'rowSelectable', type: '(row, index) => boolean', description: '返回 false 时单击、Ctrl 和 Shift 都跳过这一行。', descriptionEn: 'Returning false skips that row for click, Ctrl, and Shift.' },
    ],
    events: [
      { name: 'update:selectedRowKeys', type: 'string[]', description: '选中键变化。', descriptionEn: 'Selected keys changed.' },
      { name: 'selection-change', type: 'string[]', description: '选中键变化。', descriptionEn: 'Selected keys changed.' },
    ],
    methods: [{ name: 'getSelectedRowKeys', type: '() => string[]', description: '当前选中键。', descriptionEn: 'Current selected keys.' }],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。选择是表格自己的键盘和指针。', qEn: 'Do I still need reka-ui?', aEn: 'No. Selection is the table’s own pointer and keyboard.' },
    ],
    related: ['table', 'checkbox'],
  },
  {
    slug: 'table-tree',
    name: 'RsTable',
    title: 'Table',
    titleZh: '树列表',
    group: 'data',
    summary: '带列的树：缩进、过滤与懒加载。',
    description: 'tree-config 做层级缩进。没有 tree 布尔开关。它不是 #expand 明细行，也和 group-by 互斥。纯导航用 RsTree。',
    descriptionEn: 'tree-config indents a hierarchy. There is no boolean tree prop. It is not the #expand detail row, and it does not combine with group-by. Use RsTree when there are no columns.',
    whenToUse: ['每个节点有多列属性，例如库、表、人数。', '节点只是名称和图标时用 Tree。'],
    whenToUseEn: ['Each node has several columns, such as schema, table, and headcount.', 'Use Tree when a node is only a label and an icon.'],
    demos: [
      { id: 'demo-basic', title: '树表', titleEn: 'Tree table' },
      { id: 'demo-filter', title: '过滤', titleEn: 'Filter' },
      { id: 'demo-lazy', title: '懒加载', titleEn: 'Lazy load' },
      { id: 'demo-check', title: '父子一起勾', titleEn: 'Check with children' },
    ],
    props: [
      { name: 'treeConfig', type: 'RsTableTreeConfig<T>', description: 'children 字段、缩进列、懒加载。', descriptionEn: 'Children field, indent column, and lazy load.' },
      { name: 'treeConfig.lazy', type: 'boolean', description: '没有子节点时仍显示展开箭头，首次展开调用 loadData。', descriptionEn: 'Shows an expander when there are no children yet. The first expand calls loadData.' },
      { name: 'treeConfig.loadData', type: '(row, key) => void | T[] | Promise<…>', description: '可改 row[childrenField]，或返回子节点数组由表格写入。', descriptionEn: 'Mutate row[childrenField], or return a children array for the table to write.' },
      { name: 'treeConfig.checkStrictly', type: 'boolean', default: 'true', defaultEn: 'true', description: 'false 时勾选父节点带上已加载的子节点。', descriptionEn: 'false checks loaded children together with the parent.' },
      { name: 'filterText', type: 'string', description: '跨列包含筛选。匹配节点会留下祖先。', descriptionEn: 'Cross-column includes filter. A match keeps its ancestors.' },
      { name: 'v-model:expanded-row-keys', type: 'string[]', description: '受控展开键。', descriptionEn: 'Controlled expanded keys.' },
    ],
    events: [{ name: 'update:expandedRowKeys', type: 'string[]', description: '展开键变化。', descriptionEn: 'Expanded keys changed.' }],
    methods: [{ name: 'getRowByKey', type: '(rowKey: string) => T | undefined', description: '按 key 取节点。', descriptionEn: 'Node by key.' }],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。展开是原生 button，缩进用 padding-inline-start。', qEn: 'Do I still need reka-ui?', aEn: 'No. The expander is a native button and the indent is padding-inline-start.' },
      { q: '和 Tree 怎么选？', a: '要列就用树表。只要层级就用 RsTree。', qEn: 'How do I choose between this and Tree?', aEn: 'Use the tree table when you need columns. Use RsTree for hierarchy alone.' },
    ],
    related: ['table', 'tree'],
  },
  {
    slug: 'tree',
    name: 'RsTree',
    title: 'Tree',
    titleZh: '树',
    group: 'data',
    summary: '层级数据：勾选、拖拽、过滤与虚拟。',
    description:
      '文件树、对象树、权限树。根是原生 role=tree，不包 Reka。选中走 v-model，展开和勾选各自有 v-model。表单里选节点用 TreeSelect；要列对齐用树表。',
    descriptionEn:
      'File trees, object trees, and permission trees. The root is a native role=tree — no Reka. Selection is v-model; expansion and checks have their own v-models. Use TreeSelect inside a form. Use a tree table when nodes need columns.',
    whenToUse: [
      '主导航或资源树，节点主要是名称和图标。',
      '要勾选子树、拖拽换位、过滤或懒加载。',
      '上千个可见节点时打开 virtual，或让可见数超过 virtualThreshold 自动虚拟化。',
      '下拉里选节点用 TreeSelect。每节点多列属性用树表。',
    ],
    whenToUseEn: [
      'Primary navigation or a resource tree where each node is a label and an icon.',
      'Check a subtree, drag to reorder, filter, or lazy-load.',
      'Turn on virtual for thousands of visible nodes, or let the list virtualize once it passes virtualThreshold.',
      'Use TreeSelect to pick a node in a dropdown. Use a tree table when each node has columns.',
    ],
    demos: [
      { id: 'demo-basic', title: '选中', titleEn: 'Selection' },
      { id: 'demo-multiple', title: '多选', titleEn: 'Multiple' },
      { id: 'demo-check', title: '勾选', titleEn: 'Check' },
      { id: 'demo-strict', title: '父子不关联', titleEn: 'Independent check' },
      { id: 'demo-leaf', title: '只勾叶子', titleEn: 'Leaves only' },
      { id: 'demo-check-click', title: '点行勾选', titleEn: 'Check on row click' },
      { id: 'demo-node-disabled', title: '禁用节点', titleEn: 'Disabled nodes' },
      { id: 'demo-filter', title: '过滤', titleEn: 'Filter' },
      { id: 'demo-fields', title: '字段映射', titleEn: 'Field names' },
      { id: 'demo-drag', title: '拖拽', titleEn: 'Drag' },
      { id: 'demo-accordion', title: '手风琴', titleEn: 'Accordion' },
      { id: 'demo-block', title: '整行展开', titleEn: 'Click row to expand' },
      { id: 'demo-lazy', title: '懒加载', titleEn: 'Lazy load' },
      { id: 'demo-virtual', title: '虚拟滚动', titleEn: 'Virtual scroll' },
      { id: 'demo-size', title: '尺寸', titleEn: 'Size' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-disabled', title: '整树禁用', titleEn: 'Disabled tree' },
      { id: 'demo-keyboard', title: '键盘', titleEn: 'Keyboard' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
      { id: 'demo-theme', title: '主题与方向', titleEn: 'Theme and direction' },
    ],
    props: [
      { name: 'v-model', type: 'string | string[]', default: "''", defaultEn: "''", description: '选中的 key。multiple 时为数组。', descriptionEn: 'Selected key. An array when multiple is set.' },
      { name: 'v-model:expanded-keys', type: 'string[]', description: '受控展开键。不传则组件内部维护，可用 defaultExpandedKeys 给初值。', descriptionEn: 'Controlled expanded keys. Omit it to keep state inside the tree; seed it with defaultExpandedKeys.' },
      { name: 'v-model:checked-keys', type: 'string[]', description: '受控勾选键。不传则用 defaultCheckedKeys。', descriptionEn: 'Controlled checked keys. Omit it to use defaultCheckedKeys.' },
      { name: 'v-model:half-checked-keys', type: 'string[]', description: '半选键，由组件写入。级联勾选时父节点会半选。', descriptionEn: 'Half-checked keys, written by the tree. A parent is half-checked when cascade checking is partial.' },
      { name: 'nodes', type: 'RsTreeNode[]', description: '节点。key / label / children 可用 fieldNames 改名。', descriptionEn: 'Nodes. Rename key / label / children with fieldNames.' },
      { name: 'fieldNames', type: 'RsTreeFieldNames', description: '把 key、label、children、disabled、isLeaf、icon、disableCheckbox、loading 映射到数据字段。', descriptionEn: 'Maps key, label, children, disabled, isLeaf, icon, disableCheckbox, and loading onto data fields.' },
      { name: 'size', type: "'ssm' | 'sm' | 'md' | 'lg'", description: '行高与缩进。未传跟 Form，再跟 ConfigProvider，否则 md。', descriptionEn: 'Row height and indent. Falls through Form, then ConfigProvider, otherwise md.' },
      { name: 'id', type: 'string', description: '根元素 id。缺省时自动生成，子项 id 由它派生。', descriptionEn: 'Root id. Generated when omitted; item ids are derived from it.' },
      { name: 'ariaLabel', type: 'string', description: '树的名称。未传走 tree.label。', descriptionEn: 'Accessible name. Falls back to tree.label.' },
      { name: 'disabled', type: 'boolean', default: 'false', defaultEn: 'false', description: '整棵树不可选、不可勾、不可拖。也会跟随 Form.disabled。', descriptionEn: 'The whole tree cannot select, check, or drag. Also follows Form.disabled.' },
      { name: 'multiple', type: 'boolean', default: 'false', defaultEn: 'false', description: '多选。v-model 变为 string[]。', descriptionEn: 'Multi-select. v-model becomes string[].' },
      { name: 'selectable', type: 'boolean', default: 'true', defaultEn: 'true', description: '点击是否写入 v-model。', descriptionEn: 'Whether a click writes v-model.' },
      { name: 'checkable', type: 'boolean', default: 'false', defaultEn: 'false', description: '显示勾选框。', descriptionEn: 'Shows checkboxes.' },
      { name: 'checkStrictly', type: 'boolean', default: 'false', defaultEn: 'false', description: '勾选父子不关联。', descriptionEn: 'Checking a node does not affect its parent or children.' },
      { name: 'onlyCheckLeaf', type: 'boolean', default: 'false', defaultEn: 'false', description: '只显示并勾选叶子。', descriptionEn: 'Only leaves show a checkbox and can be checked.' },
      { name: 'checkOnClickNode', type: 'boolean', default: 'false', defaultEn: 'false', description: '点击节点行也切换勾选。', descriptionEn: 'Clicking the row also toggles the checkbox.' },
      { name: 'defaultExpandAll', type: 'boolean', default: 'false', defaultEn: 'false', description: '初次展开所有已有子节点的项。', descriptionEn: 'Expands every node that already has children on first render.' },
      { name: 'defaultExpandedKeys', type: 'string[]', default: '[]', defaultEn: '[]', description: '非受控时的初始展开键。', descriptionEn: 'Initial expanded keys when expanded keys are not controlled.' },
      { name: 'defaultCheckedKeys', type: 'string[]', default: '[]', defaultEn: '[]', description: '非受控时的初始勾选键。', descriptionEn: 'Initial checked keys when checked keys are not controlled.' },
      { name: 'expandOnClickNode', type: 'boolean', default: 'false', defaultEn: 'false', description: '点击节点时展开或收起，而不只点箭头。', descriptionEn: 'Clicking the node expands or collapses it, not only the arrow.' },
      { name: 'blockNode', type: 'boolean', default: 'false', defaultEn: 'false', description: '整行可点。标签不再是独立按钮。', descriptionEn: 'The whole row is the click target. The label is not its own button.' },
      { name: 'showLine', type: 'boolean', default: 'false', defaultEn: 'false', description: '画出层级引导线。', descriptionEn: 'Draws indent guides.' },
      { name: 'accordion', type: 'boolean', default: 'false', defaultEn: 'false', description: '同一层只展开一个节点。', descriptionEn: 'Only one sibling stays expanded.' },
      { name: 'filter', type: 'string', default: "''", defaultEn: "''", description: '过滤关键字。匹配节点及其祖先会留下。', descriptionEn: 'Filter keyword. Matches and their ancestors stay.' },
      { name: 'filterNode', type: '(node: RsTreeNode, keyword: string) => boolean', description: '自定义是否匹配。默认按标签做不区分大小写的包含（toLocaleLowerCase）。', descriptionEn: 'Custom match. The default is a case-insensitive includes on the label (toLocaleLowerCase).' },
      { name: 'highlight', type: 'boolean', default: 'true', defaultEn: 'true', description: '过滤时高亮标签中的匹配片段。', descriptionEn: 'Highlights the matched slice of the label while filtering.' },
      { name: 'autoExpandParent', type: 'boolean', default: 'true', defaultEn: 'true', description: '过滤时展开匹配路径，清空过滤后还原之前的展开。', descriptionEn: 'Expands match paths while filtering, then restores the previous expansion when the query is cleared.' },
      { name: 'lazy', type: 'boolean', default: 'false', defaultEn: 'false', description: '没有子节点且不是叶子时仍显示展开箭头。', descriptionEn: 'Shows an expander when a node has no children yet and is not a leaf.' },
      { name: 'loadData', type: '(node: RsTreeNode, key: string) => void | Promise<void>', description: '首次展开空枝时调用。宿主应把子节点写回 nodes。组件卸载后不再改展开状态。', descriptionEn: 'Called the first time an empty branch expands. The host writes children back onto nodes. After unmount the tree does not change expansion.' },
      { name: 'draggable', type: 'boolean', default: 'false', defaultEn: 'false', description: '允许拖拽。落下位置由 node-drop 交给宿主改数据。', descriptionEn: 'Allows dragging. node-drop tells the host where to move the node; the tree does not mutate nodes.' },
      { name: 'dragTrigger', type: "'handle' | 'row'", default: "'handle'", defaultEn: "'handle'", description: 'handle 显示拖拽手柄；row 整行可拖且不显示手柄。', descriptionEn: 'handle shows a grip. row drags from the whole row and hides the grip.' },
      { name: 'allowDrop', type: '(dragKey: string, dropKey: string, position: RsTreeDropPosition) => boolean', description: '是否允许落到该位置。拖进自己的子孙一律拒绝。', descriptionEn: 'Whether this drop is allowed. Dropping a node into its own descendant is always rejected.' },
      { name: 'virtual', type: 'boolean', default: 'false', defaultEn: 'false', description: '强制虚拟滚动。未传时，可见节点数超过 virtualThreshold 也会打开。开发环境下一旦开启，控制台打一行节点数和视口高度。', descriptionEn: 'Forces virtual scrolling. Without it, the tree still virtualizes once visible nodes pass virtualThreshold. In development, turning it on prints the node count and viewport height.' },
      { name: 'virtualThreshold', type: 'number', default: '100', defaultEn: '100', description: '未强制 virtual 时，可见节点超过该数才虚拟化。', descriptionEn: 'When virtual is not forced, virtualize after this many visible nodes.' },
      { name: 'height', type: 'number | string', description: '视口高度。数字按 px。0 或百分比在 virtual 时测量父级。', descriptionEn: 'Viewport height. A number is px. 0 or a percentage is measured from the parent when virtual.' },
      { name: 'itemHeight', type: 'number', description: '行高像素。未传跟 size。', descriptionEn: 'Row height in pixels. Follows size when omitted.' },
      { name: 'overscan', type: 'number', default: '4', defaultEn: '4', description: '虚拟窗口两侧多渲染的行数。', descriptionEn: 'Extra rows rendered on each side of the virtual window.' },
    ],
    events: [
      { name: 'update:modelValue', type: 'string | string[]', description: '选中变化。对应 v-model。', descriptionEn: 'Selection changed. This is v-model.' },
      { name: 'update:expandedKeys', type: 'string[]', description: '展开键变化。', descriptionEn: 'Expanded keys changed.' },
      { name: 'update:checkedKeys', type: 'string[]', description: '勾选键变化。', descriptionEn: 'Checked keys changed.' },
      { name: 'update:halfCheckedKeys', type: 'string[]', description: '半选键变化。', descriptionEn: 'Half-checked keys changed.' },
      { name: 'node-click', type: '(node: RsTreeNode, key: string)', description: '点击节点。禁用整树时不发。', descriptionEn: 'A node was clicked. Not emitted when the tree is disabled.' },
      { name: 'node-dblclick', type: '(node: RsTreeNode, key: string)', description: '双击节点。点在箭头、勾选框或拖拽手柄上不发。', descriptionEn: 'A node was double-clicked. Clicks on the arrow, checkbox, or grip do not emit.' },
      { name: 'node-contextmenu', type: '(node: RsTreeNode, key: string, event: MouseEvent)', description: '在节点上右键。事件继续冒泡，宿主可自己 preventDefault。行上有 data-tree-key。', descriptionEn: 'Context menu on a node. The event keeps bubbling; the host may preventDefault. The row has data-tree-key.' },
      { name: 'expand', type: '(key: string, expanded: boolean)', description: '单个节点展开或收起。', descriptionEn: 'One node expanded or collapsed.' },
      { name: 'check', type: '(keys: string[], halfCheckedKeys: string[], node: RsTreeNode, key: string)', description: '勾选变化。keys 是新的勾选集合。', descriptionEn: 'Check changed. keys is the next checked set.' },
      { name: 'node-drop', type: '(dragKey: string, dropKey: string, position: RsTreeDropPosition)', description: '拖拽放下。position 为 before / inside / after。组件不改 nodes。', descriptionEn: 'A drag was dropped. position is before, inside, or after. The tree does not mutate nodes.' },
    ],
    slots: [
      { name: 'title', type: '{ node, key, label, expanded, selected, checkState, depth, focused }', description: '节点标题。默认是标签文本，过滤时带高亮。', descriptionEn: 'Node title. Defaults to the label, with a highlight while filtering.' },
      { name: 'icon', type: '{ node, key, expanded }', description: '节点图标。未提供时，节点有 icon 字段才渲染 RsIcon。', descriptionEn: 'Node icon. When omitted, an RsIcon renders only if the node has an icon field.' },
      { name: 'empty', type: '—', description: '没有可见节点时替换默认空态。', descriptionEn: 'Replaces the default empty state when nothing is visible.' },
    ],
    methods: [
      { name: 'expandAll', type: '() => void', description: '展开当前可见树里所有可展开节点。', descriptionEn: 'Expands every expandable node in the current visible tree.' },
      { name: 'collapseAll', type: '() => void', description: '收起全部。', descriptionEn: 'Collapses everything.' },
      { name: 'expandNode', type: '(key: string) => void', description: '展开一个节点。', descriptionEn: 'Expands one node.' },
      { name: 'collapseNode', type: '(key: string) => void', description: '收起一个节点。', descriptionEn: 'Collapses one node.' },
      { name: 'focusNode', type: '(key: string) => void', description: '把键盘焦点移到该节点并滚进视口。不自动展开祖先。', descriptionEn: 'Moves keyboard focus to that node and scrolls it into view. Does not expand ancestors.' },
      { name: 'focus', type: '() => void', description: '聚焦树根，使方向键可用。', descriptionEn: 'Focuses the tree root so arrow keys work.' },
      { name: 'scrollToKey', type: '(key: string) => void', description: '展开祖先、聚焦该节点并滚进视口。key 不存在则无操作。', descriptionEn: 'Expands ancestors, focuses the node, and scrolls it into view. No-op when the key is missing.' },
      { name: 'getSelectedKeys', type: '() => string[]', description: '当前选中键。单选时最多一个。', descriptionEn: 'Current selected keys. At most one in single select.' },
      { name: 'getCheckedKeys', type: '() => string[]', description: '当前勾选键。', descriptionEn: 'Current checked keys.' },
      { name: 'getExpandedKeys', type: '() => string[]', description: '当前展开键。', descriptionEn: 'Current expanded keys.' },
      { name: 'getHalfCheckedKeys', type: '() => string[]', description: '当前半选键。', descriptionEn: 'Current half-checked keys.' },
    ],
    tokens: [
      { name: '--rs-tree-line', default: 'color-mix(in srgb, var(--rs-text) 10–14%, transparent)', description: '层级引导线颜色。', descriptionEn: 'Indent guide color.' },
      { name: '--rs-tree-line-width', default: '1px', description: '引导线粗细。', descriptionEn: 'Guide thickness.' },
      { name: '--rs-tree-row-hover', default: 'var(--rs-item-hover)', description: '行悬停背景。', descriptionEn: 'Row hover background.' },
      { name: '--rs-tree-selected-bg', default: 'color-mix(in srgb, var(--rs-primary) 8–12%, var(--rs-surface))', description: '选中行背景。', descriptionEn: 'Selected row background.' },
      { name: '--rs-tree-selected-fg', default: 'var(--rs-text)', description: '选中行文字。', descriptionEn: 'Selected row text.' },
      { name: '--rs-tree-focused-bg', default: 'color-mix(in srgb, var(--rs-primary) 5–8%, var(--rs-surface))', description: '键盘焦点行背景。', descriptionEn: 'Keyboard-focus row background.' },
      { name: '--rs-tree-focused-ring', default: 'color-mix(in srgb, var(--rs-primary) 22–28%, transparent)', description: '键盘焦点描边。', descriptionEn: 'Keyboard-focus outline.' },
      { name: '--rs-tree-selected-focused-bg', default: 'color-mix(in srgb, var(--rs-primary) 10–16%, var(--rs-surface))', description: '选中且聚焦时的背景。', descriptionEn: 'Background when selected and focused.' },
      { name: '--rs-tree-selected-focused-ring', default: 'color-mix(in srgb, var(--rs-primary) 28–36%, transparent)', description: '选中且聚焦时的描边。', descriptionEn: 'Outline when selected and focused.' },
      { name: '--rs-tree-drop-indicator', default: 'var(--rs-primary)', description: '拖拽插入线。', descriptionEn: 'Drag insertion line.' },
      { name: '--rs-tree-drop-inside-bg', default: 'color-mix(in srgb, var(--rs-primary) 8%, transparent)', description: '拖入节点内部时的背景。', descriptionEn: 'Background when dropping inside a node.' },
      { name: '--rs-tree-highlight-bg', default: 'color-mix(in srgb, var(--rs-warning) 45%, transparent)', description: '过滤高亮背景。', descriptionEn: 'Filter highlight background.' },
      { name: '--rs-tree-check-fg', default: 'var(--rs-primary-foreground)', description: '勾选标记颜色。', descriptionEn: 'Check mark color.' },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 role=tree，行是 treeitem。业务与文档站不要 import reka-ui。v-model、展开、勾选、拖拽和虚拟滚动语义与原来相同。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is a native role=tree and each row is a treeitem. Apps and the docs site must not import reka-ui. v-model, expansion, checks, drag, and virtual scroll behave as before.',
      },
      {
        q: '和 TreeSelect、树表怎么选？',
        a: '树一直摊在页面上用 RsTree。在输入框里弹出再选，用 TreeSelect。节点还要显示多列属性，用表格的树模式。',
        qEn: 'How do I choose among Tree, TreeSelect, and a tree table?',
        aEn: 'Use RsTree when the tree stays on the page. Use TreeSelect when the user picks from a field. Use the table tree mode when each node has several columns.',
      },
      {
        q: '拖拽之后数据为什么没变？',
        a: 'node-drop 只报告 dragKey、dropKey 和 position。宿主改 nodes。组件不会替你重排。',
        qEn: 'Why did the data not change after a drop?',
        aEn: 'node-drop only reports dragKey, dropKey, and position. The host updates nodes. The tree does not reorder them.',
      },
      {
        q: '键盘怎么走？',
        a: '树是一个 Tab 停靠点。上下移动，向前展开或进入子节点，向后收起或回到父节点。书写方向为 rtl 时左右对调。输入字符会按标签前缀跳转，输入法组合期间不抢键。星号展开当前层已加载的兄弟。',
        qEn: 'How does the keyboard work?',
        aEn: 'The tree is one tab stop. Up and down move. Forward expands or enters a child; backward collapses or returns to the parent. Left and right swap in RTL. Typing jumps by label prefix, and IME composition is ignored. Asterisk expands loaded siblings at the current level.',
      },
    ],
    related: ['tree-select', 'table-tree', 'empty'],
  },
  {
    slug: 'virtual-list',
    name: 'RsVirtualList',
    title: 'VirtualList',
    titleZh: '虚拟列表',
    group: 'data',
    summary: '只渲染可视区的长列表。',
    description:
      '日志行、命令面板、消息流等一维长列表。根是原生 overflow，不包 Reka。定高、按索引变高，或先估算再量内容。二维数据用 Table 的虚拟模式。',
    descriptionEn:
      'One-dimensional lists: logs, command results, message streams. The root is native overflow — no Reka. Sizes can be fixed, a function of the index, or measured. Use Table virtual for two-dimensional data.',
    whenToUse: [
      '同一份数据有数千行，只滚动、不切页。',
      '行高固定，或能按索引算出来。内容高度未知时用 itemSize="auto"。',
      '要分页、跳转、每页条数用 Pagination。子节点不多、要画滚动条用 Scrollbar。表格行用 Table virtual。',
    ],
    whenToUseEn: [
      'One dataset with thousands of rows that scrolls and does not page.',
      'Row size is fixed, or a function of the index. Use itemSize="auto" when content height is unknown.',
      'Use Pagination to page. Use Scrollbar when every child should mount. Use Table virtual for grid rows.',
    ],
    demos: [
      { id: 'demo-basic', title: '定高', titleEn: 'Fixed size' },
      { id: 'demo-variable', title: '按索引变高', titleEn: 'Variable size' },
      { id: 'demo-active', title: '当前项', titleEn: 'Active row' },
      { id: 'demo-horizontal', title: '横向', titleEn: 'Horizontal' },
      { id: 'demo-auto', title: '测量高度', titleEn: 'Measured size' },
      { id: 'demo-empty', title: '空态', titleEn: 'Empty' },
      { id: 'demo-keyboard', title: '键盘', titleEn: 'Keyboard' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-infinite', title: '无限滚动', titleEn: 'Infinite scroll' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'items',
        type: 'T[]',
        description: '数据。空数组显示 #empty。',
        descriptionEn: 'Items. An empty array shows #empty.',
      },
      {
        name: 'itemSize',
        type: "number | ((index: number) => number) | 'auto'",
        default: '32',
        defaultEn: '32',
        description: '主轴尺寸（纵向是高，横向是宽）。函数按索引返回像素。auto 先用 estimateSize，再量可见项。',
        descriptionEn: 'Main-axis size (height when vertical, width when horizontal). A function returns pixels for that index. auto estimates, then measures visible items.',
      },
      {
        name: 'estimateSize',
        type: 'number',
        default: '32',
        defaultEn: '32',
        description: 'itemSize 为 auto 时，测量前的估算像素。',
        descriptionEn: 'Estimated pixels before measurement when itemSize is auto.',
      },
      {
        name: 'height',
        type: 'number | string',
        default: '240',
        defaultEn: '240',
        description: '交叉轴高度。数字按 px。0 或百分比由父级撑满，内部测量可视长度。',
        descriptionEn: 'Cross-axis height. A number is px. 0 or a percentage fills the parent; the viewport length is measured.',
      },
      {
        name: 'overscan',
        type: 'number',
        default: '4',
        defaultEn: '4',
        description: '可视区两侧多渲染的条数。',
        descriptionEn: 'Extra items rendered on each side of the viewport.',
      },
      {
        name: 'v-model:active-index',
        type: 'number | null',
        default: 'null',
        defaultEn: 'null',
        description: '当前项。变化后滚进视口，默认居中。',
        descriptionEn: 'Active index. Changes scroll it into view, centered by default.',
      },
      {
        name: 'layoutActive',
        type: 'boolean',
        description: 'keep-alive 外层变为可见时重测视口并读回滚动位置。',
        descriptionEn: 'When a keep-alive parent becomes visible, remeasure the viewport and read the scroll position back.',
      },
      {
        name: 'radius',
        type: "'none' | 'xs' | 'sm' | 'md' | 'lg' | 'full'",
        default: "'sm'",
        defaultEn: "'sm'",
        description: '外层圆角。直角传 none。',
        descriptionEn: 'Outer radius. Pass none for square corners.',
      },
      {
        name: 'orientation',
        type: "'vertical' | 'horizontal'",
        default: "'vertical'",
        defaultEn: "'vertical'",
        description: '滚动轴。横向时 itemSize 是宽。',
        descriptionEn: 'Scroll axis. When horizontal, itemSize is the width.',
      },
      {
        name: 'itemKey',
        type: '(item: T, index: number) => string | number',
        description: '稳定键。不传时用索引，滚动时复用同一批节点。',
        descriptionEn: 'Stable key. Defaults to the index so the same nodes are reused while scrolling.',
      },
      {
        name: 'keyboard',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '方向键 / Home / End 移动当前项。默认关，避免抢走外层键盘。打开后根是 listbox。',
        descriptionEn: 'Arrow keys / Home / End move the active item. Off by default so a parent can keep the keys. On makes the root a listbox.',
      },
      {
        name: 'bordered',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '外框。嵌进已有表面时关掉。',
        descriptionEn: 'Outer frame. Turn off when the list sits in an existing surface.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '可访问名称。keyboard 且未传时用 virtualList.label。',
        descriptionEn: 'Accessible name. When keyboard is on and this is omitted, virtualList.label is used.',
      },
      {
        name: 'id',
        type: 'string',
        description: '根节点 id。不传时自动生成，供 aria-activedescendant。',
        descriptionEn: 'Root id. Generated when omitted, for aria-activedescendant.',
      },
    ],
    events: [
      {
        name: 'scroll',
        type: '[event: Event]',
        description: '原生滚动。载荷是 Event，读 event.target 的 scrollTop / scrollLeft。',
        descriptionEn: 'Native scroll. The payload is the Event; read scrollTop / scrollLeft on event.target.',
      },
      {
        name: 'update:activeIndex',
        type: '[index: number | null]',
        description: 'v-model:active-index。点击或键盘改当前项时发出。',
        descriptionEn: 'v-model:active-index. Emitted when a click or key changes the active item.',
      },
      {
        name: 'change',
        type: '[index: number, item: T]',
        description: '点击一行，或键盘移到另一行。',
        descriptionEn: 'A row click, or a key that moves to another row.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '{ item: T, index: number }',
        description: '可见项。只渲染窗口，不要在外面再 v-for 全量数据。',
        descriptionEn: 'A visible item. Only the window is rendered; do not v-for the full list outside.',
      },
      {
        name: 'empty',
        type: '—',
        description: 'items 为空。不传时用 virtualList.empty。',
        descriptionEn: 'Shown when items is empty. Defaults to virtualList.empty.',
      },
    ],
    methods: [
      {
        name: 'scrollToIndex',
        type: "(index: number, align?: 'nearest' | 'center' | 'start' | 'end') => void",
        description: '宿主调用。把该项滚进视口。align 默认 center。越界无操作。',
        descriptionEn: 'Host call. Scroll that index into view. align defaults to center. Out of range does nothing.',
      },
      {
        name: 'scrollToOffset',
        type: '(offset: number) => void',
        description: '宿主调用。滚到内容偏移（像素，从起点算）。超长列表会映射到压缩后的滚动条。',
        descriptionEn: 'Host call. Scroll to a content offset in pixels from the start. Very long lists map onto the compressed scrollbar.',
      },
      {
        name: 'getScrollOffset',
        type: '() => number',
        description: '宿主调用。返回内容偏移。未挂载时按当前状态估算。',
        descriptionEn: 'Host call. Return the content offset. Before mount, estimate from current state.',
      },
      {
        name: 'getViewport',
        type: '() => HTMLElement | undefined',
        description: '宿主调用。返回滚动根节点。未挂载时为 undefined。',
        descriptionEn: 'Host call. Return the scroll root, or undefined before mount.',
      },
      {
        name: 'focus',
        type: '() => void',
        description: '宿主调用。聚焦滚动根。keyboard 为 true 时根在 Tab 序里。',
        descriptionEn: 'Host call. Focus the scroll root. The root is in tab order when keyboard is true.',
      },
    ],
    tokens: [
      {
        name: '--rs-virtual-list-border / --rs-virtual-list-bg / --rs-virtual-list-fg',
        default: 'theme',
        description: '边框、表面、文字。随 data-rs-theme。',
        descriptionEn: 'Border, surface, and text. Follow data-rs-theme.',
      },
      {
        name: '--rs-virtual-list-accent / --rs-virtual-list-accent-width / --rs-virtual-list-active-bg',
        default: 'primary / 0.125rem / mix',
        description: '当前项色条与底。色条在逻辑起点，RTL 跟书写方向。',
        descriptionEn: 'Active bar and fill. The bar sits on the logical start edge so RTL follows writing direction.',
      },
      {
        name: '--rs-virtual-list-radius',
        default: 'runtime',
        description: '由 radius 写入，对应 --rs-radius-*。',
        descriptionEn: 'Written from radius, mapped to --rs-radius-*.',
      },
      {
        name: '--rs-focus-ring-width / --rs-focus-border',
        default: 'theme',
        description: 'keyboard 时的焦点环。',
        descriptionEn: 'Focus ring when keyboard is on.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 overflow。业务与文档站不要 import reka-ui。滚动、窗口和 scrollToIndex 语义与原来相同。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is native overflow. Apps and the docs site must not import reka-ui. Scroll, the window, and scrollToIndex behave as before.',
      },
      {
        q: 'itemSize 函数为什么以前看起来没生效？',
        a: '现在按索引累加高度。函数请保持稳定引用，不要在模板里每次渲染新建，否则万行会反复重算。',
        qEn: 'Why did an itemSize function seem ignored?',
        aEn: 'Heights are now summed per index. Keep the function referentially stable. An inline template function rebuilds the table on every render.',
      },
      {
        q: '和 Scrollbar、Pagination、Table 怎么选？',
        a: '子节点都要挂上用 Scrollbar。切页用 Pagination。列对齐用 Table virtual。这里只做一维窗口。',
        qEn: 'When should I use Scrollbar, Pagination, or Table instead?',
        aEn: 'Use Scrollbar when every child should mount. Use Pagination to page. Use Table virtual for aligned columns. This component is a one-dimensional window.',
      },
      {
        q: '点击为什么会改当前项？日志键盘呢？',
        a: '点击发 change，并写 v-model:active-index。keyboard 默认 false，方向键留给外层（例如 RsLog）。',
        qEn: 'Why does a click change the active row? What about log keyboard?',
        aEn: 'A click emits change and writes v-model:active-index. keyboard defaults to false so arrow keys stay with the parent (for example RsLog).',
      },
      {
        q: '怎么做无限滚动？',
        a: '听 scroll。距底部小于约一屏时把下一页追加进 items，并用 loading 挡住重复请求。滚到底会继续触发，所以请求中和已到底都要直接返回。组件不内置分页或接口。',
        qEn: 'How do I infinite-scroll?',
        aEn: 'Listen to scroll. Append the next page to items when the end is about a screen away, and ignore further events while a request is in flight or the list is finished. The component does not page or fetch.',
      },
      {
        q: '上百万行会不会把滚动条撑爆？',
        a: '总高度超过 800 万像素时压缩滚动条，屏幕上的行仍是真实像素。scroll 的 Event 不变。卸载会取消动画帧、断开 ResizeObserver，并清掉「滚动中」定时器。',
        qEn: 'Will a million rows blow the scrollbar?',
        aEn: 'Past 8 million pixels the scrollbar is compressed; on-screen rows stay real pixels. The scroll Event is unchanged. Unmount cancels animation frames, disconnects ResizeObserver, and clears the scrolling timer.',
      },
    ],
    related: ['table', 'log', 'scrollbar', 'pagination'],
  },
  {
    slug: 'descriptions',
    name: 'RsDescriptions',
    title: 'Descriptions',
    titleZh: '描述列表',
    group: 'data',
    summary: '只读字段的键值栅格。',
    description:
      '详情页把只读属性排成标签与值。根内是原生 dl，条目是 dt / dd，不包 Reka。数据走 items，自定义内容走默认插槽里的 RsDescriptionsItem。编辑用 Form，大量行列用 Table。没有组件事件，也没有 defineExpose。',
    descriptionEn:
      'A read-only label and value grid for detail pages. The list is a native dl and each entry is dt / dd — no Reka. Pass items, or put RsDescriptionsItem in the default slot. Use Form to edit and Table for large grids. No component events and no defineExpose.',
    whenToUse: [
      '资源详情、配置摘要、只读键值，需要列对齐。',
      '要改值用 Form。上千行或要排序、选择用 Table。单个 KPI 用 StatCard。',
      '不要把它当表格：没有排序、虚拟滚动或单元格编辑。',
    ],
    whenToUseEn: [
      'Resource details and read-only key-value summaries that need aligned labels.',
      'Use Form to edit, Table for thousands of rows or sorting and selection, StatCard for one KPI.',
      'This is not a table: no sorting, virtualization, or cell editing.',
    ],
    demos: [
      { id: 'demo-basic', title: '数据驱动', titleEn: 'Items' },
      { id: 'demo-border', title: '边框', titleEn: 'Border' },
      { id: 'demo-placement', title: '标签位置', titleEn: 'Label placement' },
      { id: 'demo-span', title: '列与跨列', titleEn: 'Columns and span' },
      { id: 'demo-size', title: '尺寸', titleEn: 'Size' },
      { id: 'demo-radius', title: '圆角', titleEn: 'Radius' },
      { id: 'demo-colon', title: '冒号', titleEn: 'Colon' },
      { id: 'demo-label', title: '标签列', titleEn: 'Label column' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-empty', title: '空值', titleEn: 'Empty values' },
      { id: 'demo-scene', title: '详情页', titleEn: 'Detail page' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'title',
        type: 'string',
        description: '标题。未传且无 #title 时不渲染标题。有标题时作为 dl 的可访问名称。',
        descriptionEn: 'Heading. Omitted when neither the prop nor #title is set. When present, it names the dl.',
      },
      {
        name: 'items',
        type: 'RsDescriptionsItemData[]',
        default: '[]',
        defaultEn: '[]',
        description: '数据条目：label、value、span、key。有默认插槽时不渲染 items。',
        descriptionEn: 'Data rows: label, value, span, key. Ignored when the default slot is set.',
      },
      {
        name: 'columns',
        type: 'number',
        default: '3',
        defaultEn: '3',
        description: '列数。小于 1 或非数字时回退到至少 1 列（非数字回退 3）。不是 column。',
        descriptionEn: 'Column count. Values below 1 or non-numeric fall back to at least 1 (non-numeric falls back to 3). The prop name is columns, not column.',
      },
      {
        name: 'labelPlacement',
        type: "'left' | 'top'",
        default: "'left'",
        defaultEn: "'left'",
        description: '标签在值的左侧或上方。',
        descriptionEn: 'Place the label to the side or above the value.',
      },
      {
        name: 'bordered',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '表格外框与单元格分隔。关掉后只剩键值，没有描边。',
        descriptionEn: 'Outer frame and cell rules. Turn off for plain key-value pairs.',
      },
      {
        name: 'size',
        type: "'ssm' | 'sm' | 'md' | 'lg'",
        description: '密度。未传跟 Form / RsConfigProvider.controlSize，再回退 md。',
        descriptionEn: 'Density. Omit to follow Form or RsConfigProvider.controlSize, then md.',
      },
      {
        name: 'radius',
        type: 'RsRadius',
        description: '有边框时的圆角。未传跟 ConfigProvider.controlRadius，再回退 md。',
        descriptionEn: 'Corner radius when bordered. Omit to follow ConfigProvider.controlRadius, then md.',
      },
      {
        name: 'colon',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '标签后追加冒号。字符走 label.colon（zh-CN 全角，en-US 半角），对读屏隐藏。',
        descriptionEn: 'Append a colon after labels. The glyph is label.colon (fullwidth in zh-CN, ASCII in en-US) and is hidden from assistive tech.',
      },
      {
        name: 'labelWidth',
        type: 'number | string',
        description: '左标签列宽。数字按 px。空串、负数和含 ; { } 或 url( 的字符串忽略。',
        descriptionEn: 'Side-label column width. A number is pixels. Empty, negative, and strings containing ; { } or url( are ignored.',
      },
      {
        name: 'labelAlign',
        type: "'start' | 'center' | 'end'",
        default: "'start'",
        defaultEn: "'start'",
        description: '标签在单元格内对齐。start / end 跟书写方向，不要用 left / right。',
        descriptionEn: 'Label alignment inside the cell. start / end follow writing direction. Do not use left / right.',
      },
      {
        name: 'emptyText',
        type: 'string',
        description: '替换 null / undefined。未传走 descriptions.empty（两种内置语言都是 —）。空字符串不显示占位。0 和 "" 不受影响。',
        descriptionEn: 'Replacement for null / undefined. Omit to use descriptions.empty (— in both built-in locales). An empty string hides the placeholder. 0 and "" are unchanged.',
      },
      {
        name: 'id',
        type: 'string',
        description: '根节点 id。',
        descriptionEn: 'Root id.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '覆盖 dl 的可访问名称。未传且有标题时用标题的 aria-labelledby。',
        descriptionEn: 'Override the dl accessible name. When omitted and a title exists, the dl uses aria-labelledby.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。描述列表不是控件。操作放在 #extra 或值里的 RsButton 上。',
        descriptionEn: 'No component events. A description list is not a control. Put actions on RsButton in #extra or in a value.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: 'RsDescriptionsItem。一旦传入，items 不再渲染。',
        descriptionEn: 'RsDescriptionsItem children. When set, items are not rendered.',
      },
      {
        name: 'title',
        type: '—',
        description: '自定义标题。优先于 title。',
        descriptionEn: 'Custom heading. Wins over title.',
      },
      {
        name: 'extra',
        type: '—',
        description: '标题行末尾的操作，例如编辑按钮。',
        descriptionEn: 'Actions at the end of the heading row, such as an edit button.',
      },
      {
        name: 'item-${key}',
        type: '—',
        description: '某条 items 的值。key 缺省时用下标。优先于 value。',
        descriptionEn: 'Value for one items row. The index is used when key is omitted. Wins over value.',
      },
      {
        name: 'label-${key}',
        type: '—',
        description: '某条 items 的标签。key 缺省时用下标。优先于 label。',
        descriptionEn: 'Label for one items row. The index is used when key is omitted. Wins over label.',
      },
      {
        name: 'label（RsDescriptionsItem）',
        type: '—',
        description: '子项自定义标签。优先于 label prop。',
        descriptionEn: 'Custom label on RsDescriptionsItem. Wins over the label prop.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在描述列表 ref 上调方法。',
        descriptionEn: 'No defineExpose. Do not call methods on the descriptions ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-descriptions-border / radius / label-bg',
        default: 'theme',
        description: '外框、圆角、标签底。随 data-rs-theme。不要写死 hex。',
        descriptionEn: 'Frame, radius, and label wash. Follow data-rs-theme. Do not hard-code hex.',
      },
      {
        name: '--rs-descriptions-title / label-fg / value-fg',
        default: 'theme',
        description: '标题、标签、值的文字色。默认接 --rs-text-primary / --rs-text-secondary。',
        descriptionEn: 'Title, label, and value color. They follow --rs-text-primary and --rs-text-secondary.',
      },
      {
        name: '--rs-descriptions-label-width',
        default: '7.5rem',
        description: '左标签列宽。labelWidth 只覆盖当前这一份。',
        descriptionEn: 'Side-label column width. labelWidth overrides it for that instance.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。列表是原生 dl，条目是 dt / dd。业务与文档站不要 import reka-ui。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The list is a native dl and each entry is dt / dd. Apps and the docs site must not import reka-ui.',
      },
      {
        q: '为什么 prop 叫 columns 而不是 column？',
        a: '公开名称一直是 columns。不要再加 column 别名。响应式列数由调用方传入数字，组件不订阅 matchMedia，避免监听泄漏。',
        qEn: 'Why is the prop columns and not column?',
        aEn: 'The public name has always been columns. There is no column alias. Pass a number for responsive layouts. The component does not subscribe to matchMedia, so it does not leak a listener.',
      },
      {
        q: '为什么没有 labelStyle / contentStyle？',
        a: '颜色和圆角走 --rs-descriptions-*、size、radius。列宽用 labelWidth，对齐用 labelAlign。不要在组件上写内联色值。',
        qEn: 'Why is there no labelStyle or contentStyle?',
        aEn: 'Color and radius use --rs-descriptions-*, size, and radius. Width is labelWidth and alignment is labelAlign. Do not pass inline colors.',
      },
      {
        q: '空值为什么是破折号？0 会不会被当成空？',
        a: '只有 null / undefined 显示 descriptions.empty（内置语言是 —）。0 和空字符串原样显示。要改占位传 emptyText，或用 registerRsLocale 覆盖 descriptions.empty。',
        qEn: 'Why is the empty marker an em dash? Does 0 count as empty?',
        aEn: 'Only null and undefined use descriptions.empty (— in the built-in locales). 0 and an empty string render as themselves. Pass emptyText, or override descriptions.empty with registerRsLocale.',
      },
      {
        q: '点了为什么没反应？有没有 click？',
        a: '没有 defineEmits。可感知的点击绑在 #extra 或值里的 RsButton 上。',
        qEn: 'Why does a click do nothing? Is there a click event?',
        aEn: 'There is no defineEmits. Bind a click you can feel on RsButton in #extra or in a value.',
      },
      {
        q: '字段很多会不会卡、会不会泄漏？',
        a: '布局是 CSS grid，不测量、不挂 ResizeObserver、定时器或窗口监听，卸载时没有要摘的订阅。几十条详情没问题。上千行改用 Table 的虚拟滚动。',
        qEn: 'Will a long list jank or leak?',
        aEn: 'Layout is CSS grid. There is no measurement, ResizeObserver, timer, or window listener, and nothing to detach on unmount. Dozens of fields are fine. Use Table virtualization for thousands of rows.',
      },
    ],
    related: ['form', 'card', 'stat-card', 'table'],
  },
  {
    slug: 'stat-card',
    name: 'RsStatCard',
    title: 'StatCard',
    titleZh: '指标卡',
    group: 'data',
    summary: '一张卡片上的一个 KPI：名称、数值、单位与涨跌。',
    description:
      '概览页扫读单个指标。根是原生 section，不包 Reka。label 是名称，不是标题层级。数字默认原样输出，只有 format 或 precision 才按当前 locale 走 Intl。涨跌方向和好坏分开。整块表面用 Card，键值明细用 Descriptions，可编辑数字用 InputNumber。没有组件事件，也没有 defineExpose。',
    descriptionEn:
      'One KPI for an overview. The root is a native section — no Reka. label is the metric name, not a heading level. Numbers render as raw text until format or precision turns on Intl for the current locale. Trend direction is separate from whether the change is good. Use Card for a surface, Descriptions for a key-value list, and InputNumber to edit a number. No component events and no defineExpose.',
    whenToUse: [
      '概览页需要扫读几个核心数字，并带单位或相对上一时段的变化。',
      '同一数字要随 RsConfigProvider.locale 分组、紧凑记法或货币位置变化时，传数字并打开 format。',
      '整页内容容器用 Card。只读字段表用 Descriptions。用户要改的数用 InputNumber。',
    ],
    whenToUseEn: [
      'An overview needs a few core numbers, with a unit or a change from the previous period.',
      'Pass a number and turn on format when grouping, compact notation, or currency placement must follow RsConfigProvider.locale.',
      'Use Card for a content surface, Descriptions for a read-only field list, and InputNumber when the user edits the number.',
    ],
    demos: [
      { id: 'demo-basic', title: '基本用法', titleEn: 'Basic' },
      { id: 'demo-loading', title: '加载', titleEn: 'Loading' },
      { id: 'demo-format', title: '数字与货币', titleEn: 'Numbers and currency' },
      { id: 'demo-trend', title: '涨跌', titleEn: 'Trend' },
      { id: 'demo-affix', title: '单位', titleEn: 'Units' },
      { id: 'demo-size', title: '疏密', titleEn: 'Density' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'label',
        type: 'string',
        description: '指标名。渲染为 p，不是 h1–h6，避免一排 KPI 污染大纲。不是 title。',
        descriptionEn: 'Metric name. Rendered as a p, not h1–h6, so a row of KPIs does not flood the outline. The prop is label, not title.',
      },
      {
        name: 'value',
        type: 'string | number',
        description: '数值。字符串原样显示。有限数字在 format / precision 打开后按 locale 格式化。',
        descriptionEn: 'The figure. Strings render as written. Finite numbers are formatted for the locale only when format or precision is set.',
      },
      {
        name: 'description',
        type: 'string',
        description: '数值下的说明，例如统计区间。',
        descriptionEn: 'Caption under the figure, such as the time window.',
      },
      {
        name: 'accent',
        type: "'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'primary'",
        defaultEn: "'primary'",
        description: '顶角色条。只表示指标类别，不表示涨跌好坏。',
        descriptionEn: 'Top bar. It marks the metric, not whether a trend is good or bad.',
      },
      {
        name: 'loading',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '用骨架代替数值、单位和涨跌，并设 aria-busy。说明和默认插槽仍在。组件内部不排定时器。',
        descriptionEn: 'Replace the figure, units, and trend with a skeleton and set aria-busy. The caption and default slot stay. The component does not start a timer.',
      },
      {
        name: 'prefix',
        type: 'string',
        description: '数值前的短文本。货币符号优先用 format.style=currency，由 locale 决定符号在前还是在后。',
        descriptionEn: 'Short text before the figure. For money, prefer format.style=currency so the locale places the symbol.',
      },
      {
        name: 'suffix',
        type: 'string',
        description: '数值后的单位，例如 ms、req/s。书写方向下仍跟在数字后面。',
        descriptionEn: 'Unit after the figure, such as ms or req/s. It stays after the number in reading order.',
      },
      {
        name: 'trend',
        type: "'up' | 'down' | 'flat'",
        description: '变化方向。上升不自动当成好消息。箭头对读屏隐藏，方向词走 statCard.trend.*。',
        descriptionEn: 'Change direction. Up is not automatically good. The mark is hidden from assistive tech; the word comes from statCard.trend.*.',
      },
      {
        name: 'delta',
        type: 'string | number',
        description: '变化量。字符串原样；数字跟随 format / precision。0 会显示。',
        descriptionEn: 'Change amount. Strings render as written; numbers follow format / precision. 0 is shown.',
      },
      {
        name: 'trendTone',
        type: "'neutral' | 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        default: "'neutral'",
        defaultEn: "'neutral'",
        description: '涨跌文字色。与 trend 独立：错误率上升用 danger，收入上升用 success。',
        descriptionEn: 'Trend text color, independent of trend. An error-rate increase uses danger; a revenue increase uses success.',
      },
      {
        name: 'format',
        type: 'boolean | Intl.NumberFormatOptions',
        default: 'false',
        defaultEn: 'false',
        description: 'false 保持原文。true 用当前 locale 的默认分组。对象传给 Intl.NumberFormat，例如 notation: compact 或 style: currency。',
        descriptionEn: 'false keeps the raw text. true uses the current locale grouping. An object is passed to Intl.NumberFormat, such as notation: compact or style: currency.',
      },
      {
        name: 'precision',
        type: 'number',
        description: '定点小数位数（0–20）。即使 format 为 false 也会格式化数字。字符串 value 不受影响。',
        descriptionEn: 'Fixed fraction digits (0–20). Formats numbers even when format is false. String values are unchanged.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        default: "'md'",
        defaultEn: "'md'",
        description: '疏密：内边距与数值字号。不是控件 size，没有 ssm。',
        descriptionEn: 'Density: padding and figure size. Not control size — no ssm.',
      },
      {
        name: 'id',
        type: 'string',
        description: '根节点 id。',
        descriptionEn: 'Root id.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '把整张卡标成命名区域。默认不设，避免一排 KPI 都变成 landmark。',
        descriptionEn: 'Name the card as a region. Omit it so a row of KPIs does not become a row of landmarks.',
      },
    ],
    events: [
      {
        name: '—',
        type: 'none',
        description: '不发出组件事件。可点的指标卡请在外面包链接或按钮，不要给 StatCard 绑 click。',
        descriptionEn: 'No component events. Wrap a clickable metric in a link or button — do not bind click on StatCard.',
      },
    ],
    slots: [
      {
        name: 'default',
        type: '—',
        description: '数值和说明下面的附加内容，例如进度或操作按钮。loading 时仍渲染。',
        descriptionEn: 'Extra content under the figure and caption, such as a meter or an action. Still rendered while loading.',
      },
      {
        name: 'value',
        type: '—',
        description: '自定义数值。优先于 value。前后仍可加 prefix / suffix。',
        descriptionEn: 'Custom figure. Wins over value. prefix / suffix can still sit beside it.',
      },
      {
        name: 'prefix',
        type: '—',
        description: '自定义前缀，优先于 prefix。',
        descriptionEn: 'Custom prefix. Wins over prefix.',
      },
      {
        name: 'suffix',
        type: '—',
        description: '自定义后缀，优先于 suffix。',
        descriptionEn: 'Custom suffix. Wins over suffix.',
      },
      {
        name: 'icon',
        type: '—',
        description: '名称行末尾的装饰图标，对读屏隐藏。',
        descriptionEn: 'Decorative icon at the end of the name row. Hidden from assistive tech.',
      },
      {
        name: 'trend',
        type: '—',
        description: '自定义涨跌行，优先于 trend / delta。',
        descriptionEn: 'Custom trend row. Wins over trend / delta.',
      },
      {
        name: 'description',
        type: '—',
        description: '自定义说明，优先于 description。',
        descriptionEn: 'Custom caption. Wins over description.',
      },
    ],
    methods: [
      {
        name: '—',
        type: 'none',
        description: '没有 defineExpose。不要在指标卡 ref 上调 open / close。',
        descriptionEn: 'No defineExpose. Do not call open or close on the stat card ref.',
      },
    ],
    tokens: [
      {
        name: '--rs-border / --rs-surface / --rs-shadow-sm / --rs-radius',
        default: 'theme',
        description: '边框、表面、阴影、圆角。随 data-rs-theme。',
        descriptionEn: 'Border, surface, shadow, and radius. Follow data-rs-theme.',
      },
      {
        name: '--rs-text-primary / --rs-text-secondary',
        default: 'theme',
        description: '数值与名称、说明的文字色。不写 --rs-text / --rs-muted。',
        descriptionEn: 'Figure, name, and caption color. Do not use --rs-text or --rs-muted.',
      },
      {
        name: '--rs-primary / --rs-success / --rs-warning / --rs-danger / --rs-info',
        default: 'theme',
        description: '色条与 trendTone。accent 写入 --rs-stat-accent。',
        descriptionEn: 'Bar and trendTone. accent sets --rs-stat-accent.',
      },
      {
        name: '--rs-surface-hover',
        default: 'theme',
        description: '加载骨架底色。',
        descriptionEn: 'Loading skeleton fill.',
      },
      {
        name: '--rs-font-size-* / --rs-font-weight-* / --rs-space-*',
        default: 'theme',
        description: '字号、字重、疏密内边距。数值使用 tabular-nums。',
        descriptionEn: 'Type size, weight, and density padding. Figures use tabular-nums.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 section。业务与文档站不要 import reka-ui。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is a native section. Apps and the docs site must not import reka-ui.',
      },
      {
        q: '为什么 prop 叫 label 而不是 title？',
        a: '指标名不是页面标题。用 p 而不是标题标签，一排 KPI 不会打乱大纲。内容卡的标题仍是 Card 的 title。',
        qEn: 'Why is the prop label and not title?',
        aEn: 'A metric name is not a page heading. It is a p, not a heading, so a row of KPIs does not rewrite the outline. Card title is still the heading for a content card.',
      },
      {
        q: '12480 为什么没有千分位？',
        a: '默认关闭格式化，已有页面不会突然变成 12,480 或 1.2万。传数字并设 format，或传 precision。已经拼好的字符串（例如 0.12%）保持原样。',
        qEn: 'Why does 12480 have no grouping separator?',
        aEn: 'Formatting is off by default, so existing pages do not suddenly show 12,480 or 1.2万. Pass a number with format, or pass precision. A string you already built, such as 0.12%, stays as written.',
      },
      {
        q: '上升是不是就是变好？',
        a: '不是。trend 只表示方向，trendTone 表示好坏。错误率上升用 trend="up" trend-tone="danger"。不要只靠颜色：箭头旁有方向词给读屏。',
        qEn: 'Does up mean the metric improved?',
        aEn: 'No. trend is direction and trendTone is whether that is good. An error-rate increase is trend="up" and trend-tone="danger". Color is not the only signal: assistive tech hears the direction word.',
      },
      {
        q: '货币符号该放 prefix 吗？',
        a: '不要。符号在前还是在后、小数位和货币代码都跟 locale。用 format 的 style: currency 与 currency。prefix / suffix 留给 ms、req/s 这种你自己控制的单位。',
        qEn: 'Should the currency symbol go in prefix?',
        aEn: 'No. Symbol placement, fraction digits, and the currency code follow the locale. Use format with style: currency and currency. Keep prefix / suffix for units you control, such as ms or req/s.',
      },
      {
        q: '点了为什么没反应？数值变化会不会被读屏打断？',
        a: '没有 defineEmits，也没有 aria-live。数值更新不会自动播报。需要播报时把卡片放进你自己的 live region。可点操作放在默认插槽的 RsButton 里，或把整张卡包进链接。',
        qEn: 'Why does a click do nothing? Will a value change interrupt a screen reader?',
        aEn: 'There is no defineEmits and no aria-live. Value updates are not announced. Wrap the card in your own live region when they should be. Put a clickable action on RsButton in the default slot, or wrap the card in a link.',
      },
      {
        q: '加载和格式化会不会泄漏或卡顿？',
        a: '没有定时器、窗口监听或 ResizeObserver，卸载时没有要摘的订阅。骨架动画是 CSS，减少动态时停住。Intl.NumberFormat 最多留 24 个，相同 locale 与选项会复用。非法选项回退成原文，不抛错。不要在这里做数字滚动动画。',
        qEn: 'Can loading or formatting leak or jank?',
        aEn: 'There is no timer, window listener, or ResizeObserver, and nothing to detach on unmount. The skeleton is CSS and stops under reduced motion. At most 24 Intl.NumberFormat instances are kept, and the same locale plus options are reused. Invalid options fall back to the raw text and do not throw. Do not add a count-up animation here.',
      },
    ],
    related: ['card', 'descriptions', 'input-number'],
  },
]
