import type { ComponentDoc } from '../types'

export const editorComponents: ComponentDoc[] = [
  {
    slug: 'code-block',
    name: 'RsCodeBlock',
    title: 'CodeBlock',
    titleZh: '代码块',
    group: 'editor',
    summary: '只读代码展示，可复制；也可改为可编辑。',
    description:
      '文档、接口响应和短脚本。根是原生 figure，不包 Reka。默认只读，语言条上有复制；传入 downloadFilename 才出现下载。需要补全或诊断用 CodeEditor，IDE 级用 Monaco。日志用 RsLog，交互终端用 RsTerminal。',
    descriptionEn:
      'Docs, API payloads, and short scripts. The root is a native figure — no Reka. Read-only by default, with Copy on the language bar; Download appears only when downloadFilename is set. Use CodeEditor for completions, Monaco for an IDE, RsLog for logs, and RsTerminal for a PTY.',
    whenToUse: [
      '文档示例、JSON 响应、几十行以内的脚本。',
      '只要改几行、不需要语言服务时打开 editable。',
      '补全、诊断、多文件用 CodeEditor 或 Monaco。流式日志用 RsLog。',
    ],
    whenToUseEn: [
      'Doc samples, JSON payloads, and scripts of a few dozen lines.',
      'Turn on editable for a few edits when you do not need a language service.',
      'Use CodeEditor or Monaco for completions and diagnostics. Use RsLog for streaming logs.',
    ],
    demos: [
      { id: 'demo-basic', title: '只读代码', titleEn: 'Read only' },
      { id: 'demo-languages', title: '语言', titleEn: 'Languages' },
      { id: 'demo-file', title: '文件名与高亮', titleEn: 'File and highlight' },
      { id: 'demo-chrome', title: '行号与高度', titleEn: 'Lines and height' },
      { id: 'demo-editable', title: '可编辑', titleEn: 'Editable' },
      { id: 'demo-embed', title: '嵌入', titleEn: 'Embedded' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      { name: 'code', type: 'string', description: '源码。', descriptionEn: 'Source text.' },
      {
        name: 'lang',
        type: 'string',
        default: "'text'",
        defaultEn: "'text'",
        description: '语法标识。未知语言按纯文本显示。',
        descriptionEn: 'Grammar id. Unknown languages render as plain text.',
      },
      {
        name: 'filename',
        type: 'string',
        description: '语言条上的文件名。不触发下载。',
        descriptionEn: 'Filename shown on the bar. Does not add Download.',
      },
      {
        name: 'copyLabel',
        type: 'string',
        description: '覆盖「复制」。未传走 codeBlock.copy。',
        descriptionEn: 'Overrides Copy. Defaults to codeBlock.copy.',
      },
      {
        name: 'copiedLabel',
        type: 'string',
        description: '覆盖「已复制」。未传走 codeBlock.copied。',
        descriptionEn: 'Overrides the success label. Defaults to codeBlock.copied.',
      },
      {
        name: 'copyFailedLabel',
        type: 'string',
        description: '覆盖「复制失败」。未传走 codeBlock.copyFailed。',
        descriptionEn: 'Overrides the failure label. Defaults to codeBlock.copyFailed.',
      },
      {
        name: 'downloadFilename',
        type: 'string',
        description: '提供时显示下载。只保留文件名最后一段。',
        descriptionEn: 'Shows Download when set. Only the last path segment is kept.',
      },
      {
        name: 'downloadLabel',
        type: 'string',
        description: '覆盖「下载」。未传走 codeBlock.download。',
        descriptionEn: 'Overrides Download. Defaults to codeBlock.download.',
      },
      {
        name: 'editable',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '允许改正文，击键发出 update:code。',
        descriptionEn: 'Allows edits and emits update:code on keystrokes.',
      },
      {
        name: 'showBar',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '为 false 时隐藏语言条，并取消默认最大高度。',
        descriptionEn: 'Hides the bar and removes the default max height.',
      },
      {
        name: 'lineNumbers',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '为 false 时藏起行号槽。',
        descriptionEn: 'Hides the gutter when false.',
      },
      {
        name: 'wordWrap',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '为 false 时不折行，横向滚动。',
        descriptionEn: 'Disables wrapping so the block scrolls sideways.',
      },
      {
        name: 'highlightLines',
        type: 'number[]',
        description: '从 1 开始的行号。越界和重复会被丢掉。',
        descriptionEn: '1-based line numbers. Out-of-range and duplicate lines are dropped.',
      },
      {
        name: 'maxHeight',
        type: 'string',
        description: '盖过默认 32rem。嵌入且未传时不限制高度。',
        descriptionEn: 'Overrides the 32rem default. Embedded blocks stay uncapped when this is omitted.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '工具条名称；没有语言条时也用作 figure 的名称。',
        descriptionEn: 'Toolbar name. Also names the figure when the bar is hidden.',
      },
      { name: 'id', type: 'string', description: '根节点 id。', descriptionEn: 'Id on the root.' },
    ],
    events: [
      {
        name: 'update:code',
        type: '[value: string]',
        description: '仅 editable 且用户改正文时发出。从外面写入 code 不会回声。',
        descriptionEn: 'Emitted only when editable and the user edits. Setting code from outside does not echo.',
      },
      {
        name: 'copy',
        type: '[text: string]',
        description: '复制成功时发出全文。失败不发。',
        descriptionEn: 'Emitted with the full text after a successful copy. Not emitted on failure.',
      },
    ],
    slots: [
      {
        name: 'actions',
        type: '—',
        description: '语言条右侧、下载与复制之前的额外操作。',
        descriptionEn: 'Extra actions on the bar, before Download and Copy.',
      },
    ],
    methods: [
      {
        name: 'getSelection',
        type: '() => { text: string; startLine: number; endLine: number } | null',
        description: '当前选区。编辑器未就绪、没有选区或只有空白时返回 null。',
        descriptionEn: 'Current selection. Null when the editor is not ready, the range is empty, or the text is blank.',
      },
      {
        name: 'focus',
        type: '() => void',
        description: '把焦点放进代码。编辑器未就绪时无操作。',
        descriptionEn: 'Moves focus into the code. No-op when the editor is not ready.',
      },
    ],
    tokens: [
      { name: '--rs-code-block-bg', default: 'var(--rs-surface-elevated)', description: '代码区与外框背景。', descriptionEn: 'Frame and editor background.' },
      { name: '--rs-code-block-fg', default: 'var(--rs-text-primary)', description: '文件名与正文颜色。', descriptionEn: 'Filename and text color.' },
      { name: '--rs-code-block-muted', default: 'var(--rs-text-tertiary)', description: '语言名、行号与按钮。', descriptionEn: 'Language label, gutter, and buttons.' },
      { name: '--rs-code-block-border', default: 'var(--rs-border-subtle)', description: '外框、语言条与按钮描边。', descriptionEn: 'Frame, bar, and button border.' },
      { name: '--rs-code-block-bar-bg', default: '表面与描边混合', description: '语言条背景。', descriptionEn: 'Language bar background.' },
      { name: '--rs-code-block-gutter', default: '表面与描边混合', description: '行号槽背景。', descriptionEn: 'Gutter background.' },
      { name: '--rs-code-block-highlight', default: '主色 14% 混合', description: 'highlightLines 的行底色。', descriptionEn: 'Background for highlightLines.' },
      { name: '--rs-code-block-max-height', default: '32rem', description: '代码区最大高度。嵌入默认不限制。', descriptionEn: 'Max editor height. Embedded blocks are uncapped by default.' },
      { name: '--rs-code-font-family', default: 'var(--rs-font-mono)', description: '代码字族。', descriptionEn: 'Code font family.' },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 figure，语言条是 figcaption。业务与文档站不要 import reka-ui。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is a native figure and the bar is a figcaption. Apps and the docs site must not import reka-ui.',
      },
      {
        q: '和 CodeEditor、Monaco 怎么选？',
        a: '只展示或改几行用本组件。要补全、悬停、诊断用 CodeEditor。要语言服务和多文件用 Monaco，并按路由懒加载。',
        qEn: 'How do I choose among CodeEditor and Monaco?',
        aEn: 'Use this for display or a few edits. Use CodeEditor for completion, hover, and diagnostics. Use Monaco for a language service and many files, and lazy-load it.',
      },
      {
        q: '切换主题会不会把文档清掉？',
        a: '不会。明暗只重配语法色，正文、选区和滚动位置留着。多个代码块共用一个 data-rs-theme 观察器。',
        qEn: 'Does a theme change wipe the document?',
        aEn: 'No. Light and dark only swap the syntax theme. The text, selection, and scroll position stay. Every block shares one data-rs-theme observer.',
      },
      {
        q: 'HTTP 页面能复制吗？',
        a: '能。先走剪贴板 API，失败再用 execCommand，桌面壳还有一层兜底。失败时按钮改为「复制失败」，并且不发 copy。',
        qEn: 'Does copy work on HTTP?',
        aEn: 'Yes. It tries the Clipboard API, then execCommand, then the desktop shell. On failure the button reads “Copy failed” and copy is not emitted.',
      },
    ],
    related: ['code-editor', 'markdown', 'log'],
  },
  {
    slug: 'code-editor',
    name: 'RsCodeEditor',
    title: 'CodeEditor',
    titleZh: '代码编辑器',
    group: 'editor',
    summary: '基于 CodeMirror 的轻量编辑器。',
    description:
      '配置、SQL 片段和短脚本。根是带 role=group 的原生区域，编辑面是 CodeMirror，不包 Reka。theme=auto 跟随页面 data-rs-theme；传 light 或 dark 时在根上写同名属性，做成主题岛。需要语言服务、多文件或 diff 时用 Monaco。只读展示用 CodeBlock。',
    descriptionEn:
      'Settings, SQL fragments, and short scripts. The root is a native role=group; the surface is CodeMirror. It does not wrap Reka. theme=auto follows the page data-rs-theme. light or dark writes that attribute on the root so the editor becomes a theme island. Use Monaco for a language service, many files, or diff. Use CodeBlock for read-only snippets.',
    whenToUse: [
      '设置页里的 JSON、YAML、TOML 或短 SQL。',
      '只要只读复制时用 CodeBlock。',
      '要补全语言服务、多文件或 diff 时用 Monaco。',
      '作业输出用 Log，交互式 shell 用 Terminal。',
    ],
    whenToUseEn: [
      'JSON, YAML, TOML, or a short SQL snippet on a settings page.',
      'Use CodeBlock when the text is read-only and only needs copy.',
      'Use Monaco for a language service, many files, or diff.',
      'Use Log for job output and Terminal for an interactive shell.',
    ],
    demos: [
      { id: 'demo-basic', title: '绑定文本', titleEn: 'Bound text' },
      { id: 'demo-language', title: '语言', titleEn: 'Language' },
      { id: 'demo-state', title: '只读、禁用与折行', titleEn: 'Read-only, disabled, wrap' },
      { id: 'demo-theme', title: '主题', titleEn: 'Theme' },
      { id: 'demo-diagnostics', title: '诊断与跳转', titleEn: 'Diagnostics and jump' },
      { id: 'demo-toolbar', title: '工具条与嵌入', titleEn: 'Toolbar and embedded' },
      { id: 'demo-assist', title: 'SQL、行内编辑与定义', titleEn: 'SQL, inline edit, definition' },
    ],
    props: [
      { name: 'v-model', type: 'string', default: "''", description: '正文。编辑器内部改动写回；外部改动整篇替换。', descriptionEn: 'Document. Edits inside write back. An external change replaces the whole document.' },
      { name: 'language', type: "'plaintext' | 'json' | 'typescript' | 'javascript' | 'css' | 'html' | 'xml' | 'sql' | 'go' | 'python' | 'rust' | 'java' | 'cpp' | 'c' | 'shell' | 'yaml' | 'toml' | 'markdown' | 'vue'", default: 'plaintext', description: '语法。不认识的值按 plaintext。vue 用 HTML 高亮。toml 走 legacy mode。', descriptionEn: 'Grammar. Unknown values fall back to plaintext. vue uses the HTML grammar. toml uses a legacy mode.' },
      { name: 'theme', type: "'auto' | 'light' | 'dark'", default: 'auto', description: 'auto 跟随页面。light / dark 在根上写 data-rs-theme，语法色跟着这档，不跟着页面。', descriptionEn: 'auto follows the page. light / dark set data-rs-theme on the root, and syntax colors follow that value rather than the page.' },
      { name: 'height', type: 'number | string', default: '20rem', description: '数字当像素，字符串当 CSS 高度。', descriptionEn: 'A number is pixels. A string is a CSS height.' },
      { name: 'readonly', type: 'boolean', default: 'false', description: '不可编辑，仍可聚焦和复制。编辑区 aria-readonly。', descriptionEn: 'Not editable. Focus and copy still work. The surface sets aria-readonly.' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '不可编辑、不可聚焦。根 aria-disabled。', descriptionEn: 'Not editable and not focusable. The root sets aria-disabled.' },
      { name: 'showToolbar', type: 'boolean', default: 'true', description: '语言名条。外面已有工具条时关掉。', descriptionEn: 'Language strip. Turn it off when the host already has a toolbar.' },
      { name: 'embedded', type: 'boolean', default: 'false', description: '去掉边框和圆角，铺满父级。补全浮层挂到 body，避免被 overflow 裁切。', descriptionEn: 'Drops the border and radius and fills the parent. Completion popups mount on body so overflow does not clip them.' },
      { name: 'rounded', type: 'boolean', default: 'true', description: '外框圆角。embedded 时强制直角。', descriptionEn: 'Outer radius. embedded forces square corners.' },
      { name: 'gutterWidth', type: 'number', description: '行号栏最小宽度（px），用来和表格行号对齐。不传则随内容。', descriptionEn: 'Minimum line-number gutter width in px, for aligning with a table. Omitted means the gutter sizes to its content.' },
      { name: 'foldGutter', type: 'boolean', default: 'true', description: '折叠栏。关掉后只藏起来，方便和表格 gutter 对齐。', descriptionEn: 'Fold gutter. Turning it off hides it so the line numbers can align with a table gutter.' },
      { name: 'diagnostics', type: 'RsCodeEditorDiagnostic[]', default: '[]', description: '行下划线与底栏。点击底栏跳到该行。severity 为 error | warning | info。', descriptionEn: 'Line marks and a footer. A footer click jumps to that line. severity is error, warning, or info.' },
      { name: 'placeholder', type: 'string', description: '空文档占位。之后改值不用重建编辑器。', descriptionEn: 'Empty-document placeholder. Later changes do not rebuild the editor.' },
      { name: 'sqlConfig', type: 'RsCodeEditorSqlConfig', description: '仅 language=sql。dialect 为 postgresql（默认）| standard | mysql。schema / defaultTable / defaultSchema 传给 CodeMirror。改 schema 会重建编辑器并尽量保住光标。', descriptionEn: 'Only when language=sql. dialect is postgresql (default), standard, or mysql. schema / defaultTable / defaultSchema go to CodeMirror. Changing schema rebuilds the editor and tries to keep the cursor.' },
      { name: 'filePath', type: 'string', description: '当前文件路径。定义跳转用来判断要不要发 goto-definition。', descriptionEn: 'Current file path. Definition lookup uses it to decide whether to emit goto-definition.' },
      { name: 'hoverRequest', type: '(line: number, column: number, signal?: AbortSignal) => Promise<string | null>', description: '悬停说明。signal 在下一次悬停或卸载时 abort。返回空则不显示。', descriptionEn: 'Hover text. signal aborts on the next hover or on unmount. An empty result shows nothing.' },
      { name: 'definitionRequest', type: '(line: number, column: number, signal?: AbortSignal) => Promise<{ file: string, line: number, column?: number } | null>', description: 'Ctrl/Cmd+单击。同一文件内跳转；文件不同则发 goto-definition。', descriptionEn: 'Ctrl/Cmd+click. Same file jumps inside. A different file emits goto-definition.' },
      { name: 'completionRequest', type: '(prefix: string, suffix: string, line: number, column: number, signal?: AbortSignal) => Promise<string | null>', description: 'Ctrl/Cmd+Space 插入返回的文本。停顿约 900ms 后同一回调给出灰色预览，Tab 接受，Esc 丢掉。', descriptionEn: 'Ctrl/Cmd+Space inserts the returned text. After about 900ms the same callback can show a gray preview. Tab accepts it, Esc dismisses it.' },
      { name: 'inlineEditRequest', type: '(params: { selection, instruction, from, to, surroundingContext, signal? }) => Promise<string | null>', description: '选中文字后 Ctrl/Cmd+K。返回替换文本；null 或抛错显示失败文案。从无到有会重建编辑器，函数身份变化不会。', descriptionEn: 'Ctrl/Cmd+K with a selection. Return replacement text. null or a throw shows the failure copy. Turning the callback on or off rebuilds the editor. A new function identity does not.' },
      { name: 'wrap', type: 'boolean', default: 'true', description: '折行。默认开，和原先一致。改值不重建编辑器。', descriptionEn: 'Line wrap. On by default, matching the previous behavior. Changing it does not rebuild the editor.' },
      { name: 'autofocus', type: 'boolean', default: 'false', description: '第一次创建后聚焦。之后换语言不再抢焦点。', descriptionEn: 'Focus after the first create. A later language change does not steal focus.' },
      { name: 'ariaLabel', type: 'string', description: '读屏名称。不传走 codeEditor.label。', descriptionEn: 'Accessible name. Defaults to codeEditor.label.' },
      { name: 'id', type: 'string', description: '根节点 id。', descriptionEn: 'Root id.' },
    ],
    events: [
      { name: 'update:modelValue', type: '[value: string]', description: '正文变化。v-model 已经接上。', descriptionEn: 'The document changed. v-model is already wired to this.' },
      { name: 'goto-definition', type: '[{ file: string, line: number, column?: number }]', description: '定义落在另一个文件。同一文件只在内部跳转，不发这个事件。', descriptionEn: 'The definition is in another file. The same file jumps inside and does not emit.' },
      { name: 'ready', type: '[]', description: '编辑器创建完成。换语言、SQL schema 或行内编辑开关会再发一次。', descriptionEn: 'The editor finished creating. A language change, SQL schema change, or inline-edit toggle emits it again.' },
    ],
    slots: [
      { name: 'default', type: '—', description: '没有默认插槽。正文是 v-model。', descriptionEn: 'No default slot. The document is v-model.' },
      { name: 'toolbar', type: '—', description: '语言名右侧。showToolbar 为 false 时不渲染。', descriptionEn: 'Placed after the language name. Not rendered when showToolbar is false.' },
    ],
    methods: [
      { name: 'goToPosition', type: '(line: number, column?: number) => void', description: '宿主调用。跳到 1-based 行列并聚焦。未就绪时无操作。column 默认 1。', descriptionEn: 'Host call. Jump to a 1-based line and column and focus. No-op before ready. column defaults to 1.' },
      { name: 'focus', type: '() => void', description: '宿主调用。聚焦编辑区。禁用或未就绪时无操作。', descriptionEn: 'Host call. Focus the surface. No-op when disabled or before ready.' },
    ],
    tokens: [
      { name: '--rs-code-font-family / --rs-code-font-size / --rs-code-line-height', default: 'mono / sm / relaxed', description: '编辑区字体。CodeMirror 从这里读。', descriptionEn: 'Editor font. CodeMirror reads these.' },
      { name: '--rs-code-editor-inline-width', default: '28rem', description: '行内编辑面板和悬停卡片的最大宽度。', descriptionEn: 'Max width of the inline-edit panel and the hover card.' },
      { name: '--rs-code-editor-gutter-width', default: 'runtime', description: '由 gutterWidth 写入。', descriptionEn: 'Written from gutterWidth.' },
      { name: '--rs-border / --rs-border-subtle / --rs-input-bg / --rs-surface-elevated', default: 'theme', description: '外框、分隔、输入底和编辑表面。显式主题岛跟随根上的 data-rs-theme。', descriptionEn: 'Frame, divider, input fill, and editor surface. An explicit theme island follows data-rs-theme on the root.' },
      { name: '--rs-text-primary / --rs-text-secondary', default: 'theme', description: '正文与语言名、行号。', descriptionEn: 'Document text, language name, and line numbers.' },
      { name: '--rs-danger / --rs-warning / --rs-info', default: 'theme', description: '诊断色。', descriptionEn: 'Diagnostic colors.' },
      { name: '--rs-primary / --rs-primary-foreground', default: 'theme', description: '行内编辑的主按钮。', descriptionEn: 'Primary action on the inline-edit panel.' },
      { name: '--rs-radius / --rs-radius-sm / --rs-radius-xs', default: 'theme', description: '外框与面板圆角。', descriptionEn: 'Outer frame and panel radius.' },
      { name: '--rs-shadow / --rs-shadow-lg', default: 'theme', description: '悬停卡片与行内编辑面板。', descriptionEn: 'Hover card and inline-edit panel.' },
      { name: '--rs-z-dropdown', default: '50', description: '行内编辑面板。它在编辑器内部，不盖住对话框。', descriptionEn: 'Inline-edit panel. It stacks inside the editor and does not cover a dialog.' },
      { name: '--rs-focus-ring / --rs-focus-ring-width', default: 'theme', description: '行内编辑与诊断按钮的焦点环。', descriptionEn: 'Focus ring on inline edit and diagnostic buttons.' },
    ],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。根是原生区域，编辑面是 CodeMirror。业务与文档站不要 import reka-ui。v-model、语言、诊断和跳转语义与原来相同。', qEn: 'Do I still need reka-ui?', aEn: 'No. The root is a native region and the surface is CodeMirror. Apps and the docs site must not import reka-ui. v-model, language, diagnostics, and jump behave as before.' },
      { q: '和 CodeBlock、Monaco 怎么选？', a: '只读片段用 CodeBlock。这里是轻量可编辑。语言服务、断点槽、JSON Schema 用 Monaco，并按路由懒加载。Diff 不在 RsMonacoEditor 里。', qEn: 'When should I use CodeBlock or Monaco instead?', aEn: 'Use CodeBlock for a read-only snippet. This editor is the light editable surface. Use Monaco for a language service, a breakpoint gutter, or JSON Schema, and lazy-load it per route. Diff is not part of RsMonacoEditor.' },
      { q: '主题为什么和页面不一致？', a: 'theme=auto 跟 data-rs-theme。传 light 或 dark 会在这个编辑器根上再写一层，只影响它和里面的语法色。embedded 时补全浮层挂在 body 上，跟的是页面主题，为的是不被父级 overflow 裁切。', qEn: 'Why does the theme differ from the page?', aEn: 'theme=auto follows data-rs-theme. light or dark writes another attribute on this root and affects only this editor, including syntax colors. When embedded, completion popups mount on body and follow the page theme so a parent overflow does not clip them.' },
      { q: '补全请求会不会在关掉页面后还写回？', a: '不会。悬停、定义、补全和行内编辑在下一次请求或卸载时 abort 可选的 signal，并在视图销毁后不再 dispatch。多个编辑器共用一个主题监听，最后一个卸载才断开。', qEn: 'Can a completion write back after the page is gone?', aEn: 'No. Hover, definition, completion, and inline edit abort the optional signal on the next request or on unmount, and they do not dispatch after the view is destroyed. Editors share one theme listener. It disconnects when the last editor unmounts.' },
      { q: 'vue 和 toml 有高亮吗？', a: 'toml 有。vue 目前用 HTML 高亮，没有单文件语法。不认识的 language 显示为 Plain Text，也不上色。', qEn: 'Do vue and toml highlight?', aEn: 'toml does. vue currently uses the HTML grammar, not a single-file grammar. An unknown language shows Plain Text and no colors.' },
      { q: '行内编辑的快捷键是什么？', a: '先选中文字。Windows / Linux 是 Ctrl+K，macOS 是 ⌘K。没有 inlineEditRequest、只读或禁用时不打开。取消和按钮文案走 codeEditor.* 与 common.cancel。', qEn: 'What is the inline-edit shortcut?', aEn: 'Select text first. Windows and Linux use Ctrl+K. macOS uses ⌘K. It does not open without inlineEditRequest, or when read-only or disabled. Cancel and the other labels use codeEditor.* and common.cancel.' },
    ],
    related: ['monaco-editor', 'code-block', 'markdown'],
  },
  {
    slug: 'monaco-editor',
    name: 'RsMonacoEditor',
    title: 'MonacoEditor',
    titleZh: 'Monaco 编辑器',
    group: 'editor',
    summary: '基于 Monaco 的单文件代码编辑器。',
    description:
      'IDE 级单文件编辑：语法、补全、JSON Schema、查找替换、断点槽。根是原生 div，不包 Reka。宿主需 Vite 处理 worker，并调用 setupMonacoWorkers()。轻量页用 CodeEditor，只读片段用 CodeBlock。',
    descriptionEn:
      'Single-file IDE editing: grammar, completion, JSON Schema, find and replace, a breakpoint gutter. The root is a native div — no Reka. The host must handle Vite workers and call setupMonacoWorkers(). Use CodeEditor for a light page and CodeBlock for a read-only snippet.',
    whenToUse: [
      '需要语言服务、JSON Schema、多光标或断点槽。',
      '设置页里的短 JSON / SQL 用 CodeEditor。只读展示用 CodeBlock。',
      '按路由懒加载。不要放进营销站首屏。',
    ],
    whenToUseEn: [
      'You need a language service, JSON Schema, multi-cursor, or a breakpoint gutter.',
      'Use CodeEditor for a short JSON or SQL field. Use CodeBlock for read-only display.',
      'Lazy-load it per route. Do not put it on a marketing landing page.',
    ],
    demos: [
      { id: 'demo-basic', title: '绑定', titleEn: 'Binding' },
      { id: 'demo-language', title: '语言', titleEn: 'Language' },
      { id: 'demo-schema', title: 'JSON Schema', titleEn: 'JSON Schema' },
      { id: 'demo-readonly', title: '只读与禁用', titleEn: 'Read-only and disabled' },
      { id: 'demo-minimap', title: '缩略图', titleEn: 'Minimap' },
      { id: 'demo-theme', title: '主题', titleEn: 'Theme' },
      { id: 'demo-complete', title: '补全', titleEn: 'Completion' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-contextmenu', title: '右键', titleEn: 'Context menu' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
      { id: 'demo-embedded', title: '嵌入', titleEn: 'Embedded' },
      { id: 'demo-radius', title: '圆角', titleEn: 'Radius' },
      { id: 'demo-options', title: '构造选项', titleEn: 'Options' },
    ],
    props: [
      { name: 'v-model', type: 'string', default: "''", defaultEn: "''", description: '文档文本。外部写入会 setValue，同一内容不回声。', descriptionEn: 'Document text. An external write calls setValue and does not echo the same value.' },
      { name: 'language', type: "MonacoLanguage", default: "'json'", defaultEn: "'json'", description: '语言 id。json / javascript / typescript / sql / yaml / plaintext / mongodb-shell，以及 pgsql、mysql、postgresql 等 SQL 方言。变化会重建编辑器。', descriptionEn: 'Language id: json, javascript, typescript, sql, yaml, plaintext, mongodb-shell, plus SQL dialects such as pgsql, mysql, and postgresql. Changing it recreates the editor.' },
      { name: 'height', type: 'number | string', default: "'100%'", defaultEn: "'100%'", description: '高度。数字按 px，字符串按 CSS。', descriptionEn: 'Height. A number is px. A string is CSS.' },
      { name: 'readonly', type: 'boolean', default: 'false', defaultEn: 'false', description: '只读。仍可选中。Monaco 会提示文档只读。', descriptionEn: 'Read-only. Selection still works. Monaco shows its read-only notice.' },
      { name: 'disabled', type: 'boolean', default: 'false', defaultEn: 'false', description: '禁用。readOnly 且 domReadOnly，根节点 aria-disabled。不弹出只读提示。', descriptionEn: 'Disabled. Sets readOnly and domReadOnly, and aria-disabled on the root. No read-only notice.' },
      { name: 'theme', type: "'auto' | 'vs-dark' | 'light'", default: "'auto'", defaultEn: "'auto'", description: 'auto 跟 documentElement 的 data-rs-theme；未写属性时为浅色。light / vs-dark 使用带 token 色的 rs-light / rs-dark。Monaco setTheme 是进程级的。', descriptionEn: 'auto follows data-rs-theme on documentElement. A missing attribute is light. light and vs-dark use token-tinted rs-light and rs-dark. Monaco setTheme is process-global.' },
      { name: 'minimap', type: 'boolean', default: 'false', defaultEn: 'false', description: '右侧缩略图。', descriptionEn: 'Right-hand minimap.' },
      { name: 'glyphMargin', type: 'boolean', default: 'false', defaultEn: 'false', description: '行号左侧的断点槽。点击发 glyphMarginClick。', descriptionEn: 'Breakpoint gutter beside the line numbers. A click emits glyphMarginClick.' },
      { name: 'debugCurrentLine', type: 'number', default: '0', defaultEn: '0', description: '当前执行行（1-based）。0 表示没有。需要 glyphMargin。', descriptionEn: 'Current execution line (1-based). 0 means none. Requires glyphMargin.' },
      { name: 'debugBreakpoints', type: 'number[]', default: '[]', defaultEn: '[]', description: '断点行号（1-based）。需要 glyphMargin。', descriptionEn: 'Breakpoint lines (1-based). Requires glyphMargin.' },
      { name: 'embedded', type: 'boolean', default: 'false', defaultEn: 'false', description: '去掉自己的边框和底色，圆角跟父级，铺满父级。height 仍生效。', descriptionEn: 'Drops its own border and fill, inherits the parent radius, and fills the parent. height still applies.' },
      { name: 'radius', type: "'none' | 'xs' | 'sm' | 'md' | 'lg' | 'full'", default: "'md'", defaultEn: "'md'", description: '外框圆角。画布裁进圆角。未传时跟 ConfigProvider，再回退 md。embedded 时忽略，改跟父级。', descriptionEn: 'Outer radius. The canvas is clipped to it. Falls back to ConfigProvider, then md. Ignored when embedded; the parent radius is used.' },
      { name: 'jsonSchema', type: 'object', description: '仅 language=json。按本实例 URI 绑定，不覆盖别的 JSON 编辑器或外部 schema。', descriptionEn: 'language=json only. Bound to this instance URI. Does not replace other JSON editors or external schemas.' },
      { name: 'snippets', type: 'MonacoCompletionSnippet[]', description: '实例级片段。与 completionRequest 合并。Bridge LSP 的 SQL 方言不注册。', descriptionEn: 'Instance snippets, merged with completionRequest. Bridge LSP SQL dialects do not register a provider.' },
      { name: 'completionRequest', type: '(context: MonacoCompletionContext) => MonacoCompletionSnippet[] | Promise<...>', description: '按光标上下文返回候选。卸载或取消后不再写入建议。', descriptionEn: 'Returns candidates for the cursor context. After unmount or cancellation, suggestions are dropped.' },
      { name: 'completionTriggerCharacters', type: 'string[]', default: "['\"', '$', '{', ':', ',']", defaultEn: "['\"', '$', '{', ':', ',']", description: '触发补全的字符。同语言的编辑器合成一份。', descriptionEn: 'Characters that trigger completion. Editors of the same language share one list.' },
      { name: 'completionPrefixResolver', type: '(linePrefix: string) => string', description: '替换范围的前缀。默认按标识符字符切词。', descriptionEn: 'Prefix that defines the replace range. Defaults to an identifier scan.' },
      { name: 'options', type: 'Record<string, unknown>', description: '浅合并进 Monaco 构造选项。suggest 再浅合并一层。请保持引用稳定。options.theme 会盖过 theme。contextmenu 跟 contextMenu，不从这里盖。', descriptionEn: 'Shallow-merged into Monaco construction options. suggest is merged one level deeper. Keep the object referentially stable. options.theme overrides theme. contextmenu follows contextMenu and is not overridden here.' },
      { name: 'placeholder', type: 'string', description: '空文档时的占位。不写入 v-model。', descriptionEn: 'Shown when the document is empty. Not written to v-model.' },
      { name: 'ariaLabel', type: 'string', description: '文本框的可访问名称。未传走 monaco.label。', descriptionEn: 'Accessible name of the textbox. Defaults to monaco.label.' },
      { name: 'id', type: 'string', description: '根节点 id。未传时自动生成。', descriptionEn: 'Root id. Generated when omitted.' },
      { name: 'contextMenu', type: 'boolean', default: 'true', defaultEn: 'true', description: '原生右键菜单。关掉后不再弹出，contextmenu 仍发，并拦住浏览器菜单。options.contextmenu 不盖过它。', descriptionEn: 'Native context menu. When off, the menu stays closed, contextmenu still fires, and the browser menu is suppressed. options.contextmenu does not override it.' },
    ],
    events: [
      { name: 'update:modelValue', type: '[value: string]', description: 'v-model。文档变化时发出。外部 setValue 不回声。', descriptionEn: 'v-model. Emitted when the document changes. An external setValue does not echo.' },
      { name: 'glyphMarginClick', type: '[line: number]', description: '点击断点槽。行号 1-based。glyphMargin 关闭时不发。', descriptionEn: 'Breakpoint gutter click. Line is 1-based. Not emitted when glyphMargin is off.' },
      { name: 'focus', type: '[]', description: '文本区获得焦点。', descriptionEn: 'The text area gained focus.' },
      { name: 'blur', type: '[]', description: '文本区失去焦点。', descriptionEn: 'The text area lost focus.' },
      { name: 'ready', type: '[]', description: '编辑器创建完成。language 变化导致重建时会再发。', descriptionEn: 'The editor finished creating. Emitted again when language recreates it.' },
      { name: 'contextmenu', type: '[event: RsMonacoEditorContextMenu]', description: '右键。line / column 为 1-based，点在无光标处时为 0。selectedText 只在点击落在选区内时有值。x / y 是指针的视口坐标。', descriptionEn: 'Right-click. line and column are 1-based, or 0 when the target has no caret. selectedText is set only when the click lands inside the selection. x and y are viewport coordinates.' },
    ],
    slots: [
      { name: 'none', type: '—', description: '没有插槽。文档就是 v-model。', descriptionEn: 'No slots. The document is v-model.' },
    ],
    methods: [
      { name: 'format', type: '() => void', description: '宿主调用。执行 editor.action.formatDocument。失败时吞掉异常。', descriptionEn: 'Host call. Runs editor.action.formatDocument. Swallows a failed action.' },
      { name: 'getEditor', type: '() => IStandaloneCodeEditor | null', description: '宿主调用。返回 Monaco 实例。未挂载时为 null。不要用 InstanceType。', descriptionEn: 'Host call. Returns the Monaco instance, or null before mount. Do not use InstanceType.' },
      { name: 'revealLine', type: '(line: number) => void', description: '宿主调用。把该行滚到视口中央。line <= 0 无操作。', descriptionEn: 'Host call. Scrolls that line to the center. line <= 0 does nothing.' },
      { name: 'focus', type: '() => void', description: '宿主调用。聚焦文本区。', descriptionEn: 'Host call. Focuses the text area.' },
      { name: 'blur', type: '() => void', description: '宿主调用。若焦点在编辑器内，则 blur。', descriptionEn: 'Host call. Blurs when focus is inside the editor.' },
    ],
    tokens: [
      { name: '--rs-monaco-border / --rs-monaco-bg / --rs-monaco-fg', default: 'theme', description: '外框、表面、文字。随 data-rs-theme。', descriptionEn: 'Frame, surface, and text. Follow data-rs-theme.' },
      { name: '--rs-monaco-gutter / --rs-monaco-gutter-fg / --rs-monaco-line-highlight / --rs-monaco-selection', default: 'theme', description: '行号槽、当前行和选区。写进 Monaco 主题色。', descriptionEn: 'Gutter, current line, and selection. Written into the Monaco theme.' },
      { name: '--rs-monaco-widget-bg / --rs-monaco-widget-border', default: 'theme', description: '查找框等浮层表面。', descriptionEn: 'Find widget and other overlay surfaces.' },
      { name: '--rs-monaco-radius / --rs-monaco-padding / --rs-monaco-scrollbar-size', default: 'md / 0.5rem / 0.5rem', description: '圆角、内边距、滚动条。圆角由 radius 写入；embedded 时为 inherit。', descriptionEn: 'Radius, padding, and scrollbar. Radius is written from the radius prop. embedded sets inherit.' },
      { name: '--rs-monaco-glyph-width / --rs-monaco-decoration-width', default: '1rem / 0.25rem', description: '断点槽与普通装饰槽宽度。Monaco 只收 px。', descriptionEn: 'Breakpoint gutter and plain decoration width. Monaco takes px.' },
      { name: '--rs-monaco-disabled-opacity', default: '0.72', description: '禁用时的不透明度。', descriptionEn: 'Opacity while disabled.' },
      { name: '--rs-code-font-family / --rs-code-font-size / --rs-code-line-height', default: 'mono / sm / relaxed', description: '编辑区字体。主题切换时重读。', descriptionEn: 'Editor font. Reread when the theme changes.' },
      { name: '--rs-z-dropdown', default: '50', description: 'Find Widget。悬停卡片仍高于它。', descriptionEn: 'Find widget. Hover cards stay above it.' },
      { name: '--rs-focus-ring-width / --rs-focus-border', default: 'theme', description: '非 embedded 时，焦点在文本区上的外框环。', descriptionEn: 'Frame ring when the text area is focused and the editor is not embedded.' },
    ],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。根是原生 div，编辑面是 Monaco。业务与文档站不要 import reka-ui。v-model、语言、schema 和 format() 语义与原来相同。', qEn: 'Do I still need reka-ui?', aEn: 'No. The root is a native div and the surface is Monaco. Apps and the docs site must not import reka-ui. v-model, language, schema, and format() behave as before.' },
      { q: '和 CodeEditor、CodeBlock 怎么选？', a: '只读片段用 CodeBlock。短配置用 CodeEditor。这里要 worker，适合工作台。不要首屏引入。', qEn: 'When should I use CodeEditor or CodeBlock instead?', aEn: 'Use CodeBlock for a read-only snippet and CodeEditor for a short setting. This one needs workers and belongs on a workbench. Do not load it on the first screen.' },
      { q: '为什么两个编辑器主题会互相覆盖？', a: 'Monaco 的 setTheme 是进程级的。同一页后创建或后切换的实例决定所有编辑器的语法色。auto 跟 documentElement 的 data-rs-theme，不是父级深色岛。', qEn: 'Why do two editors overwrite each other’s theme?', aEn: 'Monaco setTheme is process-global. The instance that is created or switched last paints every editor. auto reads data-rs-theme on documentElement, not a parent dark island.' },
      { q: '菜单为什么还是英文？', a: '查找、命令面板等 Chrome 跟着 Monaco 的 NLS 构建。默认英文。中文用官方插件 monacoZhNls。组件自己的可访问名称走 monaco.label，跟 RsConfigProvider。', qEn: 'Why is the menu still English?', aEn: 'Find and the command palette follow the Monaco NLS build. The default is English. Chinese uses the monacoZhNls plugin. The component’s own accessible name uses monaco.label and RsConfigProvider.' },
      { q: '能做 diff 吗？', a: '不能。这是单文件编辑器。Diff 是另一套 Monaco API，不要从 getEditor() 假装它是 DiffEditor。', qEn: 'Can it diff?', aEn: 'No. This is a single-file editor. Diff is a different Monaco API. getEditor() is not a DiffEditor.' },
      { q: '卸载后还会不会占着补全和 schema？', a: '不会。内容、焦点、glyph 和右键监听随编辑器释放。同语言只留一个补全 Provider，按 model 分发，最后一个该语言的编辑器卸载时摘掉。JSON Schema 按实例 URI 删除。主题观察器在最后一个实例离开时断开。', qEn: 'Does unmount leave completion or schema behind?', aEn: 'No. Content, focus, glyph, and context-menu listeners go with the editor. One completion provider per language dispatches by model and is removed with the last editor of that language. JSON Schema is removed by instance URI. The theme observer disconnects when the last instance leaves.' },
      { q: '右键能换成自己的菜单吗？', a: '能。contextMenu 默认开，仍是 Monaco 的剪切、复制、粘贴。关掉后 contextmenu 给出行、列、选中文本和指针坐标，用 RsContextMenu.open({ x, y }) 打开自己的菜单。', qEn: 'Can I replace the context menu?', aEn: 'Yes. contextMenu defaults to on, which is Monaco’s Cut, Copy, and Paste. Turn it off and contextmenu reports the line, column, selected text, and pointer. Open your own menu with RsContextMenu.open({ x, y }).' },
      { q: 'RTL 页面会把代码翻过去吗？', a: '不会。源码面固定 dir=ltr，避免列号和光标被书写方向翻过去。外框间距仍用逻辑属性。', qEn: 'Does an RTL page reverse the code?', aEn: 'No. The source surface is dir=ltr so line numbers and the caret stay put. The frame still uses logical properties.' },
    ],
    related: ['code-editor', 'code-block', 'terminal'],
  },
  {
    slug: 'markdown',
    name: 'RsMarkdown',
    title: 'Markdown',
    titleZh: 'Markdown',
    group: 'editor',
    summary: 'GFM 编辑与消毒预览。',
    description:
      '说明、变更记录和知识片段。根是带名称的 section，模式条是 tablist，源码面是嵌入的 CodeEditor，不包 Reka。预览经 DOMPurify。只读片段用 CodeBlock，补全和诊断用 CodeEditor，富文本表面用 ProseEditor。不含公式和图表。',
    descriptionEn:
      'Notes, changelogs, and knowledge snippets. The root is a named section, the mode bar is a tablist, and the source is an embedded CodeEditor. It does not wrap Reka. The preview is sanitized with DOMPurify. Use CodeBlock for a read-only snippet, CodeEditor for completions, and ProseEditor for a rich-text surface. No math and no diagrams.',
    whenToUse: [
      '发布说明、内部文档、表单里的 Markdown 字段。',
      '只要展示代码用 CodeBlock。要补全或诊断用 CodeEditor。',
      '要所见即所得、公式或图表时不要用本组件。',
    ],
    whenToUseEn: [
      'Release notes, internal docs, and a Markdown field in a form.',
      'Use CodeBlock to show code. Use CodeEditor for completions or diagnostics.',
      'Do not use this for WYSIWYG, math, or diagrams.',
    ],
    demos: [
      { id: 'demo-edit', title: '编辑', titleEn: 'Edit' },
      { id: 'demo-split', title: '分栏', titleEn: 'Split' },
      { id: 'demo-readonly', title: '只读', titleEn: 'Read only' },
      { id: 'demo-locked', title: '隐藏切换', titleEn: 'Hidden toggle' },
      { id: 'demo-disabled', title: '禁用', titleEn: 'Disabled' },
      { id: 'demo-breaks', title: '换行', titleEn: 'Line breaks' },
      { id: 'demo-theme', title: '主题', titleEn: 'Theme' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      { name: 'modelValue', type: 'string', default: "''", defaultEn: "''", description: 'v-model。Markdown 源码。', descriptionEn: 'v-model. Markdown source.' },
      { name: 'mode', type: "'edit' | 'preview' | 'split'", default: "'edit'", defaultEn: "'edit'", description: 'v-model:mode。readonly 时强制 preview。', descriptionEn: 'v-model:mode. Forced to preview when readonly.' },
      { name: 'readonly', type: 'boolean', default: 'false', defaultEn: 'false', description: '强制预览并隐藏模式条。源码不可改。', descriptionEn: 'Forces preview and hides the mode bar. The source cannot be edited.' },
      { name: 'height', type: 'number | string', default: '16rem', defaultEn: '16rem', description: '根高度。数字按像素。', descriptionEn: 'Root height. A number is pixels.' },
      { name: 'placeholder', type: 'string', description: '编辑区占位。未传走 markdown.placeholder。', descriptionEn: 'Editor placeholder. Defaults to markdown.placeholder.' },
      { name: 'theme', type: "'auto' | 'light' | 'dark'", default: "'auto'", defaultEn: "'auto'", description: 'auto 跟页面；落在主题岛里时源码面跟岛。light / dark 写到根的 data-rs-theme，预览和源码一起变。', descriptionEn: 'auto follows the page. Inside a theme island the source follows the island. light or dark sets data-rs-theme on the root so preview and source match.' },
      { name: 'rounded', type: 'boolean', default: 'true', defaultEn: 'true', description: '外框圆角。', descriptionEn: 'Rounds the frame.' },
      { name: 'showModeToggle', type: 'boolean', default: 'true', defaultEn: 'true', description: '显示编辑 / 预览 / 分栏。readonly 或 disabled 时强制隐藏。', descriptionEn: 'Shows Edit / Preview / Split. Forced off when readonly or disabled.' },
      { name: 'breaks', type: 'boolean', default: 'true', defaultEn: 'true', description: '单个换行转 <br>。false 时按 CommonMark，单换行仍在同一段。', descriptionEn: 'Turns a single newline into <br>. When false, CommonMark keeps that newline in the same paragraph.' },
      { name: 'disabled', type: 'boolean', default: 'false', defaultEn: 'false', description: '禁用。隐藏模式条，源码不可改，focus() 无操作。', descriptionEn: 'Disabled. Hides the mode bar, blocks edits, and focus() does nothing.' },
      { name: 'ariaLabel', type: 'string', description: '区域名称。未传走 markdown.label。', descriptionEn: 'Region name. Defaults to markdown.label.' },
      { name: 'id', type: 'string', description: '根节点 id。未传时自动生成。', descriptionEn: 'Root id. Generated when omitted.' },
    ],
    events: [
      { name: 'update:modelValue', type: '[value: string]', description: 'v-model。编辑区击键时发出。只读、禁用和从外面写入不改源码。', descriptionEn: 'v-model. Emitted when the editor changes. Readonly, disabled, and external writes do not edit the source.' },
      { name: 'update:mode', type: "['edit' | 'preview' | 'split']", description: 'v-model:mode。点模式条或方向键 / Home / End 时发出。readonly 与 disabled 不发。', descriptionEn: 'v-model:mode. Emitted from the mode bar or Arrow / Home / End. Not emitted when readonly or disabled.' },
    ],
    slots: [
      { name: 'none', type: '—', description: '没有插槽。文档就是 v-model。', descriptionEn: 'No slots. The document is v-model.' },
    ],
    methods: [
      { name: 'focus', type: '() => void', description: '宿主调用。编辑或分栏时聚焦源码；预览时聚焦预览面。禁用或编辑器未就绪时无操作。', descriptionEn: 'Host call. Focuses the source in edit or split, and the preview surface in preview. No-op when disabled or the editor is not ready.' },
    ],
    tokens: [
      { name: '--rs-markdown-bg / --rs-markdown-fg / --rs-markdown-muted / --rs-markdown-border', default: 'surface / text / muted / border', description: '预览与外框。随 data-rs-theme。', descriptionEn: 'Preview and frame. Follow data-rs-theme.' },
      { name: '--rs-markdown-accent', default: 'var(--rs-primary)', description: '链接与已完成任务。', descriptionEn: 'Links and a completed task.' },
      { name: '--rs-markdown-radius', default: 'var(--rs-radius)', description: '外框、代码块和图片圆角。rounded 为 false 时不套到外框。', descriptionEn: 'Frame, code block, and image radius. The frame stays square when rounded is false.' },
      { name: '--rs-markdown-bar-bg', default: '表面与描边混合', description: '模式条背景。', descriptionEn: 'Mode bar background.' },
      { name: '--rs-markdown-code-bg / --rs-markdown-code-frame', default: '表面与描边混合', description: '行内代码底和代码块外框。', descriptionEn: 'Inline code background and fenced-code frame.' },
      { name: '--rs-markdown-th-bg', default: '描边 40% 混合', description: '表头底色。', descriptionEn: 'Header cell background.' },
      { name: '--rs-markdown-measure', default: '48rem', description: '预览正文最大宽度。', descriptionEn: 'Max preview measure.' },
      { name: '--rs-markdown-disabled-opacity', default: '0.65', description: '禁用时的不透明度。', descriptionEn: 'Opacity while disabled.' },
    ],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。根是带名称的 section，模式条是 tablist，源码面是 CodeEditor。业务与文档站不要 import reka-ui。v-model、mode、readonly 和 breaks 语义与原来相同。', qEn: 'Do I still need reka-ui?', aEn: 'No. The root is a named section, the mode bar is a tablist, and the source is CodeEditor. Apps and the docs site must not import reka-ui. v-model, mode, readonly, and breaks behave as before.' },
      { q: '和 CodeBlock、CodeEditor、ProseEditor 怎么选？', a: '整篇 Markdown 用本组件。只展示一段代码用 CodeBlock。要补全、悬停、诊断用 CodeEditor。要所见即所得用 ProseEditor。', qEn: 'How do I choose among CodeBlock, CodeEditor, and ProseEditor?', aEn: 'Use this for a Markdown document. Use CodeBlock for one snippet, CodeEditor for completion and diagnostics, and ProseEditor for WYSIWYG.' },
      { q: '预览会不会执行脚本？', a: '不会。javascript:、控制字符和协议相对地址会被拿掉。图片只留 http(s)、站内路径和 png/jpeg/gif/webp/avif/bmp 的 data URL，SVG data URL 丢掉。消毒还禁止 input、form 和 button。无 window 时返回空字符串。', qEn: 'Can the preview run a script?', aEn: 'No. javascript:, control characters, and protocol-relative URLs are removed. Images keep http(s), same-site paths, and png/jpeg/gif/webp/avif/bmp data URLs. SVG data URLs are dropped. Sanitizing also forbids input, form, and button. With no window the result is an empty string.' },
      { q: '外链为什么开新标签，锚点却不？', a: 'http(s)、mailto 和 tel 带 target=_blank 与 noopener。#、站内路径和相对路径留在当前页。读屏会在外链后听到「在新标签页打开」。', qEn: 'Why do external links open a new tab, but anchors do not?', aEn: 'http(s), mailto, and tel use target=_blank and noopener. Hash, site paths, and relative paths stay on the page. Assistive tech hears “opens in a new tab” after an external link.' },
      { q: '主题岛里左右两边颜色不一致？', a: '预览跟 CSS 变量，会继承最近的 data-rs-theme。theme=auto 时，若组件落在非页面根的主题岛里，源码面跟那一岛；否则交给 CodeEditor 的 auto（看 documentElement）。显式 light / dark 写在根上，两边一起变。', qEn: 'Why do the two panes disagree inside a theme island?', aEn: 'The preview follows CSS variables and inherits the nearest data-rs-theme. With theme=auto, a source inside an island that is not the document element follows that island; otherwise CodeEditor auto reads documentElement. An explicit light or dark is written on the root so both panes match.' },
      { q: 'RTL 会把代码翻过去吗？', a: '不会。源码面和预览里的代码块固定 dir=ltr。正文 dir=auto。模式条的左右键在 RTL 下对调。间距用逻辑属性。', qEn: 'Does an RTL page reverse the code?', aEn: 'No. The source and preview code blocks are dir=ltr. Prose is dir=auto. Arrow keys on the mode bar swap under RTL. Spacing uses logical properties.' },
      { q: '大文档会不会卡住，卸载后还占着定时器？', a: '编辑模式不解析。预览和分栏在击键后约 32ms 合并解析一次，切模式立即解析。定时器在卸载和停用时清掉。主题岛上的 MutationObserver 在卸载、停用时断开；页面根的明暗仍由 CodeEditor 的共享观察器负责。Marked 只缓存 breaks 的两份实例。', qEn: 'Will a large document block the page, and does unmount leave a timer?', aEn: 'Edit mode does not parse. Preview and split coalesce keystrokes at about 32ms; changing mode parses immediately. The timer is cleared on unmount and deactivate. A MutationObserver on a theme island disconnects on unmount and deactivate. Document theme stays with CodeEditor’s shared observer. Marked caches only the two breaks instances.' },
      { q: '预览里的代码为什么没有语法色？', a: '围栏代码只转义显示，并标语言名，避免每个代码块再挂一个编辑器。着色在源码面（CodeEditor）或只读片段（CodeBlock）。', qEn: 'Why is preview code not syntax-colored?', aEn: 'Fenced code is escaped and labeled. A highlighter per block would mount another editor. Coloring stays on the source (CodeEditor) or on CodeBlock.' },
      { q: '能排公式或 Mermaid 吗？', a: '不能。那会扩大包体和 XSS 面。公式和图表请在产品层单独渲染，不要关消毒把 HTML 塞进来。', qEn: 'Can it render math or Mermaid?', aEn: 'No. That would grow the bundle and the XSS surface. Render math and diagrams in the product. Do not turn sanitizing off to inject HTML.' },
    ],
    related: ['code-block', 'code-editor'],
  },
  {
    slug: 'log',
    name: 'RsLog',
    title: 'Log',
    titleZh: '日志',
    group: 'editor',
    summary: '作业 / 发版日志，不是终端。',
    description:
      '只读日志。根是原生区域，不包 Reka；长列表走 RsVirtualList。单行虚拟滚动，折行改普通列表。级别对齐 RFC 5424 / OpenTelemetry，另有 UI 档 success。内置只认方括号、行首级别词和工具链行首。展示会去掉 ANSI，源文本仍留在 getLines().text。交互式 shell 用 Terminal。',
    descriptionEn:
      'Read-only log. The root is a native region — no Reka; long lists use RsVirtualList. Single-line mode virtualizes; wrap uses a plain list. Levels follow RFC 5424 / OpenTelemetry, plus a UI success tone. Built-in inference only reads bracket tags, a leading level word, and toolchain line starts. ANSI is stripped for display; getLines().text keeps the source. Use Terminal for an interactive shell.',
    whenToUse: [
      'CI、发版、作业的只读输出，要搜索、级别和跟底。',
      '一行可能很长、需要折行撑满时打开 wrap。虚拟列表没有变高。',
      '要 PTY、光标和 ANSI 上色用 Terminal。短代码片段用 CodeBlock。',
    ],
    whenToUseEn: [
      'Read-only CI, release, or job output that needs search, levels, and tailing.',
      'Turn on wrap when a line must fill the column. The virtual list does not do variable heights.',
      'Use Terminal for a PTY, a caret, and ANSI colors. Use CodeBlock for a short snippet.',
    ],
    demos: [
      { id: 'demo-basic', title: '结构化行', titleEn: 'Structured lines' },
      { id: 'demo-infer', title: '从正文推断', titleEn: 'Infer from text' },
      { id: 'demo-search', title: '搜索与过滤', titleEn: 'Search and filter' },
      { id: 'demo-follow', title: '跟底', titleEn: 'Follow' },
      { id: 'demo-wrap', title: '折行', titleEn: 'Wrap' },
      { id: 'demo-overflow', title: '保留最新', titleEn: 'Keep the tail' },
      { id: 'demo-ansi', title: 'ANSI', titleEn: 'ANSI' },
      { id: 'demo-slot', title: '自定义行', titleEn: 'Custom row' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
      { id: 'demo-empty', title: '空态', titleEn: 'Empty' },
      { id: 'demo-direction', title: '书写方向', titleEn: 'Direction' },
      { id: 'demo-theme', title: '深色岛', titleEn: 'Dark island' },
    ],
    props: [
      { name: 'v-model:lines', type: 'string | RsLogLineInput[]', default: "''", defaultEn: "''", description: '日志源。字符串按行拆。空字符串时改读 text。', descriptionEn: 'Log source. A string is split into lines. An empty string falls through to text.' },
      { name: 'v-model:search', type: 'string', default: "''", defaultEn: "''", description: '过滤正文。大小写按当前 locale 折叠。Enter / Shift+Enter 在匹配行之间移动。', descriptionEn: 'Filters the visible text. Case folds with the active locale. Enter / Shift+Enter moves between matches.' },
      { name: 'v-model:levels', type: 'RsLogLevel[]', default: '[]', defaultEn: '[]', description: '只显示这些级别。空数组表示不过滤。配合 show-filter。', descriptionEn: 'Show only these levels. An empty array does not filter. Pair with show-filter.' },
      { name: 'text', type: 'string', description: 'lines 为空字符串时的只读源。', descriptionEn: 'Read-only source used when lines is an empty string.' },
      { name: 'height', type: 'number | string', default: '280', defaultEn: '280', description: '外框高度。数字按 px。', descriptionEn: 'Frame height. A number is px.' },
      { name: 'itemSize', type: 'number', default: '0', defaultEn: '0', description: '虚拟行高。0 时单行 24、折行 48。', descriptionEn: 'Virtual row size. 0 uses 24 for a single line and 48 when wrapping.' },
      { name: 'overscan', type: 'number', default: '8', defaultEn: '8', description: '可视区两侧多渲染的行数。', descriptionEn: 'Extra rows rendered on each side of the viewport.' },
      { name: 'follow', type: 'boolean', default: 'true', defaultEn: 'true', description: '贴底时新行自动滚到底。用户上滚或框选正文后停下，并出现回到最新。', descriptionEn: 'When stuck to the end, new lines scroll to the bottom. Scrolling up or selecting text pauses follow and shows Jump to latest.' },
      { name: 'wrap', type: 'boolean', default: 'false', defaultEn: 'false', description: '折行。virtual 为 auto 时关闭虚拟滚动。', descriptionEn: 'Wrap lines. When virtual is auto, virtualization turns off.' },
      { name: 'showTime', type: 'boolean', default: 'false', defaultEn: 'false', description: '显示时间列。能解析的瞬间按 locale 与 timeFormat 格式化。', descriptionEn: 'Show the time column. Instants format with locale and timeFormat.' },
      { name: 'showLevel', type: 'boolean', default: 'true', defaultEn: 'true', description: '显示级别名。关掉后仍有色条，名称进读屏。', descriptionEn: 'Show the level name. When off, the color bar remains and the name stays for screen readers.' },
      { name: 'inferLevel', type: 'boolean', default: 'true', defaultEn: 'true', description: '行上没有 level / severity 时扫描正文。', descriptionEn: 'Scan the text when a line has no level or severity.' },
      { name: 'inferMarkers', type: 'RsLogInferMarkers', description: '内置扫描之后的产品标识。拉丁词按词边界，中日韩按子串。多条命中取更严重档。', descriptionEn: 'Product markers applied after the built-in scan. Latin tokens use word boundaries; CJK uses a substring. Several hits keep the more severe level.' },
      { name: 'maxLines', type: 'number', description: '只保留最新的这么多行。超出时发 overflow。', descriptionEn: 'Keep only this many newest lines. Emits overflow when older rows drop.' },
      { name: 'zebra', type: 'boolean', default: 'true', defaultEn: 'true', description: '隔行底纹。', descriptionEn: 'Stripe alternate rows.' },
      { name: 'emptyText', type: 'string', description: '没有可见行时的说明。不传走 log.empty。', descriptionEn: 'Copy when nothing is visible. Defaults to log.empty.' },
      { name: 'radius', type: "'none' | 'xs' | 'sm' | 'md' | 'lg' | 'full'", description: '外框圆角。不传跟 ConfigProvider，默认 sm。', descriptionEn: 'Frame radius. Falls through to ConfigProvider, then sm.' },
      { name: 'ariaLabel', type: 'string', description: '日志区名称。不传走 log.label。', descriptionEn: 'Accessible name of the log region. Defaults to log.label.' },
      { name: 'live', type: "boolean | 'off' | 'polite' | 'assertive'", default: "'off'", defaultEn: "'off'", description: '新行是否进 aria-live。默认关，避免虚拟回收刷读屏。true 视为 polite。', descriptionEn: 'Whether new lines go to aria-live. Off by default so virtual recycling does not spam screen readers. true means polite.' },
      { name: 'busy', type: 'boolean', default: 'false', defaultEn: 'false', description: '为真时日志区 aria-busy。', descriptionEn: 'Sets aria-busy on the log region.' },
      { name: 'showSearch', type: 'boolean', default: 'true', defaultEn: 'true', description: '搜索框。Ctrl/⌘+F 聚焦。', descriptionEn: 'Search field. Ctrl/⌘+F focuses it.' },
      { name: 'showCopy', type: 'boolean', default: 'true', defaultEn: 'true', description: '复制按钮。复制可见正文（ANSI 已去掉）。有选区时只复制选区。', descriptionEn: 'Copy button. Copies the visible text (ANSI stripped). A selection copies only that selection.' },
      { name: 'showFilter', type: 'boolean', default: 'false', defaultEn: 'false', description: '级别筛选条，写入 v-model:levels。', descriptionEn: 'Level chips. Writes v-model:levels.' },
      { name: 'showLineNo', type: 'boolean', default: 'false', defaultEn: 'false', description: '裁剪后的行号。不可选中，避免复制进正文。', descriptionEn: 'Line number after trimming. Not selectable, so it stays out of a copy.' },
      { name: 'virtual', type: "boolean | 'auto'", default: "'auto'", defaultEn: "'auto'", description: 'auto：折行关虚拟，单行开虚拟。', descriptionEn: 'auto turns virtualization off when wrap is on, and on for single-line rows.' },
      { name: 'dir', type: "'ltr' | 'rtl' | 'auto'", default: "'ltr'", defaultEn: "'ltr'", description: '日志正文的书写方向。工具条跟页面。默认 ltr，避免列号被翻过去。', descriptionEn: 'Writing direction of the log body. The toolbar follows the page. Defaults to ltr so line numbers stay put.' },
      { name: 'severityScale', type: "'syslog' | 'otel' | 'auto'", default: "'auto'", defaultEn: "'auto'", description: '数字严重级别怎么读。auto：0–7 当 syslog，更大当 OTel。', descriptionEn: 'How a numeric severity is read. auto treats 0–7 as syslog and larger numbers as OpenTelemetry.' },
      { name: 'timeFormat', type: 'Intl.DateTimeFormatOptions', description: '瞬间的展示格式，含 timeZone。已是展示串的 time 原样保留。', descriptionEn: 'Format for instants, including timeZone. A time that is already a display string is kept.' },
      { name: 'id', type: 'string', description: '根节点 id。', descriptionEn: 'Root id.' },
    ],
    events: [
      { name: 'update:lines', type: '[value: string | RsLogLineInput[]]', description: 'v-model:lines。append / clear 会写回。', descriptionEn: 'v-model:lines. append and clear write it.' },
      { name: 'update:search', type: '[value: string]', description: 'v-model:search。', descriptionEn: 'v-model:search.' },
      { name: 'update:levels', type: '[value: RsLogLevel[]]', description: 'v-model:levels。点级别筛选时发出。', descriptionEn: 'v-model:levels. Emitted when a level chip toggles.' },
      { name: 'followChange', type: '[following: boolean]', description: '贴底状态变化。上滚或框选为 false，回到底部为 true。', descriptionEn: 'Tail state. false after scrolling up or selecting text, true when stuck to the end again.' },
      { name: 'overflow', type: '[{ dropped: number, kept: number }]', description: 'maxLines 丢掉了更早的行。dropped 只增不减时发出。', descriptionEn: 'maxLines dropped older lines. Emitted when dropped increases.' },
      { name: 'copy', type: '[{ text: string, source: RsLogCopySource }]', description: '复制成功。source 为 selection、all、line 或 visible。失败不发。', descriptionEn: 'Copy succeeded. source is selection, all, line, or visible. A failure does not emit.' },
    ],
    slots: [
      { name: 'toolbar', type: '—', description: '替换搜索、筛选和复制。不传且三者都关时不留工具条。', descriptionEn: 'Replaces search, filters, and copy. Omitted, and with all three off, there is no toolbar.' },
      { name: 'empty', type: '—', description: '没有可见行。不传时用 RsEmpty 和 emptyText / log.empty。', descriptionEn: 'Shown when no row is visible. Defaults to RsEmpty with emptyText or log.empty.' },
      { name: 'row', type: '{ item: RsNormalizedLogLine, index: number, levelLabel: string, parts: RsLogHighlightPart[] }', description: '自定义一行。parts 是搜索高亮片段。不传时渲染 plain。', descriptionEn: 'Custom row. parts are the search-highlight slices. Defaults to plain.' },
    ],
    methods: [
      { name: 'append', type: '(input: string | RsLogLineInput | RsLogLineInput[]) => void', description: '宿主调用。追加到 v-model:lines。字符串模型拼成文本，数组模型保留对象。', descriptionEn: 'Host call. Appends to v-model:lines. A string model is joined as text; an array model keeps objects.' },
      { name: 'clear', type: '() => void', description: '宿主调用。字符串模型写成空串，数组模型写成 []。', descriptionEn: 'Host call. Writes an empty string or [] to match the current model.' },
      { name: 'scrollToBottom', type: '() => void', description: '宿主调用。滚到最后一行并重新跟底。', descriptionEn: 'Host call. Scrolls to the last row and resumes follow.' },
      { name: 'scrollToTop', type: '() => void', description: '宿主调用。滚到第一行并取消跟底。', descriptionEn: 'Host call. Scrolls to the first row and pauses follow.' },
      { name: 'copy', type: '() => Promise<boolean>', description: '宿主调用。选区优先，否则复制全部可见正文。成功 true。', descriptionEn: 'Host call. Selection wins; otherwise copies all visible text. Resolves true on success.' },
      { name: 'copyAll', type: '() => Promise<boolean>', description: '宿主调用。忽略选区和过滤，复制全部可见正文。', descriptionEn: 'Host call. Copies every visible line, ignoring the selection and the filter.' },
      { name: 'getLines', type: '() => RsNormalizedLogLine[]', description: '宿主调用。归一化后的全部行，含 text（源）和 plain（去 ANSI）。', descriptionEn: 'Host call. Every normalized line, including text (source) and plain (ANSI stripped).' },
      { name: 'getVisibleLines', type: '() => RsNormalizedLogLine[]', description: '宿主调用。搜索和级别过滤之后的行。', descriptionEn: 'Host call. Rows after search and level filters.' },
      { name: 'focus', type: '() => void', description: '宿主调用。聚焦日志区，方向键可漫游。', descriptionEn: 'Host call. Focuses the log region so arrow keys can move.' },
      { name: 'focusSearch', type: '() => void', description: '宿主调用。聚焦搜索框并选中已有关键字。', descriptionEn: 'Host call. Focuses the search field and selects the current query.' },
    ],
    tokens: [
      { name: '--rs-log-bg / --rs-log-fg / --rs-log-border / --rs-log-muted', default: 'theme', description: '表面、文字、边框、次要文字。随 data-rs-theme。', descriptionEn: 'Surface, text, border, and muted text. Follow data-rs-theme.' },
      { name: '--rs-log-trace / --rs-log-debug / --rs-log-info / --rs-log-notice / --rs-log-success / --rs-log-warn / --rs-log-error / --rs-log-fatal', default: 'theme', description: '级别色。色条与级别名同时存在，不只靠颜色。', descriptionEn: 'Level colors. The bar and the name are both present, so color is not the only cue.' },
      { name: '--rs-log-stripe / --rs-log-hit-bg / --rs-log-hit-fg', default: 'theme', description: '隔行底纹和搜索命中。', descriptionEn: 'Zebra stripe and search hit.' },
      { name: '--rs-log-accent / --rs-log-accent-width / --rs-log-active-bg', default: 'primary / 0.125rem / mix', description: '当前行色条在逻辑起点，RTL 跟正文方向。', descriptionEn: 'Active bar on the logical start edge, so it follows the log direction.' },
      { name: '--rs-log-chrome-bg / --rs-log-chip-on-bg / --rs-log-chip-on-border', default: 'mix', description: '工具条和选中的级别筛选。', descriptionEn: 'Toolbar and the selected level chip.' },
      { name: '--rs-log-font-family / --rs-log-font-size / --rs-log-line-height', default: 'mono / xs / 1.45', description: '日志字体。行高与默认 24px 行对齐。', descriptionEn: 'Log font. Line height lines up with the default 24px row.' },
      { name: '--rs-log-radius', default: 'runtime', description: '由 radius 写入，对应 --rs-radius-*。', descriptionEn: 'Written from radius, mapped to --rs-radius-*.' },
      { name: '--rs-focus-ring-width / --rs-focus-border', default: 'theme', description: '日志区和级别筛选的焦点环。', descriptionEn: 'Focus ring on the log region and level chips.' },
    ],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。根是原生区域，行是普通 div，长列表用本库的虚拟列表。业务与文档站不要 import reka-ui。lines、搜索、复制和 append 语义与原来相同。', qEn: 'Do I still need reka-ui?', aEn: 'No. The root is a native region, a row is a div, and long lists use this library’s virtual list. Apps and the docs site must not import reka-ui. lines, search, copy, and append behave as before.' },
      { q: '和 Terminal、CodeBlock 怎么选？', a: '只读、要级别和搜索用这里。要键盘输入和 PTY 用 Terminal。几十行代码用 CodeBlock。', qEn: 'When should I use Terminal or CodeBlock instead?', aEn: 'Use this for a read-only stream with levels and search. Use Terminal for keyboard input and a PTY. Use CodeBlock for a few dozen lines of code.' },
      { q: 'ANSI 颜色还在吗？', a: '展示、搜索、复制和级别推断用去掉转义后的正文。getLines()[i].text 仍是源文本。上色是终端的事。', qEn: 'Are ANSI colors kept?', aEn: 'Display, search, copy, and level inference use the stripped text. getLines()[i].text is still the source. Coloring belongs to the terminal.' },
      { q: '为什么默认不播报新行？', a: '虚拟列表会回收节点。live 默认 off。需要听新增时设 polite，同一句会交替一个不可见字符，避免读屏把重复句丢掉。', qEn: 'Why are new lines silent?', aEn: 'A virtual list recycles nodes. live defaults to off. Set polite to hear arrivals. A repeated sentence alternates an invisible character so assistive tech does not drop it.' },
      { q: '阿拉伯语页面会把日志翻过去吗？', a: '工具条跟页面方向。日志正文默认 dir=ltr，行号和时间用 isolate。把 dir 设成 rtl 时，当前行色条改到逻辑起点。', qEn: 'Does an Arabic page reverse the log?', aEn: 'The toolbar follows the page. The log body defaults to dir=ltr, and line numbers and times are isolated. Set dir to rtl and the active bar moves to the logical start.' },
      { q: '卸载后还会不会留着定时器？', a: '复制结果的定时器在卸载时清掉。剪贴板如果在卸载之后才返回，不再排新的定时器。没有 window 监听，也没有 ResizeObserver。', qEn: 'Does unmount leave a timer?', aEn: 'The copy-status timer is cleared on unmount. If the clipboard resolves after that, no new timer is scheduled. There is no window listener and no ResizeObserver.' },
    ],
    related: ['terminal', 'virtual-list', 'code-block'],
  },
  {
    slug: 'terminal',
    name: 'RsTerminal',
    title: 'Terminal',
    titleZh: '终端',
    group: 'editor',
    summary: '基于 xterm 的 PTY 面板。',
    description:
      '交互式终端。根是原生 section，右键用本库 RsContextMenu，不包 Reka。键盘输入经 data 交给宿主的 PTY / WebSocket，输出用 write()。只读日志用 RsLog。宿主必须给一个高度。',
    descriptionEn:
      'Interactive terminal. The root is a native section and the context menu is this library’s RsContextMenu — no Reka. Keystrokes go out through data to the host PTY or WebSocket; output comes back through write(). Use RsLog for a read-only log. The host must supply a height.',
    whenToUse: [
      'SSH、本地 shell、容器 exec，需要键盘和 PTY。',
      '只看日志、要级别和搜索时用 RsLog。几十行代码用 CodeBlock。',
      '宿主负责连接、重连和尺寸：把 data 写进通道，把通道字节 write() 回来，resize 时通知 PTY。',
    ],
    whenToUseEn: [
      'SSH, a local shell, or container exec when you need a keyboard and a PTY.',
      'Use RsLog for a read-only stream with levels and search. Use CodeBlock for a few dozen lines of code.',
      'The host owns the connection. Send data into the channel, write() bytes back, and tell the PTY about resize.',
    ],
    demos: [
      { id: 'demo-basic', title: '回显', titleEn: 'Echo' },
      { id: 'demo-readonly', title: '只读', titleEn: 'Read only' },
      { id: 'demo-overlay', title: '遮罩', titleEn: 'Overlay' },
      { id: 'demo-search', title: '搜索', titleEn: 'Search' },
      { id: 'demo-menu', title: '右键', titleEn: 'Context menu' },
      { id: 'demo-session', title: '标题、响铃与链接', titleEn: 'Title, bell, and links' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
      { id: 'demo-theme', title: '主题岛', titleEn: 'Theme island' },
      { id: 'demo-direction', title: '书写方向', titleEn: 'Direction' },
    ],
    props: [
      { name: 'loading', type: 'boolean', default: 'false', defaultEn: 'false', description: '盖住画面的加载层。首次 fit 完成前也会显示。', descriptionEn: 'Covers the surface. Also shown until the first fit finishes.' },
      { name: 'overlay', type: 'string', default: "''", defaultEn: "''", description: '遮罩文案。没有 overlayAction 时挡住点击。', descriptionEn: 'Overlay text. Blocks pointer events unless overlayAction is set.' },
      { name: 'inputEnabled', type: 'boolean', default: 'true', defaultEn: 'true', description: '关闭后不再发 data，粘贴被禁用，stdin 关掉。仍可滚动和复制。', descriptionEn: 'When false, data is not emitted, paste is disabled, and stdin is off. Scroll and copy still work.' },
      { name: 'cursorBlink', type: 'boolean', default: 'true', defaultEn: 'true', description: '光标闪烁。系统开启减少动态时不闪。', descriptionEn: 'Cursor blink. Stays steady when the OS asks for reduced motion.' },
      { name: 'cursorStyle', type: "'block' | 'underline' | 'bar'", default: "'block'", defaultEn: "'block'", description: '光标形状。', descriptionEn: 'Cursor shape.' },
      { name: 'fontFamily', type: 'string', description: '缺省读 --rs-terminal-font-family / --rs-font-mono。', descriptionEn: 'Defaults to --rs-terminal-font-family / --rs-font-mono.' },
      { name: 'fontSize', type: 'number', description: '缺省读 --rs-terminal-font-size。', descriptionEn: 'Defaults to --rs-terminal-font-size.' },
      { name: 'fontWeight', type: "'normal' | 'bold' | '100'–'900'", description: '缺省读 --rs-terminal-font-weight。', descriptionEn: 'Defaults to --rs-terminal-font-weight.' },
      { name: 'fontWeightBold', type: "'normal' | 'bold' | '100'–'900'", description: '粗体字重。缺省读 --rs-terminal-font-weight-bold。', descriptionEn: 'Bold weight. Defaults to --rs-terminal-font-weight-bold.' },
      { name: 'allowTransparency', type: 'boolean', default: 'false', defaultEn: 'false', description: '单元格背景可透明。斑马纹打开时也会打开。', descriptionEn: 'Allows transparent cell backgrounds. Also turned on with zebra stripes.' },
      { name: 'themeMode', type: "'auto' | 'light' | 'dark'", default: "'auto'", defaultEn: "'auto'", description: 'auto 跟最近的 data-rs-theme。未写时跟浅色。', descriptionEn: 'auto follows the nearest data-rs-theme. Unset means light.' },
      { name: 'theme', type: 'Partial<ITheme>', default: '{}', defaultEn: '{}', description: '盖住调色板里的若干项。色值须是 xterm 能解析的颜色。', descriptionEn: 'Overrides palette keys. Values must be colors xterm can parse.' },
      { name: 'contextMenu', type: 'boolean', default: 'true', defaultEn: 'true', description: '关闭后右键走浏览器菜单。', descriptionEn: 'When false, the browser context menu is left alone.' },
      { name: 'showAskAi', type: 'boolean', default: 'false', defaultEn: 'false', description: '右键多一项「询问 AI」，只发 askAi，不调用模型。', descriptionEn: 'Adds Ask AI to the menu. It only emits askAi. No model is called.' },
      { name: 'extraContextMenuItems', type: 'RsContextMenuItem[]', default: '[]', defaultEn: '[]', description: '插在内置项和「清空」之间。key 勿与 copy / paste / selectAll / search / askAi / clear 冲突。', descriptionEn: 'Inserted between the built-in items and Clear. Do not reuse copy, paste, selectAll, search, askAi, or clear.' },
      { name: 'rightClickSelectsWord', type: 'boolean', default: 'true', defaultEn: 'true', description: '没有选区时，右键选中光标下的词。已经滚选的大段文本不会被缩成一个词。vim / less 里建议关掉。', descriptionEn: 'With no selection, right-click selects the word under the cursor. An existing drag selection is left intact. Turn this off in vim or less.' },
      { name: 'shortcuts', type: 'boolean', default: 'true', defaultEn: 'true', description: 'Ctrl/⌘+C 复制、V 粘贴、A 全选、K 清空、F 搜索（搜索需 searchEnabled）。', descriptionEn: 'Ctrl/⌘+C copy, V paste, A select all, K clear, F search (search requires searchEnabled).' },
      { name: 'scrollback', type: 'number', default: '5000', defaultEn: '5000', description: '回滚行数。', descriptionEn: 'Scrollback rows.' },
      { name: 'convertEol', type: 'boolean', default: 'false', defaultEn: 'false', description: '把单独的换行符当成回车换行。PTY 建议保持 false，以免打乱 top / vim。', descriptionEn: 'Treats a lone line feed as a newline. Keep false for a PTY so top and vim stay intact.' },
      { name: 'zebraStripes', type: 'boolean', default: 'true', defaultEn: 'true', description: '奇数行底纹。', descriptionEn: 'Stripe odd rows.' },
      { name: 'wheelScrollModifier', type: "'none' | 'shift'", default: "'none'", defaultEn: "'none'", description: 'none：滚轮翻历史。shift：只在 vim/top 备用屏把滚轮转成方向键。', descriptionEn: 'none scrolls history. shift turns the wheel into arrow keys only on the alternate screen (vim, top).' },
      { name: 'snapViewportOnTuiWrite', type: 'boolean', default: 'true', defaultEn: 'true', description: '全屏清屏或进入备用屏时把视口拉回底部。普通的光标归位不拽回用户翻过的历史。', descriptionEn: 'Snaps the viewport to the bottom on a full clear or alternate-screen enter. A plain cursor-home does not yank scrollback.' },
      { name: 'copyOnSelect', type: 'boolean', default: 'false', defaultEn: 'false', description: '鼠标松开且有选区时复制。', descriptionEn: 'Copies when the pointer is released over a selection.' },
      { name: 'searchEnabled', type: 'boolean', default: 'false', defaultEn: 'false', description: '打开后才加载搜索插件。Ctrl/⌘+F 或右键「搜索」。', descriptionEn: 'Loads the search addon only when on. Ctrl/⌘+F or the Search menu item.' },
      { name: 'screenReaderMode', type: 'boolean', default: 'false', defaultEn: 'false', description: '交给 xterm 的读屏模式。默认关，避免每次移动光标都改 DOM。', descriptionEn: 'xterm screen-reader mode. Off by default so cursor moves do not rewrite the DOM.' },
      { name: 'openLinks', type: 'boolean', default: 'true', defaultEn: 'true', description: '点击 http(s) / mailto 时新开标签。false 时只发 link。javascript: 与 data: 不打开也不发事件。', descriptionEn: 'Opens http(s) and mailto in a new tab. false only emits link. javascript: and data: are ignored.' },
      { name: 'rescaleOverlappingGlyphs', type: 'boolean', default: 'true', defaultEn: 'true', description: '把超宽的单格字形缩进格子，便于 GB18030 歧义宽度。DOM 渲染器下无效。', descriptionEn: 'Scales overlapping single-cell glyphs into the cell for GB18030 ambiguous width. No effect on the DOM renderer.' },
      { name: 'minimumContrastRatio', type: 'number', default: '4.5', defaultEn: '4.5', description: '前景相对背景的最低对比度。传 1 关闭。浅色主题下 ls 软链接靠它才看得清。', descriptionEn: 'Minimum contrast of foreground against background. Pass 1 to disable. Keeps ls symlinks readable on a light theme.' },
      { name: 'ariaLabel', type: 'string', description: '区域名称。未传走 terminal.label。', descriptionEn: 'Accessible name. Defaults to terminal.label.' },
      { name: 'id', type: 'string', description: '根节点 id。', descriptionEn: 'Root id.' },
    ],
    events: [
      { name: 'ready', type: '[]', description: '首次 fit 之后。此时 getGeometry() 才有意义。', descriptionEn: 'After the first fit. getGeometry() is meaningful from here.' },
      { name: 'data', type: '[data: string]', description: '用户输入，含回车和方向键。inputEnabled 为 false 时不发。', descriptionEn: 'User input, including Enter and arrow keys. Not emitted when inputEnabled is false.' },
      { name: 'resize', type: '[{ cols: number, rows: number }]', description: '行列变化。把这对数字交给 PTY。', descriptionEn: 'Column and row changes. Forward the pair to the PTY.' },
      { name: 'action', type: '[action: RsTerminalAction]', description: '复制、粘贴、全选、清空、搜索或询问 AI 成功触发。复制失败不发。', descriptionEn: 'Copy, paste, select all, clear, search, or Ask AI ran. A failed copy does not emit.' },
      { name: 'askAi', type: '[text: string]', description: '右键「询问 AI」。文本是打开菜单时的选区快照。', descriptionEn: 'Ask AI from the menu. text is the selection captured when the menu opened.' },
      { name: 'selectionChange', type: '[text: string]', description: '选区变化。没有选区时是空串。', descriptionEn: 'Selection changed. An empty string means nothing is selected.' },
      { name: 'extraSelect', type: '[key: string]', description: '点了 extraContextMenuItems 里的一项。', descriptionEn: 'An extra context-menu item was chosen.' },
      { name: 'titleChange', type: '[title: string]', description: 'OSC 0 / 2 设置了标题。', descriptionEn: 'OSC 0 or 2 set the title.' },
      { name: 'bell', type: '[]', description: '收到 BEL。组件不发声。', descriptionEn: 'BEL arrived. The component does not play a sound.' },
      { name: 'link', type: '[url: string]', description: '点了 http(s) 或 mailto。不安全协议不发。', descriptionEn: 'An http(s) or mailto link was activated. Unsafe protocols do not emit.' },
    ],
    slots: [
      { name: 'overlayAction', type: '—', description: '遮罩上的操作，例如重连。有插槽时遮罩可以点击。', descriptionEn: 'Actions on the overlay, such as reconnect. The overlay accepts clicks when this slot is set.' },
    ],
    methods: [
      { name: 'write', type: '(data: string) => void', description: '宿主调用。把 PTY 字节写进画面。全屏清屏时会先把视口拉回底部。', descriptionEn: 'Host call. Writes PTY bytes. A full-screen clear snaps the viewport to the bottom first.' },
      { name: 'clear', type: '() => void', description: '宿主调用。清屏并取消选区。不发 action。', descriptionEn: 'Host call. Clears the screen and the selection. Does not emit action.' },
      { name: 'focus', type: '() => void', description: '宿主调用。聚焦终端。', descriptionEn: 'Host call. Focuses the terminal.' },
      { name: 'fit', type: '() => Promise<void>', description: '宿主调用。按容器重算行列。容器宽高为 0 时直接返回。', descriptionEn: 'Host call. Refits columns and rows to the box. Returns immediately when the box is 0×0.' },
      { name: 'copySelection', type: '() => Promise<void>', description: '宿主调用。复制选区。没有选区或剪贴板失败时不发 action。', descriptionEn: 'Host call. Copies the selection. No action event when there is no selection or the clipboard fails.' },
      { name: 'pasteFromClipboard', type: '() => Promise<void>', description: '宿主调用。把剪贴板贴进终端。inputEnabled 为 false 或读不到文本时不发 action。', descriptionEn: 'Host call. Pastes the clipboard. No action event when input is off or the clipboard is empty.' },
      { name: 'selectAll', type: '() => void', description: '宿主调用。全选并发 action。', descriptionEn: 'Host call. Selects everything and emits action.' },
      { name: 'getSelection', type: '() => string', description: '宿主调用。当前选中文本，没有时是空串。', descriptionEn: 'Host call. The current selection, or an empty string.' },
      { name: 'hasSelection', type: '() => boolean', description: '宿主调用。是否有选区。', descriptionEn: 'Host call. Whether a selection exists.' },
      { name: 'getGeometry', type: '() => RsTerminalGeometry | null', description: '宿主调用。当前行列。实例尚未创建时是 null。', descriptionEn: 'Host call. Current columns and rows. null before the instance exists.' },
      { name: 'getTerminal', type: '() => Terminal | null', description: '宿主调用。xterm 实例。优先用上面的方法；直接改 options 会和 props 打架。', descriptionEn: 'Host call. The xterm instance. Prefer the methods above. Writing options fights the props.' },
    ],
    tokens: [
      { name: '--rs-terminal-bg / --rs-terminal-fg / --rs-terminal-border', default: 'theme', description: '单元格、文字、边框。随最近的 data-rs-theme。', descriptionEn: 'Cells, text, and border. Follow the nearest data-rs-theme.' },
      { name: '--rs-terminal-shell-bg / --rs-terminal-cursor / --rs-terminal-cursor-accent', default: 'theme', description: '外壳和光标。', descriptionEn: 'Shell and cursor.' },
      { name: '--rs-terminal-selection-bg / --rs-terminal-selection-fg', default: 'theme', description: '选区。', descriptionEn: 'Selection.' },
      { name: '--rs-terminal-row-stripe', default: 'theme', description: '斑马纹。', descriptionEn: 'Zebra stripe.' },
      { name: '--rs-terminal-ansi-black … --rs-terminal-ansi-bright-white', default: 'theme', description: 'ANSI 16 色。浅色和深色各一套，保证浅底上的彩色字可读。', descriptionEn: 'ANSI 16. Separate light and dark ramps so colored text stays readable on a light background.' },
      { name: '--rs-terminal-font-family / --rs-terminal-font-size / --rs-terminal-font-weight / --rs-terminal-font-weight-bold', default: 'mono / sm / regular / medium', description: '未传 font* 时读这些。', descriptionEn: 'Read when font* props are omitted.' },
      { name: '--rs-shadow-sm / --rs-focus-ring-width / --rs-focus-border', default: 'theme', description: '外壳阴影和搜索框焦点环。', descriptionEn: 'Shell shadow and the search focus ring.' },
    ],
    faq: [
      { q: '还要装 reka-ui 吗？', a: '不包。根是原生 section，右键是本库菜单。业务与文档站不要 import reka-ui。data、write、resize 和右键项语义与原来相同。', qEn: 'Do I still need reka-ui?', aEn: 'No. The root is a native section and the menu is this library’s. Apps and the docs site must not import reka-ui. data, write, resize, and menu items behave as before.' },
      { q: '能直接当日志看吗？', a: '不要。没有级别、虚拟行和跟底。作业日志用 RsLog。', qEn: 'Can I use it as a log viewer?', aEn: 'No. It has no levels, virtual rows, or follow-tail. Use RsLog for job output.' },
      { q: '深色卡片里的终端会不会还是浅色？', a: '不会。auto 读最近的 data-rs-theme，颜色从宿主元素继承的 token 来。多个终端共用一个观察器，最后一个卸载才断开。', qEn: 'Does a terminal inside a dark card stay light?', aEn: 'No. auto reads the nearest data-rs-theme and the tokens inherited by the host. Instances share one observer, disconnected when the last one unmounts.' },
      { q: '链接安全吗？', a: '只打开 http、https 和 mailto，并带 noopener。javascript: 和 data: 忽略。把 openLinks 设为 false 后只发 link，由你决定。', qEn: 'Are links safe?', aEn: 'Only http, https, and mailto open, with noopener. javascript: and data: are ignored. Set openLinks to false to handle the link event yourself.' },
      { q: '阿拉伯语页面会把终端翻过去吗？', a: '不会。画面 dir=ltr，列从左往右。Mac 上 Option 仍用来输入字符，不当成 Meta。', qEn: 'Does an Arabic page reverse the terminal?', aEn: 'No. The surface is dir=ltr, so columns run left to right. On a Mac, Option still types characters and is not treated as Meta.' },
      { q: '卸载后还会不会留着观察器？', a: '不会。卸载会丢掉主题订阅、ResizeObserver、滚轮监听、减少动态监听、xterm 的数据和选区订阅，并 dispose 实例。若卸载发生在首次 fit 的等待期间，之后不再挂观察器。', qEn: 'Does unmount leave an observer?', aEn: 'No. Unmount drops the theme subscription, ResizeObserver, wheel listener, reduced-motion listener, and the xterm data and selection subscriptions, then disposes the instance. If unmount happens while the first fit is still waiting, no observer is attached afterwards.' },
      { q: '为什么默认不开读屏模式？', a: 'xterm 的 screenReaderMode 会为光标移动改 DOM，长会话很吵。区域本身有名字。需要 NVDA 跟随时再开。', qEn: 'Why is screen-reader mode off?', aEn: 'xterm’s screenReaderMode rewrites the DOM as the cursor moves, which is noisy for a long session. The region already has a name. Turn it on when NVDA should follow the cursor.' },
    ],
    related: ['log', 'code-block', 'context-menu'],
  },
]
