import type { ComponentDoc } from '../types'

export const feedbackComponents: ComponentDoc[] = [
  {
    slug: 'alert',
    name: 'RsAlert',
    title: 'Alert',
    titleZh: '警告提示',
    group: 'feedback',
    summary: '页面内的静态反馈条。',
    description: '展示需要用户持久看见的提示，不自动消失。临时结果用 Toast，需要决策用 Dialog。',
    whenToUse: [
      '表单顶部的错误汇总、只读页的环境提示。',
      '成功 / 警告 / 错误需要留在上下文中。',
    ],
    props: [
      { name: 'type', type: "'default' | 'info' | 'success' | 'warning' | 'danger'", default: "'info'", description: '语义。' },
      { name: 'title', type: 'string', description: '标题。' },
      { name: 'closable', type: 'boolean', default: 'false', description: '可关闭。' },
      { name: 'bordered', type: 'boolean', default: 'true', description: '描边。' },
    ],
    events: [{ name: 'close', type: '(event: MouseEvent) => void', description: '关闭。' }],
    slots: [
      { name: 'default', type: '—', description: '描述。' },
      { name: 'icon', type: '—', description: '替换图标。' },
    ],
    related: ['toaster', 'empty'],
  },
  {
    slug: 'empty',
    name: 'RsEmpty',
    title: 'Empty',
    titleZh: '空状态',
    group: 'feedback',
    summary: '无数据时的占位与引导。',
    description: '列表、表格、面板在没有数据时给出原因和下一步。避免空白让用户以为故障。',
    whenToUse: ['首次使用、筛选无结果、权限不足导致无数据。'],
    props: [
      { name: 'title', type: 'string', description: '主文案。' },
      { name: 'description', type: 'string', description: '说明。' },
    ],
    slots: [
      { name: 'icon', type: '—', description: '插图。' },
      { name: 'extra', type: '—', description: '操作，如「新建」。' },
    ],
    related: ['alert', 'button'],
  },
  {
    slug: 'loading',
    name: 'RsLoading',
    title: 'Loading',
    titleZh: '加载',
    group: 'feedback',
    summary: '局部或整页加载指示。',
    description: '表示内容正在获取。顶栏连续进度用 LoadingBar，按钮内等待用 Button.loading。',
    whenToUse: ['首次进入面板、刷新区块。'],
    props: [
      { name: 'spinning', type: 'boolean', default: 'true', description: '是否旋转。' },
      { name: 'tip', type: 'string', description: '文案。' },
    ],
    related: ['loading-bar', 'button'],
  },
  {
    slug: 'loading-bar',
    name: 'RsLoadingBar',
    title: 'LoadingBar',
    titleZh: '加载条',
    group: 'feedback',
    summary: '顶栏进度，配合 useRsLoadingBar。',
    description: '在应用根上挂载，路由切换或请求期间调用 start / finish。不是页面内 Spinner。',
    whenToUse: ['跨页面的请求进度。'],
    methods: [
      { name: 'start', type: '() => void', description: '开始。' },
      { name: 'finish', type: '() => void', description: '结束。' },
      { name: 'error', type: '() => void', description: '失败态。' },
    ],
    related: ['loading'],
  },
  {
    slug: 'tooltip',
    name: 'RsTooltip',
    title: 'Tooltip',
    titleZh: '文字提示',
    group: 'feedback',
    summary: '悬停时的短说明。',
    description: '为图标按钮、截断文本提供补充说明。长内容或操作请用 Popover。应用根需 RsTooltipProvider。',
    whenToUse: ['控件名称无法写全、需要一句补充。', '需要放表单或按钮时用 Popover / Dropdown。'],
    props: [
      { name: 'content', type: 'string', description: '提示文案。' },
      { name: 'side', type: "'top' | 'right' | 'bottom' | 'left'", description: '方向。' },
    ],
    related: ['popover', 'button'],
  },
  {
    slug: 'popover',
    name: 'RsPopover',
    title: 'Popover',
    titleZh: '气泡卡片',
    group: 'feedback',
    summary: '带标题与内容的浮层。',
    description: '比 Tooltip 更重：可放说明、短表单、筛选。模态决策用 Dialog。',
    whenToUse: ['需要在锚点旁展示一小块可交互内容。'],
    props: [
      { name: 'title', type: 'string', description: '标题。' },
      { name: 'open', type: 'boolean', description: '受控显隐。' },
    ],
    related: ['tooltip', 'dropdown', 'dialog'],
  },
  {
    slug: 'dialog',
    name: 'RsDialog',
    title: 'Dialog',
    titleZh: '对话框',
    group: 'feedback',
    summary: '工作窗或居中表单窗。',
    description:
      'layout=window 可拖拽、缩放、全屏，适合编辑器与连接会话；layout=form 为居中轻量窗。确认/危险提示请用 ConfirmDialog，不要用本组件页脚冒充确认 UI。',
    whenToUse: [
      '需要中断当前流、完成一段表单或展示详情。',
      '桌面工作台的浮动会话窗。',
    ],
    props: [
      { name: 'open / v-model:open', type: 'boolean', default: 'false', description: '是否打开。' },
      { name: 'title', type: 'string', description: '标题。' },
      { name: 'layout', type: "'window' | 'form' | 'confirm'", default: "'window'", description: '窗体类型。confirm 为 form 的历史别名。' },
      { name: 'width / height', type: "'sm' | 'md' | 'lg' | number | string", default: "'md'", description: '尺寸。' },
      { name: 'modal', type: 'boolean', default: 'true', description: '是否锁焦点。' },
      { name: 'showOverlay', type: 'boolean', default: 'false', description: '是否显示遮罩。与 modal 解耦。' },
      { name: 'draggable / resizable / fullscreenable', type: 'boolean', description: '仅 window 布局。' },
      { name: 'closeOnOverlayClick', type: 'boolean', default: 'false', description: '点遮罩关闭。' },
      { name: 'closeOnEsc', type: 'boolean', default: 'true', description: 'Esc 关闭。' },
      { name: 'beforeClose', type: '() => boolean | Promise<boolean>', description: '返回 false 阻止关闭。' },
      { name: 'showFooter', type: 'boolean', default: 'false', description: '内置取消/确定。' },
    ],
    events: [
      { name: 'openChange', type: '(open: boolean) => void', description: '显隐变化。' },
      { name: 'afterOpen / afterClose', type: '…', description: '动画后。' },
      { name: 'confirm / cancel', type: '() => void', description: '页脚按钮。' },
    ],
    slots: [
      { name: 'title / header', type: '—', description: '标题区。' },
      { name: 'default / body', type: '—', description: '主体。' },
      { name: 'footer', type: '—', description: '自定义页脚。' },
    ],
    related: ['confirm-dialog', 'drawer'],
  },
  {
    slug: 'confirm-dialog',
    name: 'RsConfirmDialog',
    title: 'ConfirmDialog',
    titleZh: '确认框',
    group: 'feedback',
    summary: '危险或不可逆操作的确认。',
    description: '专用确认 UI，带语义 tone 与明确的确认/取消。不要用 Dialog 页脚临时拼一套。',
    whenToUse: ['删除、断开、覆盖等需要二次确认的操作。'],
    props: [
      { name: 'open', type: 'boolean', description: '是否打开。' },
      { name: 'title / description', type: 'string', description: '文案。' },
      { name: 'tone', type: 'RsFeedbackTone', description: '危险操作用 danger。' },
    ],
    related: ['dialog', 'button'],
  },
  {
    slug: 'drawer',
    name: 'RsDrawer',
    title: 'Drawer',
    titleZh: '抽屉',
    group: 'feedback',
    summary: '从边缘滑出的面板。',
    description: '四向滑入。modal 与遮罩语义解耦：可以锁焦点不画遮罩，或反之。适合详情、筛选、设置。',
    whenToUse: ['需要保留背后列表上下文。', '完整中断用 Dialog。'],
    props: [
      { name: 'open', type: 'boolean', description: '是否打开。' },
      { name: 'side', type: "'left' | 'right' | 'top' | 'bottom'", description: '方向。' },
      { name: 'modal', type: 'boolean', description: '是否锁焦点。' },
      { name: 'title', type: 'string', description: '标题。' },
    ],
    related: ['dialog'],
  },
  {
    slug: 'context-menu',
    name: 'RsContextMenu',
    title: 'ContextMenu',
    titleZh: '右键菜单',
    group: 'feedback',
    summary: '针对对象的上下文命令。',
    description: '在树节点、表格行、编辑器上右键出菜单。命令列表与 Dropdown 类似，触发方式不同。',
    whenToUse: ['对象有一组就地操作（重命名、删除、复制路径）。'],
    props: [{ name: 'items', type: 'MenuItem[]', description: '菜单项。' }],
    related: ['dropdown', 'tree', 'table'],
  },
  {
    slug: 'toaster',
    name: 'RsToaster',
    title: 'Toaster',
    titleZh: '全局提示',
    group: 'feedback',
    summary: '轻量反馈，配合 useRsToast。',
    description: '在应用根挂载宿主，业务调用 toast.success / error。自动消失，不阻断操作。',
    whenToUse: ['保存成功、复制成功、后台任务开始。', '必须阅读的错误用 Alert 或 Dialog。'],
    props: [
      { name: 'position', type: 'string', description: '位置。' },
      { name: 'closeButton', type: 'boolean', description: '关闭按钮。' },
    ],
    related: ['alert', 'loading-bar'],
  },
]
