import type { ComponentDoc } from '../types'

const size = "'ssm' | 'sm' | 'md' | 'lg'"

export const formComponents: ComponentDoc[] = [
  {
    slug: 'form',
    name: 'RsForm',
    title: 'Form',
    titleZh: '表单',
    group: 'form',
    summary: '数据录入、校验与提交。',
    description:
      '表单是字段布局与校验的中枢。model + name 读写字段，rules 集中声明，Form.Item 负责标签、校验反馈与依赖字段。动态数组用 FormList。',
    whenToUse: [
      '登录、设置、新建资源等需要成组校验的场景。',
      '字段之间有依赖（dependencies）或需要 getFieldsValue / validateFields 时。',
      '单控件校验可继续用 RsInput 的 rule / validator；复杂表单应上收至 Form.rules。',
    ],
    props: [
      { name: 'model', type: 'Record<string, unknown>', description: '表单数据中枢。Item 声明 name 后读写此对象。' },
      { name: 'rules', type: 'RsFormRules', description: '按字段 name 匹配的校验规则，与控件自身规则合并。' },
      { name: 'validateMessages', type: 'RsFormValidateMessages', description: '覆盖默认文案，支持 {label}。' },
      { name: 'labelPosition', type: "'top' | 'left'", default: "'top'", description: '标签位置。' },
      { name: 'labelWidth', type: 'string', default: "'6rem'", description: '左标签宽度。' },
      { name: 'labelAlign', type: "'start' | 'end'", default: "'start'", description: '标签对齐。' },
      { name: 'size', type: size, default: "'md'", description: '字段控件默认尺寸。' },
      { name: 'gap', type: 'string', default: "'md'", description: '字段间距。' },
      { name: 'maxWidth', type: 'string', default: "'full'", description: '表单最大宽度。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用全部字段。' },
      { name: 'validateOnSubmit', type: 'boolean', default: 'true', description: '原生 submit 时自动校验。' },
    ],
    events: [
      { name: 'submit', type: '(event: Event) => void', description: '提交。' },
      { name: 'validate', type: '(result) => void', description: '整表校验结束。' },
    ],
    methods: [
      { name: 'validate', type: '() => Promise<RsFormValidationResult>', description: '校验全部字段。' },
      { name: 'validateFields', type: '(names?) => Promise<…>', description: '校验指定字段。' },
      { name: 'getFieldsValue', type: '(names?) => Record<string, unknown>', description: '读取字段值。' },
      { name: 'resetFields', type: '(names?) => void', description: '重置到初始值。' },
    ],
    slots: [
      { name: 'default', type: '—', description: '表单字段。' },
      { name: 'error', type: '{ name, message, value }', description: '自定义错误渲染，优先于 errorRender。' },
    ],
    faq: [
      {
        q: '控件还要不要写 v-model？',
        a: '可以。声明 name 后 Form 会读写 model；控件继续 v-model 也能工作。新表单推荐只走 model + name，减少双绑。',
      },
    ],
    related: ['fieldset', 'input', 'label'],
  },
  {
    slug: 'input',
    name: 'RsInput',
    title: 'Input',
    titleZh: '输入框',
    group: 'form',
    summary: '单行文本录入与校验。',
    description:
      '单行输入。框内 prefix / suffix（清除、字数、密码显隐在自定义 suffix 之前），框外连体 addonBefore / addonAfter。内置 rule 与 validator，可与 Form.Item name 组合。',
    whenToUse: [
      '搜索、账号、密钥、URL 等单行文本。',
      '需要格式规则（邮箱、数字）或自定义 validator。',
      '单位、协议等应放 addon，不要塞进 suffix。',
    ],
    props: [
      { name: 'v-model', type: 'string', description: '输入值。' },
      { name: 'type', type: "'text' | 'email' | 'password' | 'search' | 'tel' | 'url' | 'number' | …", default: "'text'", description: '原生类型。' },
      { name: 'label', type: 'string', description: '字段标签。表单字段优先用此，不必再包 RsLabel。' },
      { name: 'hint', type: 'string', description: '控件下方辅助说明。' },
      { name: 'placeholder', type: 'string', description: '占位。' },
      { name: 'name', type: 'string', description: '字段名，匹配 Form.rules。' },
      { name: 'required', type: 'boolean', default: 'false', description: '必填。' },
      { name: 'rule', type: 'RsInputRule', description: '预设格式规则。' },
      { name: 'validator', type: '(value: string) => boolean | string', description: '自定义校验。' },
      { name: 'validateTrigger', type: 'string', default: "'blur'", description: '校验时机。' },
      { name: 'invalid', type: 'boolean', default: 'false', description: '手动错误，优先于自动校验。' },
      { name: 'errorMessage', type: 'string', description: '手动错误文案。' },
      { name: 'clearable', type: 'boolean', default: 'false', description: '有值时显示清除。' },
      { name: 'maxlength', type: 'number', description: '最大字符数。' },
      { name: 'showCount', type: 'boolean', default: 'false', description: '字数统计，需配合 maxlength。' },
      { name: 'visibilityToggle', type: 'boolean', default: 'true', description: 'password 显隐按钮。' },
      { name: 'prefix / suffix', type: 'string', description: '框内前后缀文本。也可用插槽。' },
      { name: 'addonBefore / addonAfter', type: 'string', description: '框外连体 addon。' },
      { name: 'disabled / readonly', type: 'boolean', default: 'false', description: '禁用 / 只读。' },
      { name: 'size', type: size, description: '尺寸。' },
    ],
    events: [
      { name: 'pressEnter', type: '(event: KeyboardEvent) => void', description: '按下 Enter。' },
      { name: 'clear', type: '() => void', description: '点击清除。' },
      { name: 'validate', type: '(payload) => void', description: '校验结果。' },
      { name: 'focus / blur', type: '(event: FocusEvent) => void', description: '焦点。' },
    ],
    slots: [
      { name: 'prefix / suffix', type: '—', description: '框内图标或自定义节点。' },
      { name: 'addonBefore / addonAfter', type: '—', description: '框外连体区域。' },
    ],
    related: ['textarea', 'input-number', 'form', 'auto-complete'],
  },
  {
    slug: 'textarea',
    name: 'RsTextarea',
    title: 'Textarea',
    titleZh: '文本域',
    group: 'form',
    summary: '多行文本。autosize、字数与校验与 Input 同一套 Token。',
    description: '多行输入，支持 autosize、字数统计、清除与校验。视觉 Token 与 RsInput 同一套。',
    whenToUse: ['备注、描述、JSON 片段等需要换行的文本。', '需要随内容增高时开启 autosize。'],
    props: [
      { name: 'v-model', type: 'string', description: '文本。' },
      { name: 'autosize', type: 'boolean | { minRows, maxRows }', description: '高度随内容。' },
      { name: 'maxlength / showCount', type: 'number / boolean', description: '字数限制与统计。' },
      { name: 'clearable', type: 'boolean', default: 'false', description: '清除。' },
      { name: 'label / hint / required', type: 'string / boolean', description: '与 Input 相同的字段语义。' },
    ],
    related: ['input', 'mentions'],
  },
  {
    slug: 'input-number',
    name: 'RsInputNumber',
    title: 'InputNumber',
    titleZh: '数字输入',
    group: 'form',
    summary: '数字与步进。',
    description: '约束为数字的输入，支持步进、精度、上下限。中间态输入不会把非法字符串写回业务模型。',
    whenToUse: ['数量、端口、超时等必须是数字的字段。', '需要按钮步进或键盘方向键调整时。'],
    props: [
      { name: 'v-model', type: 'number | string | null', description: '数值。' },
      { name: 'min / max', type: 'number', description: '范围。' },
      { name: 'step', type: 'number', description: '步进。' },
      { name: 'precision', type: 'number', description: '小数位。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用。' },
    ],
    related: ['input', 'form'],
  },
  {
    slug: 'checkbox',
    name: 'RsCheckbox',
    title: 'Checkbox',
    titleZh: '复选框',
    group: 'form',
    summary: '多选与半选。',
    description: '在一组选项中选择多项。indeterminate 仅表示半选视觉，点击仍按 v-model 取反。',
    whenToUse: ['协议同意、列显示、批量选择的中间态。', '树或表格全选需要半选时。'],
    props: [
      { name: 'v-model', type: 'boolean', description: '是否选中。' },
      { name: 'indeterminate', type: 'boolean', default: 'false', description: '半选视觉。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用。' },
      { name: 'size', type: size, description: '尺寸。' },
    ],
    events: [{ name: 'change', type: '(value: boolean) => void', description: '变化。' }],
    related: ['radio', 'switch', 'tree'],
  },
  {
    slug: 'radio',
    name: 'RsRadio',
    title: 'Radio',
    titleZh: '单选',
    group: 'form',
    summary: '互斥选项。',
    description: '在一组互斥选项中选择一项。使用 RsRadio + RsRadioItem。选项很少且需要一眼看清全部时优于 Select。',
    whenToUse: ['2–5 个互斥选项，且需要同时可见。', '选项过多或需要搜索时改用 Select。'],
    props: [
      { name: 'v-model', type: 'string | number', description: '当前值。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '整组禁用。' },
    ],
    related: ['checkbox', 'select'],
  },
  {
    slug: 'switch',
    name: 'RsSwitch',
    title: 'Switch',
    titleZh: '开关',
    group: 'form',
    summary: '切换两种状态。',
    description: '表示开 / 关。默认 boolean，也可用 checkedValue / uncheckedValue 映射业务码（如 Y/N）。',
    whenToUse: ['立即生效的设置项（启用通知、暗色主题）。', '需要提交后才生效的互斥选择更适合 Checkbox / Radio。'],
    props: [
      { name: 'v-model', type: 'boolean | string | number', default: 'false', description: '当前值。' },
      { name: 'checkedValue', type: 'RsSwitchValue', default: 'true', description: '打开时写入的值。' },
      { name: 'uncheckedValue', type: 'RsSwitchValue', default: 'false', description: '关闭时写入的值。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用。' },
      { name: 'size', type: size, description: '尺寸。' },
    ],
    events: [{ name: 'change', type: '(value) => void', description: '切换。' }],
    related: ['checkbox', 'form'],
  },
  {
    slug: 'select',
    name: 'RsSelect',
    title: 'Select',
    titleZh: '选择器',
    group: 'form',
    summary: '从列表中选择，支持搜索与远程。',
    description:
      '下拉选择。支持多选、面板内搜索、远程防抖、创建选项、匹配高亮，以及 maxTagCount="responsive"。浮层避让视口。',
    whenToUse: [
      '选项较多，不适合全部平铺为 Radio。',
      '需要远程分页或在面板内过滤。',
      '层级数据请用 Cascader / TreeSelect。',
    ],
    props: [
      { name: 'v-model', type: 'string | number | Array', description: '选中值。' },
      { name: 'options', type: 'Array<{ label, value, disabled? }>', description: '选项。' },
      { name: 'multiple', type: 'boolean', default: 'false', description: '多选。' },
      { name: 'searchable / filterable', type: 'boolean', description: '面板内搜索。' },
      { name: 'clearable', type: 'boolean', description: '允许清空。' },
      { name: 'disabled', type: 'boolean', default: 'false', description: '禁用。' },
      { name: 'size', type: size, description: '尺寸。' },
      { name: 'placeholder', type: 'string', description: '占位。' },
      { name: 'maxTagCount', type: 'number | "responsive"', description: '多选标签折叠。' },
    ],
    related: ['auto-complete', 'cascader', 'tree-select'],
  },
  {
    slug: 'auto-complete',
    name: 'RsAutoComplete',
    title: 'AutoComplete',
    titleZh: '自动完成',
    group: 'form',
    summary: '输入时给出建议，值仍以输入为准。',
    description: '在输入框内打字出建议，列表贴合输入并避让视口。遵循 APG Combobox：允许输入不在列表中的值。要强制选列表项请用 Select。',
    whenToUse: ['搜索历史、路径补全、可自由输入的建议。', '必须选自列表时用 Select。'],
    props: [
      { name: 'v-model', type: 'string', description: '输入值。' },
      { name: 'options', type: 'string[] | { label, value }[]', description: '建议项。' },
    ],
    related: ['input', 'select', 'mentions'],
  },
  {
    slug: 'cascader',
    name: 'RsCascader',
    title: 'Cascader',
    titleZh: '级联选择',
    group: 'form',
    summary: '多列层级选择。',
    description: '从多列中逐级选择。支持 changeOnSelect 与 expandTrigger。树形勾选更适合 TreeSelect。',
    whenToUse: ['省市区、目录路径等固定层级。', '需要勾选多个节点时用 TreeSelect。'],
    props: [
      { name: 'v-model', type: 'Array', description: '路径值。' },
      { name: 'options', type: 'CascaderOption[]', description: '树形选项。' },
      { name: 'changeOnSelect', type: 'boolean', description: '选择任意级即生效。' },
      { name: 'expandTrigger', type: "'click' | 'hover'", description: '展开方式。' },
    ],
    related: ['tree-select', 'select'],
  },
  {
    slug: 'tree-select',
    name: 'RsTreeSelect',
    title: 'TreeSelect',
    titleZh: '树选择',
    group: 'form',
    summary: '在下拉中选择树节点，面板内可搜索。',
    description: '下拉树选择，复用 RsTree。适合权限、目录、组织节点等需要勾选或单选树节点的表单字段。',
    whenToUse: ['选项是树，且需要在表单里选择。', '需要完整树操作页面时用 RsTree。'],
    props: [
      { name: 'v-model', type: 'string | string[]', description: '选中节点。' },
      { name: 'data', type: 'TreeNode[]', description: '树数据。' },
      { name: 'multiple', type: 'boolean', description: '多选。' },
    ],
    related: ['tree', 'cascader', 'select'],
  },
  {
    slug: 'mentions',
    name: 'RsMentions',
    title: 'Mentions',
    titleZh: '提及',
    group: 'form',
    summary: '在文本中 @ 成员。',
    description: '多行输入中用触发符（默认 @）拉起成员列表。用于评论、工单指派。',
    whenToUse: ['评论、描述里需要点名成员。', '普通多行文本用 Textarea。'],
    props: [
      { name: 'v-model', type: 'string', description: '文本。' },
      { name: 'options', type: '{ value, label }[]', description: '可提及的成员。' },
      { name: 'prefix', type: 'string', default: "'@'", description: '触发符。' },
    ],
    related: ['textarea', 'auto-complete'],
  },
  {
    slug: 'label',
    name: 'RsLabel',
    title: 'Label',
    titleZh: '标签',
    group: 'form',
    summary: '表单标签与必填标记。',
    description: '独立标签。Input / DatePicker 等已内置 label 时不必再包一层。Select 等仍可用 RsLabel 关联控件。',
    whenToUse: ['控件本身没有 label prop。', '需要自定义必填星号与提示。'],
    props: [
      { name: 'required', type: 'boolean', default: 'false', description: '必填星号。' },
      { name: 'hint', type: 'string', description: '说明。' },
    ],
    related: ['form', 'input'],
  },
  {
    slug: 'fieldset',
    name: 'RsFieldset',
    title: 'Fieldset',
    titleZh: '表单分区',
    group: 'form',
    summary: '用 legend 分组字段，不是卡片。',
    description:
      '对应 WHATWG fieldset / legend。说明走标题旁 tooltip；可用 borderStyle / borderTone（含 faded）与标题清晰度。不要用 Card 冒充分组语义。',
    whenToUse: ['同一表单内的逻辑分组（连接信息、认证、高级）。', '需要弱化边框以免干扰阅读时用 faded。'],
    props: [
      { name: 'legend / title', type: 'string', description: '组名。' },
      { name: 'tooltip', type: 'string', description: '组说明。' },
      { name: 'borderStyle / borderTone', type: 'string', description: '边框样式与虚化。' },
      { name: 'titleWeight / titleTone / titleSize', type: 'string', description: '标题清晰度。' },
    ],
    related: ['form', 'card'],
  },
  {
    slug: 'dynamic-tags',
    name: 'RsDynamicTags',
    title: 'DynamicTags',
    titleZh: '动态标签',
    group: 'form',
    summary: '可增删的标签组。',
    description: '在输入中创建标签、校验重复与格式。用于环境变量键、关键字、多值枚举。',
    whenToUse: ['一组用户可增删的短文本。', '单个状态标签用 Tag。'],
    props: [
      { name: 'v-model', type: 'string[]', description: '标签列表。' },
      { name: 'max', type: 'number', description: '数量上限。' },
    ],
    related: ['tag', 'input'],
  },
  {
    slug: 'upload',
    name: 'RsUpload',
    title: 'Upload',
    titleZh: '上传',
    group: 'form',
    summary: '选择文件并做前端校验。',
    description: '文件选择与类型 / 大小校验辅助。实际上传请求由业务完成，组件不内置存储协议。',
    whenToUse: ['导入配置、证书、附件。', '需要限制扩展名或体积时。'],
    props: [
      { name: 'accept', type: 'string', description: '文件类型。' },
      { name: 'multiple', type: 'boolean', description: '多选。' },
      { name: 'maxSize', type: 'number', description: '大小限制。' },
    ],
    related: ['button', 'form'],
  },
  {
    slug: 'date-picker',
    name: 'RsDatePicker',
    title: 'DatePicker',
    titleZh: '日期选择',
    group: 'form',
    summary: '选择日期。',
    description: '弹出日历选择单个日期。日期时间请用 DateTimePicker，仅时间用 TimePicker。',
    whenToUse: ['生日、截止日期等只要日期。', '需要时分秒时用 DateTimePicker。'],
    props: [
      { name: 'v-model', type: 'string | Date | null', description: '日期。' },
      { name: 'label / placeholder / clearable', type: 'string / boolean', description: '与输入类控件一致。' },
    ],
    related: ['datetime-picker', 'time-picker', 'calendar-grid'],
  },
  {
    slug: 'datetime-picker',
    name: 'RsDateTimePicker',
    title: 'DateTimePicker',
    titleZh: '日期时间',
    group: 'form',
    summary: '选择日期与时间。',
    description: '日期 + 时间组合。作业调度、日志查询区间常用。',
    whenToUse: ['需要精确到时分或秒的时间点。'],
    props: [{ name: 'v-model', type: 'string | Date | null', description: '日期时间。' }],
    related: ['date-picker', 'time-picker'],
  },
  {
    slug: 'time-picker',
    name: 'RsTimePicker',
    title: 'TimePicker',
    titleZh: '时间选择',
    group: 'form',
    summary: '选择时刻。',
    description: '仅选择时分（或秒）。与日期无关的日常时刻、窗口期。',
    whenToUse: ['提醒时间、业务窗口，不需要日期部分。'],
    props: [{ name: 'v-model', type: 'string | null', description: '时间字符串。' }],
    related: ['date-picker', 'datetime-picker'],
  },
  {
    slug: 'calendar-grid',
    name: 'RsCalendarGrid',
    title: 'CalendarGrid',
    titleZh: '日历网格',
    group: 'form',
    summary: '日历原语，供选择器与自定义日历复用。',
    description: '无输入框的日历网格。DatePicker 内部使用；产品要做月视图排班时也可直接用。',
    whenToUse: ['自定义日历、排班、日期范围面板。', '普通选日期用 DatePicker。'],
    props: [{ name: 'modelValue', type: 'Date | string', description: '当前月 / 选中日。' }],
    related: ['date-picker'],
  },
]
