import type { ComponentDoc } from '../types'

export const navComponents: ComponentDoc[] = [
  {
    slug: 'anchor',
    name: 'RsAnchor',
    title: 'Anchor',
    titleZh: '锚点',
    group: 'nav',
    summary: '页内目录，滚动时高亮当前标题。',
    description:
      '页内目录。根是原生 nav + a，不包 Reka。滚动监听当前章节，墨点沿轨道跟随；点击平滑滚到对应标题。Hash 路由必须关闭 changeHash，否则会覆盖当前路由。滚动容器不是 window 时传入 getContainer。',
    descriptionEn:
      'In-page table of contents. The root is a native nav plus anchors — no Reka. Scroll highlights the current heading; the ink follows the rail. A click smooth-scrolls to the target. Hash routers must set changeHash=false or the current route is overwritten. Pass getContainer when the scroller is not window.',
    whenToUse: [
      '文档、指南、组件 API 超过一屏，需要快速跳转章节。',
      '滚动容器不是 window（工作台主栏、抽屉）时传入 getContainer。',
      '跨页层级用 Breadcrumb。同级切换用 Tabs。向导用 Steps。应用入口用 Menu。',
    ],
    whenToUseEn: [
      'A long doc, guide, or API page that needs jump-to-section.',
      'Pass getContainer when the scroller is not window (workbench main pane, a drawer).',
      'Use Breadcrumb for hierarchy across pages, Tabs for peers, Steps for a wizard, Menu for app entries.',
    ],
    demos: [
      { id: 'demo-basic', title: '基本用法', titleEn: 'Basic' },
      { id: 'demo-lineless', title: '无轨道', titleEn: 'Lineless' },
      { id: 'demo-horizontal', title: '横向', titleEn: 'Horizontal' },
      { id: 'demo-offset', title: '偏移与吸附', titleEn: 'Offset and affix' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
      { id: 'demo-methods', title: '方法', titleEn: 'Methods' },
    ],
    props: [
      {
        name: 'items',
        type: 'RsAnchorItem[]',
        description: 'href + title，可嵌套 children，可选 disabled。href 应对应文档里的 id。',
        descriptionEn: 'href + title. children may nest. disabled is optional. href must match an id in the document.',
      },
      {
        name: 'v-model / modelValue',
        type: 'string',
        default: "''",
        defaultEn: "''",
        description: '当前激活的 href。',
        descriptionEn: 'The active href.',
      },
      {
        name: 'offset',
        type: 'number',
        default: '12',
        defaultEn: '12',
        description: '判定「已滚过」的顶部偏移（px）。',
        descriptionEn: 'Top offset in px used to decide a heading has been passed.',
      },
      {
        name: 'targetOffset',
        type: 'number',
        description: '点击后标题距容器顶的距离（px）。未传时等于 offset。',
        descriptionEn: 'Distance in px from the container top after a click. Defaults to offset.',
      },
      {
        name: 'bounds',
        type: 'number',
        default: '8',
        defaultEn: '8',
        description: '判定容差（px），避免刚贴顶就跳下一项。',
        descriptionEn: 'Tolerance in px so the next item does not activate the moment a heading touches the top.',
      },
      {
        name: 'affix',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: 'sticky 吸附。关闭后随文档流。',
        descriptionEn: 'Sticky affix. Off keeps the nav in normal flow.',
      },
      {
        name: 'affixOffset',
        type: 'number',
        description: 'sticky 距滚动容器顶的距离（px），写入 --rs-anchor-affix-top。',
        descriptionEn: 'Sticky offset from the scroller top in px. Writes --rs-anchor-affix-top.',
      },
      {
        name: 'lineless',
        type: 'boolean',
        default: 'false',
        defaultEn: 'false',
        description: '无轨道墨点，只高亮文字。',
        descriptionEn: 'Hide the rail ink. Only the text highlights.',
      },
      {
        name: 'changeHash',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: '是否写入 location.hash。Hash 路由必须 false。',
        descriptionEn: 'Whether to write location.hash. Must be false on a hash router.',
      },
      {
        name: 'replace',
        type: 'boolean',
        default: 'true',
        defaultEn: 'true',
        description: 'changeHash 时用 history.replaceState。false 则 pushState。',
        descriptionEn: 'When changeHash is on, use history.replaceState. false uses pushState.',
      },
      {
        name: 'direction',
        type: "'vertical' | 'horizontal'",
        default: 'vertical',
        defaultEn: 'vertical',
        description: '竖向侧栏或横向顶栏。',
        descriptionEn: 'A vertical side rail or a horizontal top rail.',
      },
      {
        name: 'scrollBehavior',
        type: "'smooth' | 'auto'",
        description: '点击滚动行为。未传时减少动态用 auto，否则 smooth。',
        descriptionEn: 'Click scroll behavior. When omitted, reduced motion uses auto, otherwise smooth.',
      },
      {
        name: 'getCurrentAnchor',
        type: '(activeHref: string) => string',
        description: '覆盖滚动或点击后的激活 href。返回空字符串则不改。',
        descriptionEn: 'Override the href that becomes active after scroll or click. An empty string leaves the current value.',
      },
      {
        name: 'getContainer',
        type: '() => HTMLElement | Window | null | undefined',
        description: '滚动容器。返回空时回退 window。不要每次渲染换新函数也可，组件比较的是返回值。',
        descriptionEn: 'Scroll container. An empty return falls back to window. A new function each render is fine — the component compares the element.',
      },
      {
        name: 'id',
        type: 'string',
        description: '写到 nav 的 id。',
        descriptionEn: 'Id written on the nav.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '覆盖 nav 的可访问名称。未传走 anchor.label。',
        descriptionEn: 'Overrides the nav accessible name. Defaults to anchor.label.',
      },
    ],
    events: [
      {
        name: 'update:modelValue',
        type: '(href: string) => void',
        description: 'v-model。激活 href 变化。',
        descriptionEn: 'v-model. Fires when the active href changes.',
      },
      {
        name: 'change',
        type: '(href: string) => void',
        description: '激活项变化。与 v-model 同时发出。',
        descriptionEn: 'The active item changed. Also emitted with v-model.',
      },
      {
        name: 'click',
        type: '(href: string, event: MouseEvent) => void',
        description: '点击链接。禁用项仍发 click，但不滚动、不改激活。',
        descriptionEn: 'A link was clicked. A disabled item still emits click but does not scroll or change the active href.',
      },
    ],
    slots: [
      {
        name: 'item',
        type: '{ item: RsAnchorFlatItem, active: boolean, href: string }',
        description: '自定义一条标题。未传时渲染 item.title。',
        descriptionEn: 'Custom title for one row. Renders item.title when omitted.',
      },
    ],
    methods: [
      {
        name: 'scrollTo',
        type: '(href: string) => void',
        description: '宿主调用。滚到对应章节并激活。禁用项或找不到目标时不滚动。模板 ref 用 RsAnchorExpose。',
        descriptionEn: 'Host call. Scroll to the section and activate it. A disabled item or a missing target does not scroll. Type the template ref as RsAnchorExpose.',
      },
    ],
    tokens: [
      {
        name: '--rs-anchor-min-width / gap / rail-width / indent / link-pad-* / affix-top',
        default: 'theme',
        description: '侧栏最小宽、间距、轨道粗细、缩进、链接内边距、sticky 顶距。不要写死 rem。',
        descriptionEn: 'Min width, gap, rail thickness, indent, link padding, and sticky top. Do not hard-code rem.',
      },
      {
        name: '--rs-anchor-rail / ink / ink-ring',
        default: 'theme',
        description: '轨道底、墨点、墨点描边。随 data-rs-theme。',
        descriptionEn: 'Rail, ink, and ink ring. Follow data-rs-theme.',
      },
      {
        name: '--rs-anchor-link / link-hover / link-active / link-active-weight / link-active-bg / disabled-opacity',
        default: 'theme',
        description: '链接色、激活字重与无轨道底、禁用透明度。',
        descriptionEn: 'Link colors, active weight, lineless active background, and disabled opacity.',
      },
      {
        name: '--rs-focus-ring / --rs-focus-ring-width / --rs-transition-fast',
        default: 'theme',
        description: '焦点环与过渡。减少动态时关闭过渡。',
        descriptionEn: 'Focus ring and transition. Transitions turn off under reduced motion.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 nav，条目是 a[href]。业务与文档站不要 import reka-ui。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is a native nav; rows are a[href]. Apps and the docs site must not import reka-ui.',
      },
      {
        q: '和 Vue Router 的 hash 模式一起用为什么会跳首页？',
        a: 'createWebHashHistory 把 # 当成路由。传入 :change-hash="false"，只滚动不改 URL。文档站演示一律关闭。',
        qEn: 'Why does this jump to home with a Vue Router hash history?',
        aEn: 'createWebHashHistory treats # as the route. Pass :change-hash="false" to scroll only. Docs demos always turn it off.',
      },
      {
        q: '滚动容器不是 window 怎么办？',
        a: '传入 getContainer，返回那个 overflow 元素。组件比较的是返回的节点，不是函数引用，因此 :get-container="() => box" 每次渲染新建函数也可以。',
        qEn: 'What if the scroller is not window?',
        aEn: 'Pass getContainer and return that overflow element. The component compares the node, not the function identity, so :get-container="() => box" is fine.',
      },
      {
        q: '中文或编码过的 hash 能对上吗？',
        a: '能。hrefToAnchorId 会 decodeURIComponent。文档 id="概述" 时 href 写 #概述 或 #%E6%A6%82%E8%BF%B0 都可以。',
        qEn: 'Do encoded or non-ASCII hashes match?',
        aEn: 'Yes. hrefToAnchorId runs decodeURIComponent. If the heading id is 概述, href may be #概述 or #%E6%A6%82%E8%BF%B0.',
      },
      {
        q: '点最后一项画面滚过去了，高亮却停在上一项？',
        a: '最后一节往往不够高，标题到不了判定线。组件在贴底时高亮最后一项；点击后先锁住激活，等滚动停稳再听滚动。不要靠把最后一节垫很高来修。',
        qEn: 'I click the last item, the pane scrolls, but the highlight stays on the previous one?',
        aEn: 'The last section is often too short to reach the offset line. At the bottom the last item stays active. A click locks the highlight until scrolling settles. Do not pad the last section as a workaround.',
      },
      {
        q: '和 Menu / Tabs / Breadcrumb 怎么选？',
        a: '本页跳章节用 Anchor。应用入口用 Menu。同一区域切换打开对象用 Tabs。跨页层级用 Breadcrumb。',
        qEn: 'When should I use Menu, Tabs, or Breadcrumb instead?',
        aEn: 'Use Anchor to jump sections on this page. Use Menu for app entries, Tabs to switch open objects in one pane, Breadcrumb for hierarchy across pages.',
      },
    ],
    related: ['menu', 'tabs', 'steps', 'breadcrumb'],
  },
  {
    slug: 'breadcrumb',
    name: 'RsBreadcrumb',
    title: 'Breadcrumb',
    titleZh: '面包屑',
    group: 'nav',
    summary: '展示当前页面在层级中的位置。',
    description:
      '跨页层级。根是原生 nav + ol，不包 Reka。最后一项为当前页（aria-current=page），通常不可点。to 在未传 href 时写到 a[href]；Vue Router 请在 click 里 preventDefault 后 push，或用 #item。超过 maxItems 时中间收成省略号，点开后展开。',
    descriptionEn:
      'Hierarchy across pages. The root is a native nav plus an ordered list — no Reka. The last item is the current page (aria-current=page) and is usually not a link. to is written as href when href is omitted. With Vue Router, preventDefault on click and push, or use #item. Paths longer than maxItems collapse to an ellipsis; a click expands them.',
    whenToUse: [
      '信息架构超过两级，或用户可能从深链进入，需要回到列表或概览。',
      '本页跳章节用 Anchor。同级切换用 Tabs。向导用 Steps。应用入口用 Menu。',
      '不要用面包屑代替页面标题；末级只标明位置。',
    ],
    whenToUseEn: [
      'The IA is more than two levels, or people land from a deep link and need a way back.',
      'Use Anchor to jump sections on this page, Tabs for peers, Steps for a wizard, Menu for app entries.',
      'Do not replace the page title with a breadcrumb. The last item only marks the place.',
    ],
    demos: [
      { id: 'demo-basic', title: '基本用法', titleEn: 'Basic' },
      { id: 'demo-separator', title: '分隔符', titleEn: 'Separator' },
      { id: 'demo-icons', title: '图标', titleEn: 'Icons' },
      { id: 'demo-collapse', title: '折叠', titleEn: 'Collapse' },
      { id: 'demo-disabled', title: '禁用', titleEn: 'Disabled' },
      { id: 'demo-slots', title: '插槽', titleEn: 'Slots' },
      { id: 'demo-events', title: '事件', titleEn: 'Events' },
    ],
    props: [
      {
        name: 'items',
        type: 'RsBreadcrumbItem[]',
        description:
          '路径项：label 必填；href / to / icon / disabled / target / rel / key 可选。href 优先于 to。最后一项视为当前页，即使写了 href 也渲染为 span。',
        descriptionEn:
          'Path items. label is required; href / to / icon / disabled / target / rel / key are optional. href wins over to. The last item is the current page and renders as a span even if href is set.',
      },
      {
        name: 'separator',
        type: 'string',
        description: '文字分隔符。未传时用 separatorIcon。',
        descriptionEn: 'Text separator. When omitted, separatorIcon is used.',
      },
      {
        name: 'separatorIcon',
        type: 'string',
        default: 'chevron-right',
        defaultEn: 'chevron-right',
        description: 'Lucide kebab-case。有 separator 文字时不渲染图标。RTL 下会水平翻转。',
        descriptionEn: 'Lucide kebab-case. Ignored when separator is set. Flips horizontally in RTL.',
      },
      {
        name: 'maxItems',
        type: 'number',
        description: '超过该数量时中间收成省略号。省略号算一项。未传不折叠。',
        descriptionEn: 'Collapse the middle into an ellipsis when the path is longer. The ellipsis counts as one item. Omit to keep every crumb.',
      },
      {
        name: 'itemsBeforeCollapse',
        type: 'number',
        default: '1',
        defaultEn: '1',
        description: '折叠时省略号前保留几项。',
        descriptionEn: 'How many items stay before the ellipsis.',
      },
      {
        name: 'itemsAfterCollapse',
        type: 'number',
        default: '1',
        defaultEn: '1',
        description: '折叠时省略号后保留几项（至少 1，末级当前页）。',
        descriptionEn: 'How many items stay after the ellipsis. At least 1 so the current page remains.',
      },
      {
        name: 'id',
        type: 'string',
        description: '写到 nav 的 id。',
        descriptionEn: 'Id written on the nav.',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        description: '覆盖 nav 的可访问名称。未传走 breadcrumb.label。',
        descriptionEn: 'Overrides the nav accessible name. Defaults to breadcrumb.label.',
      },
    ],
    events: [
      {
        name: 'click',
        type: '(item: RsBreadcrumbItem, event: MouseEvent) => void',
        description: '点到某一项。禁用项仍发 click，但会 preventDefault，不跳转。当前页 pointer-events: none，点不到。',
        descriptionEn:
          'An item was clicked. A disabled item still emits click but preventDefault stops navigation. The current page has pointer-events: none, so it does not fire.',
      },
    ],
    slots: [
      {
        name: 'item',
        type: '{ item: RsBreadcrumbItem, index: number, isCurrent: boolean, href?: string }',
        description: '自定义一项的内容。外层仍是 a 或 span。未传时渲染 icon + label。',
        descriptionEn: 'Custom content for one crumb. The outer node is still a or span. Renders icon + label when omitted.',
      },
      {
        name: 'separator',
        type: '{ index: number }',
        description: '自定义两项之间的分隔符。未传时用 separator / separatorIcon。',
        descriptionEn: 'Custom separator between crumbs. Falls back to separator / separatorIcon.',
      },
      {
        name: 'more',
        type: '{ hiddenItems: RsBreadcrumbItem[], expand: () => void }',
        description: '自定义折叠省略号。默认是 ellipsis 图标按钮，点击展开。',
        descriptionEn: 'Custom collapsed ellipsis. The default is an ellipsis icon button that expands the path.',
      },
    ],
    methods: [
      {
        name: 'none',
        type: '—',
        description: '没有 defineExpose。展开折叠只是内部状态，点省略号即可。',
        descriptionEn: 'No defineExpose. Expanding the collapsed path is internal state — click the ellipsis.',
      },
    ],
    tokens: [
      {
        name: '--rs-breadcrumb-gap / item-gap / link-pad-* / font-size',
        default: 'theme',
        description: '列表间距、项内间距、链接内边距、字号。不要写死 rem。',
        descriptionEn: 'List gap, item gap, link padding, and font size. Do not hard-code rem.',
      },
      {
        name: '--rs-breadcrumb-link / link-hover / link-hover-bg / current / current-weight / sep / disabled-opacity',
        default: 'theme',
        description: '链接色、悬停底、当前页字重、分隔符色、禁用透明度。随 data-rs-theme。',
        descriptionEn: 'Link color, hover wash, current-page weight, separator, and disabled opacity. Follow data-rs-theme.',
      },
      {
        name: '--rs-focus-ring / --rs-focus-ring-width / --rs-transition-fast',
        default: 'theme',
        description: '焦点环与过渡。减少动态时关闭过渡。',
        descriptionEn: 'Focus ring and transition. Transitions turn off under reduced motion.',
      },
    ],
    faq: [
      {
        q: '还要装 reka-ui 吗？',
        a: '不包。根是原生 nav + ol，链接是 a[href]，当前页是 span。业务与文档站不要 import reka-ui。',
        qEn: 'Do I still need reka-ui?',
        aEn: 'No. The root is a native nav plus ol; links are a[href]; the current page is a span. Apps and the docs site must not import reka-ui.',
      },
      {
        q: 'to 和 Vue Router 怎么接？',
        a: '未传 href 时 to 会写到 a[href]。history 模式左键会整页跳。在 @click 里 event.preventDefault() 再 router.push(item.to)，或用 #item 自己画 RouterLink（不要把 RouterLink 再套进默认的 a 里）。',
        qEn: 'How do I wire to to Vue Router?',
        aEn: 'When href is omitted, to is written as href. A left click does a full navigation on history mode. preventDefault on @click and router.push(item.to), or render RouterLink in #item (do not nest RouterLink inside the default a).',
      },
      {
        q: '外链要新窗口吗？',
        a: '传 target="_blank"。组件会补 rel="noopener noreferrer"。已有 rel 会合并，不会去掉。',
        qEn: 'How do I open an external link in a new tab?',
        aEn: 'Pass target="_blank". The component adds rel="noopener noreferrer" and keeps any rel you already set.',
      },
      {
        q: '和 Anchor / Menu / Tabs 怎么选？',
        a: '跨页层级用 Breadcrumb。本页跳章节用 Anchor。应用入口用 Menu。同一区域切换打开对象用 Tabs。',
        qEn: 'When should I use Anchor, Menu, or Tabs instead?',
        aEn: 'Use Breadcrumb for hierarchy across pages, Anchor to jump sections on this page, Menu for app entries, Tabs to switch open objects in one pane.',
      },
    ],
    related: ['anchor', 'menu', 'tabs', 'steps'],
  },
  {
    slug: 'menu',
    name: 'RsMenu',
    title: 'Menu',
    titleZh: '菜单',
    group: 'nav',
    summary: '应用内导航菜单。',
    description: '侧栏或顶栏的导航结构，支持分组与选中态。侧栏布局可与 Sidebar 组合。',
    whenToUse: ['应用有多个稳定入口。', '临时操作列表用 Dropdown / ContextMenu。'],
    props: [
      { name: 'items', type: 'MenuItem[]', description: '菜单数据。' },
      { name: 'collapsed', type: 'boolean', description: '折叠为图标。' },
    ],
    related: ['sidebar', 'dropdown', 'breadcrumb'],
  },
  {
    slug: 'sidebar',
    name: 'RsSidebar',
    title: 'Sidebar',
    titleZh: '侧栏',
    group: 'nav',
    summary: '侧边导航容器。',
    description: '工作台左侧导航。配合 SidebarGroup / SidebarItem 组织入口，可与 SplitPane 组成可调宽度布局。',
    whenToUse: ['控制台级应用的一级导航。'],
    props: [{ name: 'collapsed', type: 'boolean', description: '折叠。' }],
    slots: [{ name: 'default', type: '—', description: '分组与条目。' }],
    related: ['menu', 'split-pane'],
  },
  {
    slug: 'tabs',
    name: 'RsTabs',
    title: 'Tabs',
    titleZh: '标签页',
    group: 'nav',
    summary: '同一层级内容的切换，支持关闭与重命名。',
    description: '工作台式标签：打开多个文档 / 连接 / 查询。支持关闭、重命名与溢出滚动，不是简单的分段控制器。',
    whenToUse: ['同一区域切换多个打开的对象。', '步骤流程用 Steps，设置分组用锚点或 Collapse。'],
    props: [
      { name: 'v-model / modelValue', type: 'string', description: '当前页签。' },
      { name: 'closable', type: 'boolean', description: '允许关闭。' },
    ],
    related: ['steps', 'menu'],
  },
  {
    slug: 'steps',
    name: 'RsSteps',
    title: 'Steps',
    titleZh: '步骤条',
    group: 'nav',
    summary: '引导用户完成分步任务。',
    description: '展示任务进度与当前步骤。用于向导、开通流程。',
    whenToUse: ['任务有固定顺序且需要回看进度。', '单页表单用 Fieldset 分组即可。'],
    props: [
      { name: 'current', type: 'number', description: '当前步骤索引。' },
      { name: 'items', type: '{ title, description? }[]', description: '步骤。' },
    ],
    related: ['tabs', 'form'],
  },
  {
    slug: 'dropdown',
    name: 'RsDropdown',
    title: 'Dropdown',
    titleZh: '下拉菜单',
    group: 'nav',
    summary: '由按钮触发的命令列表。',
    description: '收纳次要操作。与 Select 不同：Dropdown 触发命令，Select 回写表单值。',
    whenToUse: ['更多、批量操作、账号菜单。', '选择一个值写回表单时用 Select。'],
    props: [
      { name: 'items', type: 'DropdownItem[]', description: '菜单项。' },
      { name: 'disabled', type: 'boolean', description: '禁用触发器。' },
    ],
    slots: [{ name: 'trigger / default', type: '—', description: '触发器。' }],
    related: ['context-menu', 'button', 'select'],
  },
  {
    slug: 'toolbar',
    name: 'RsToolbar',
    title: 'Toolbar',
    titleZh: '工具条',
    group: 'nav',
    summary: '操作按钮的水平布局。',
    description: '把主操作、筛选与辅助操作排在一行，两端对齐。编辑器与表格上方常用。',
    whenToUse: ['列表页或编辑器需要一排稳定操作。'],
    slots: [
      { name: 'start', type: '—', description: '左侧。' },
      { name: 'end', type: '—', description: '右侧。' },
    ],
    related: ['button', 'dropdown'],
  },
  {
    slug: 'split-pane',
    name: 'RsSplitPane',
    title: 'SplitPane',
    titleZh: '分栏',
    group: 'nav',
    summary: '可拖拽调整的多栏布局。',
    description: '工作台经典布局：树 + 表格、编辑器 + 终端。支持方向与最小尺寸。',
    whenToUse: ['两栏或多栏需要用户自己调宽度。'],
    props: [
      { name: 'direction', type: "'horizontal' | 'vertical'", description: '分割方向。' },
      { name: 'minSize', type: 'number', description: '最小尺寸。' },
    ],
    related: ['sidebar', 'scrollbar'],
  },
  {
    slug: 'pagination',
    name: 'RsPagination',
    title: 'Pagination',
    titleZh: '分页',
    group: 'nav',
    summary: '分页浏览长列表。',
    description: '页码、每页条数与跳转。表格、日志检索的配套控件。',
    whenToUse: ['数据量超过一屏且服务端分页。', '前端虚拟滚动长列表用 VirtualList / Table virtual。'],
    props: [
      { name: 'page', type: 'number', description: '当前页。' },
      { name: 'pageSize', type: 'number', description: '每页条数。' },
      { name: 'total', type: 'number', description: '总条数。' },
    ],
    related: ['table', 'virtual-list'],
  },
]
