import type { ComponentDoc } from '../types'

export const navComponents: ComponentDoc[] = [
  {
    slug: 'anchor',
    name: 'RsAnchor',
    title: 'Anchor',
    titleZh: '锚点',
    group: 'nav',
    summary: '页内目录，滚动时高亮当前标题。',
    description:
      '用于长文、组件文档与设置页的本页导航。滚动监听当前章节，墨点沿轨道跟随。点击平滑滚到对应标题。Hash 路由必须关闭 changeHash，否则会覆盖当前路由。',
    whenToUse: [
      '文档、指南、组件 API 超过一屏，需要快速跳转章节。',
      '滚动容器不是 window（如工作台主栏）时传入 getContainer。',
    ],
    props: [
      { name: 'items', type: 'RsAnchorItem[]', description: 'href + title，可嵌套 children。' },
      { name: 'v-model', type: 'string', description: '当前激活的 href。' },
      { name: 'offset', type: 'number', default: '12', description: '判定已滚过的顶部偏移。' },
      { name: 'targetOffset', type: 'number', description: '点击后标题距容器顶的距离，默认等于 offset。' },
      { name: 'bounds', type: 'number', default: '8', description: '判定容差。' },
      { name: 'affix', type: 'boolean', default: 'true', description: 'sticky 吸附。' },
      { name: 'lineless', type: 'boolean', default: 'false', description: '无轨道墨点。' },
      { name: 'changeHash', type: 'boolean', default: 'true', description: '是否写入 location.hash。Hash 路由设 false。' },
      { name: 'getContainer', type: '() => HTMLElement | Window', description: '滚动容器，默认 window。' },
    ],
    events: [
      { name: 'change', type: '(href: string) => void', description: '激活项变化。' },
      { name: 'click', type: '(href, event) => void', description: '点击链接。' },
    ],
    tokens: [
      { name: '--rs-primary', default: '主题主色', description: '墨点与激活文字。' },
      { name: '--rs-border-subtle', default: '细分隔', description: '轨道底色。' },
    ],
    faq: [
      {
        q: '和 Vue Router 的 hash 模式一起用为什么会跳首页？',
        a: 'createWebHashHistory 把 # 当成路由。传入 :change-hash="false"，只滚动不改 URL。',
      },
    ],
    related: ['menu', 'tabs', 'steps'],
  },
  {
    slug: 'breadcrumb',
    name: 'RsBreadcrumb',
    title: 'Breadcrumb',
    titleZh: '面包屑',
    group: 'nav',
    summary: '展示当前页面在层级中的位置。',
    description: '面包屑告诉用户现在在哪、如何回到上级。最后一项为当前页，通常不可点。',
    whenToUse: ['信息架构超过两级。', '用户可能从深链进入，需要回到列表或概览。'],
    props: [{ name: 'items', type: '{ label, href? }[]', description: '路径项。也可用插槽。' }],
    related: ['menu', 'tabs'],
  },
  {
    slug: 'menu',
    name: 'RsMenu',
    title: 'Menu',
    titleZh: '菜单',
    group: 'nav',
    summary: '应用内导航菜单。',
    description: '侧栏或顶栏的导航结构，支持分组与选中态。侧栏布局可与 Sidebar 组合。',
    whenToUse: ['应用有多个稳定入口。', '临时操作列表用 Dropdown / ContextMenu。'],
    props: [
      { name: 'items', type: 'MenuItem[]', description: '菜单数据。' },
      { name: 'collapsed', type: 'boolean', description: '折叠为图标。' },
    ],
    related: ['sidebar', 'dropdown', 'breadcrumb'],
  },
  {
    slug: 'sidebar',
    name: 'RsSidebar',
    title: 'Sidebar',
    titleZh: '侧栏',
    group: 'nav',
    summary: '侧边导航容器。',
    description: '工作台左侧导航。配合 SidebarGroup / SidebarItem 组织入口，可与 SplitPane 组成可调宽度布局。',
    whenToUse: ['控制台级应用的一级导航。'],
    props: [{ name: 'collapsed', type: 'boolean', description: '折叠。' }],
    slots: [{ name: 'default', type: '—', description: '分组与条目。' }],
    related: ['menu', 'split-pane'],
  },
  {
    slug: 'tabs',
    name: 'RsTabs',
    title: 'Tabs',
    titleZh: '标签页',
    group: 'nav',
    summary: '同一层级内容的切换，支持关闭与重命名。',
    description: '工作台式标签：打开多个文档 / 连接 / 查询。支持关闭、重命名与溢出滚动，不是简单的分段控制器。',
    whenToUse: ['同一区域切换多个打开的对象。', '步骤流程用 Steps，设置分组用锚点或 Collapse。'],
    props: [
      { name: 'v-model / modelValue', type: 'string', description: '当前页签。' },
      { name: 'closable', type: 'boolean', description: '允许关闭。' },
    ],
    related: ['steps', 'menu'],
  },
  {
    slug: 'steps',
    name: 'RsSteps',
    title: 'Steps',
    titleZh: '步骤条',
    group: 'nav',
    summary: '引导用户完成分步任务。',
    description: '展示任务进度与当前步骤。用于向导、开通流程。',
    whenToUse: ['任务有固定顺序且需要回看进度。', '单页表单用 Fieldset 分组即可。'],
    props: [
      { name: 'current', type: 'number', description: '当前步骤索引。' },
      { name: 'items', type: '{ title, description? }[]', description: '步骤。' },
    ],
    related: ['tabs', 'form'],
  },
  {
    slug: 'dropdown',
    name: 'RsDropdown',
    title: 'Dropdown',
    titleZh: '下拉菜单',
    group: 'nav',
    summary: '由按钮触发的命令列表。',
    description: '收纳次要操作。与 Select 不同：Dropdown 触发命令，Select 回写表单值。',
    whenToUse: ['更多、批量操作、账号菜单。', '选择一个值写回表单时用 Select。'],
    props: [
      { name: 'items', type: 'DropdownItem[]', description: '菜单项。' },
      { name: 'disabled', type: 'boolean', description: '禁用触发器。' },
    ],
    slots: [{ name: 'trigger / default', type: '—', description: '触发器。' }],
    related: ['context-menu', 'button', 'select'],
  },
  {
    slug: 'toolbar',
    name: 'RsToolbar',
    title: 'Toolbar',
    titleZh: '工具条',
    group: 'nav',
    summary: '操作按钮的水平布局。',
    description: '把主操作、筛选与辅助操作排在一行，两端对齐。编辑器与表格上方常用。',
    whenToUse: ['列表页或编辑器需要一排稳定操作。'],
    slots: [
      { name: 'start', type: '—', description: '左侧。' },
      { name: 'end', type: '—', description: '右侧。' },
    ],
    related: ['button', 'dropdown'],
  },
  {
    slug: 'split-pane',
    name: 'RsSplitPane',
    title: 'SplitPane',
    titleZh: '分栏',
    group: 'nav',
    summary: '可拖拽调整的多栏布局。',
    description: '工作台经典布局：树 + 表格、编辑器 + 终端。支持方向与最小尺寸。',
    whenToUse: ['两栏或多栏需要用户自己调宽度。'],
    props: [
      { name: 'direction', type: "'horizontal' | 'vertical'", description: '分割方向。' },
      { name: 'minSize', type: 'number', description: '最小尺寸。' },
    ],
    related: ['sidebar', 'scrollbar'],
  },
  {
    slug: 'pagination',
    name: 'RsPagination',
    title: 'Pagination',
    titleZh: '分页',
    group: 'nav',
    summary: '分页浏览长列表。',
    description: '页码、每页条数与跳转。表格、日志检索的配套控件。',
    whenToUse: ['数据量超过一屏且服务端分页。', '前端虚拟滚动长列表用 VirtualList / Table virtual。'],
    props: [
      { name: 'page', type: 'number', description: '当前页。' },
      { name: 'pageSize', type: 'number', description: '每页条数。' },
      { name: 'total', type: 'number', description: '总条数。' },
    ],
    related: ['table', 'virtual-list'],
  },
]
