import type { RsThemeMode, RsThemeTokens } from './types'

/**
 * 色板参考值（与 styles.css 中的 --rs-* 保持同步，勿单独改此处）
 * 暗色：VS Code Dark Modern 灰阶 + macOS 系统色（primary / danger / success 等）
 * 亮色：macOS systemBackground / label + VS Code Light Modern 表格语义
 */
export const themePresets: Record<RsThemeMode, RsThemeTokens> = {
  light: {
    primary: '#007aff',
    primaryHover: '#0071eb',
    primaryForeground: '#ffffff',
    primaryContainer: '#e5f1ff',
    onPrimaryContainer: '#003d99',
    bg: '#f5f5f7',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceHover: '#e8e8ed',
    inputBg: '#ffffff',
    border: '#8c8c8c',
    borderSubtle: 'rgb(60 60 67 / 0.20)',
    text: '#1d1d1f',
    muted: '#6e6e73',
    placeholder: '#909090',
    danger: '#ff3b30',
    dangerContainer: '#ffe5e3',
    onDangerContainer: '#c41e16',
    success: '#34c759',
    successContainer: '#e4f8e9',
    onSuccessContainer: '#1a7f37',
    warning: '#ff9500',
    warningContainer: '#fff3e0',
    onWarningContainer: '#b26500',
    info: '#007aff',
    infoContainer: '#e5f1ff',
    onInfoContainer: '#003d99',
    focusRing: 'color-mix(in srgb, #007aff 22%, transparent)',
  },
  dark: {
    primary: '#0a84ff',
    primaryHover: '#409cff',
    primaryForeground: '#ffffff',
    primaryContainer: '#0a2540',
    onPrimaryContainer: '#6cb4ff',
    bg: '#181818',
    surface: '#1f1f1f',
    surfaceElevated: '#262626',
    surfaceHover: '#2e2e2e',
    inputBg: '#2b2b2b',
    border: '#6e6e6e',
    borderSubtle: '#3a3a3a',
    text: '#cccccc',
    muted: '#9d9d9d',
    placeholder: '#919191',
    danger: '#ff453a',
    dangerContainer: '#3b1210',
    onDangerContainer: '#ff8a84',
    success: '#30d158',
    successContainer: '#0d2818',
    onSuccessContainer: '#6ee79a',
    warning: '#ff9f0a',
    warningContainer: '#2e1f08',
    onWarningContainer: '#ffc46b',
    info: '#0a84ff',
    infoContainer: '#0a2540',
    onInfoContainer: '#6cb4ff',
    focusRing: 'color-mix(in srgb, #0a84ff 28%, transparent)',
  },
}
