import { createRouter, createWebHashHistory } from 'vue-router'

const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    { path: '/', component: () => import('./pages/IndexPage.vue') },
    { path: '/button', component: () => import('./pages/ButtonPage.vue') },
    { path: '/badge', component: () => import('./pages/BadgePage.vue') },
    { path: '/checkbox', component: () => import('./pages/CheckboxPage.vue') },
    { path: '/label', component: () => import('./pages/LabelPage.vue') },
    { path: '/link', component: () => import('./pages/LinkPage.vue') },
    { path: '/input', component: () => import('./pages/InputPage.vue') },
    { path: '/icon', component: () => import('./pages/IconPage.vue') },
    { path: '/avatar', component: () => import('./pages/AvatarPage.vue') },
    { path: '/card', component: () => import('./pages/CardPage.vue') },
    { path: '/stat-card', component: () => import('./pages/StatCardPage.vue') },
    { path: '/empty', component: () => import('./pages/EmptyPage.vue') },
    { path: '/loading', component: () => import('./pages/LoadingPage.vue') },
    { path: '/toaster', component: () => import('./pages/ToasterPage.vue') },
    { path: '/form', component: () => import('./pages/FormPage.vue') },
    { path: '/breadcrumb', component: () => import('./pages/BreadcrumbPage.vue') },
    { path: '/toolbar', component: () => import('./pages/ToolbarPage.vue') },
    { path: '/steps', component: () => import('./pages/StepsPage.vue') },
    { path: '/select', component: () => import('./pages/SelectPage.vue') },
    { path: '/scrollbar', component: () => import('./pages/ScrollbarPage.vue') },
    { path: '/dropdown', component: () => import('./pages/DropdownPage.vue') },
    { path: '/menu', component: () => import('./pages/MenuPage.vue') },
    { path: '/tabs', component: () => import('./pages/TabsPage.vue') },
    { path: '/terminal', component: () => import('./pages/TerminalPage.vue') },
    { path: '/pagination', component: () => import('./pages/PaginationPage.vue') },
    { path: '/table', component: () => import('./pages/TablePage.vue') },
    { path: '/table-cell-edit', component: () => import('./pages/TableCellEditPage.vue') },
    { path: '/table-row-commit', component: () => import('./pages/TableRowCommitPage.vue') },
    { path: '/table-row-select', component: () => import('./pages/TableRowSelectPage.vue') },
    { path: '/virtual-list', component: () => import('./pages/VirtualListPage.vue') },
    { path: '/popover', component: () => import('./pages/PopoverPage.vue') },
    { path: '/container', component: () => import('./pages/ContainerPage.vue') },
    { path: '/sidebar', component: () => import('./pages/SidebarPage.vue') },
    { path: '/split-pane', component: () => import('./pages/SplitPanePage.vue') },
    { path: '/context-menu', component: () => import('./pages/ContextMenuPage.vue') },
    { path: '/calendar-grid', component: () => import('./pages/CalendarGridPage.vue') },
    { path: '/date-picker', component: () => import('./pages/DatePickerPage.vue') },
    { path: '/datetime-picker', component: () => import('./pages/DateTimePickerPage.vue') },
    { path: '/time-picker', component: () => import('./pages/TimePickerPage.vue') },
    { path: '/tooltip', component: () => import('./pages/TooltipPage.vue') },
    { path: '/tree', component: () => import('./pages/TreePage.vue') },
    { path: '/upload', component: () => import('./pages/UploadPage.vue') },
    { path: '/confirm-dialog', component: () => import('./pages/ConfirmDialogPage.vue') },
    { path: '/dialog', component: () => import('./pages/DialogPage.vue') },
    { path: '/drawer', component: () => import('./pages/DrawerPage.vue') },
    { path: '/code-editor', component: () => import('./pages/CodeEditorPage.vue') },
    { path: '/monaco-editor', component: () => import('./pages/MonacoEditorPage.vue') },
    { path: '/code-block', component: () => import('./pages/CodeBlockPage.vue') },
    { path: '/studio-components', component: () => import('./pages/StudioComponentsPage.vue') },
    { path: '/theme', component: () => import('./pages/ThemePage.vue') },
    { path: '/:pathMatch(.*)*', redirect: '/' },
  ],
})

export default router
