export type PlaygroundGroup =
  | 'start'
  | 'basic'
  | 'form'
  | 'nav'
  | 'feedback'
  | 'data'
  | 'editor'
  | 'lab'

export interface PlaygroundRoute {
  path: string
  name: string
  title: string
  /** 侧栏 / 首页分组 */
  group: PlaygroundGroup
  /** 组件一句话说明（对外演示） */
  description: string
  /** 对应单测文件名；无则 '—' */
  testFile: string
  /** 首页精选 */
  featured?: boolean
}

export const playgroundGroupOrder: PlaygroundGroup[] = [
  'basic',
  'form',
  'nav',
  'feedback',
  'data',
  'editor',
  'lab',
]

export const playgroundRoutes: PlaygroundRoute[] = [
  {
    path: '/button',
    name: 'button',
    title: 'RsButton',
    group: 'basic',
    description: '按钮：变体、尺寸、图标、loading 与 tooltip。',
    testFile: 'RsButton.spec.ts',
    featured: true,
  },
  {
    path: '/badge',
    name: 'badge',
    title: 'RsBadge',
    group: 'basic',
    description: '状态与数量徽标。',
    testFile: 'RsBadge.spec.ts',
  },
  {
    path: '/tag',
    name: 'tag',
    title: 'RsTag',
    group: 'basic',
    description: '语义标签、关闭与圆角尺寸。',
    testFile: '—',
  },
  {
    path: '/divider',
    name: 'divider',
    title: 'RsDivider',
    group: 'basic',
    description: '水平 / 垂直分隔线。',
    testFile: '—',
  },
  {
    path: '/checkbox',
    name: 'checkbox',
    title: 'RsCheckbox',
    group: 'form',
    description: '复选框与半选状态。',
    testFile: 'RsCheckbox.spec.ts',
  },
  {
    path: '/switch',
    name: 'switch',
    title: 'RsSwitch',
    group: 'form',
    description: '开关控件。',
    testFile: 'RsSwitch.spec.ts',
  },
  {
    path: '/radio',
    name: 'radio',
    title: 'RsRadio',
    group: 'form',
    description: '单选分组。',
    testFile: '—',
  },
  {
    path: '/dynamic-tags',
    name: 'dynamic-tags',
    title: 'RsDynamicTags',
    group: 'form',
    description: '可编辑标签组。',
    testFile: 'RsDynamicTags.spec.ts',
  },
  {
    path: '/label',
    name: 'label',
    title: 'RsLabel',
    group: 'form',
    description: '表单标签与必填标记。',
    testFile: 'RsLabel.spec.ts',
  },
  {
    path: '/link',
    name: 'link',
    title: 'RsLink',
    group: 'basic',
    description: '文字链接。',
    testFile: 'RsLink.spec.ts',
  },
  {
    path: '/input',
    name: 'input',
    title: 'RsInput',
    group: 'form',
    description: '文本输入与内置校验规则。',
    testFile: 'RsInput.spec.ts',
    featured: true,
  },
  {
    path: '/input-number',
    name: 'input-number',
    title: 'RsInputNumber',
    group: 'form',
    description: '数字输入与步进。',
    testFile: 'RsInputNumber.spec.ts',
  },
  {
    path: '/icon',
    name: 'icon',
    title: 'RsIcon',
    group: 'basic',
    description: 'Lucide 与业务扩展图标。',
    testFile: 'RsIcon.spec.ts',
  },
  {
    path: '/avatar',
    name: 'avatar',
    title: 'RsAvatar',
    group: 'basic',
    description: '头像与回退文案。',
    testFile: 'RsAvatar.spec.ts',
  },
  {
    path: '/card',
    name: 'card',
    title: 'RsCard',
    group: 'basic',
    description: '内容卡片容器。',
    testFile: 'RsCard.spec.ts',
  },
  {
    path: '/stat-card',
    name: 'stat-card',
    title: 'RsStatCard',
    group: 'data',
    description: '指标卡片。',
    testFile: 'RsStatCard.spec.ts',
  },
  {
    path: '/descriptions',
    name: 'descriptions',
    title: 'RsDescriptions',
    group: 'data',
    description: '描述列表。',
    testFile: 'RsDescriptions.spec.ts',
  },
  {
    path: '/empty',
    name: 'empty',
    title: 'RsEmpty',
    group: 'feedback',
    description: '空状态与操作引导。',
    testFile: 'RsEmpty.spec.ts',
  },
  {
    path: '/loading',
    name: 'loading',
    title: 'RsLoading',
    group: 'feedback',
    description: '加载指示。',
    testFile: 'RsLoading.spec.ts',
  },
  {
    path: '/loading-bar',
    name: 'loading-bar',
    title: 'RsLoadingBar',
    group: 'feedback',
    description: '顶栏加载进度条。',
    testFile: '—',
  },
  {
    path: '/alert',
    name: 'alert',
    title: 'RsAlert',
    group: 'feedback',
    description: '反馈提示条。',
    testFile: '—',
  },
  {
    path: '/toaster',
    name: 'toaster',
    title: 'RsToaster',
    group: 'feedback',
    description: 'Toast 通知宿主。',
    testFile: 'RsToaster.spec.ts',
  },
  {
    path: '/form',
    name: 'form',
    title: 'RsForm',
    group: 'form',
    description: '专业表单：rules / name、validateField、异步校验、登录场景。',
    testFile: 'RsForm.spec.ts',
    featured: true,
  },
  {
    path: '/breadcrumb',
    name: 'breadcrumb',
    title: 'RsBreadcrumb',
    group: 'nav',
    description: '面包屑导航。',
    testFile: 'RsBreadcrumb.spec.ts',
  },
  {
    path: '/toolbar',
    name: 'toolbar',
    title: 'RsToolbar',
    group: 'nav',
    description: '工具条布局。',
    testFile: 'RsToolbar.spec.ts',
  },
  {
    path: '/steps',
    name: 'steps',
    title: 'RsSteps',
    group: 'nav',
    description: '步骤条。',
    testFile: 'RsSteps.spec.ts',
  },
  {
    path: '/select',
    name: 'select',
    title: 'RsSelect',
    group: 'form',
    description: '选择器、搜索与远程选项。',
    testFile: 'RsSelect.spec.ts',
    featured: true,
  },
  {
    path: '/auto-complete',
    name: 'auto-complete',
    title: 'RsAutoComplete',
    group: 'form',
    description: '输入框内打字出建议。',
    testFile: 'RsAutoComplete.spec.ts',
  },
  {
    path: '/cascader',
    name: 'cascader',
    title: 'RsCascader',
    group: 'form',
    description: '级联多列选择。',
    testFile: 'cascader-utils.spec.ts',
  },
  {
    path: '/tree-select',
    name: 'tree-select',
    title: 'RsTreeSelect',
    group: 'form',
    description: '树形选择，面板内搜索。',
    testFile: 'RsTreeSelect.spec.ts',
  },
  {
    path: '/mentions',
    name: 'mentions',
    title: 'RsMentions',
    group: 'form',
    description: '@ 提及输入。',
    testFile: 'mentions-utils.spec.ts',
  },
  {
    path: '/scrollbar',
    name: 'scrollbar',
    title: 'RsScrollbar',
    group: 'basic',
    description: '自定义滚动区域。',
    testFile: 'RsScrollbar.spec.ts',
  },
  {
    path: '/dropdown',
    name: 'dropdown',
    title: 'RsDropdown',
    group: 'nav',
    description: '下拉菜单。',
    testFile: 'RsDropdown.spec.ts',
  },
  {
    path: '/menu',
    name: 'menu',
    title: 'RsMenu',
    group: 'nav',
    description: '导航菜单。',
    testFile: 'RsMenu.spec.ts',
  },
  {
    path: '/tabs',
    name: 'tabs',
    title: 'RsTabs',
    group: 'nav',
    description: '标签页：关闭、重命名与溢出。',
    testFile: 'RsTabs.spec.ts',
  },
  {
    path: '/terminal',
    name: 'terminal',
    title: 'RsTerminal',
    group: 'editor',
    description: '基于 xterm 的终端面板。',
    testFile: 'RsTerminal.spec.ts',
  },
  {
    path: '/pagination',
    name: 'pagination',
    title: 'RsPagination',
    group: 'data',
    description: '分页控件。',
    testFile: 'RsPagination.spec.ts',
  },
  {
    path: '/table',
    name: 'table',
    title: 'RsTable',
    group: 'data',
    description: '数据表：排序、选择、虚拟滚动、编辑与树列表。',
    testFile: 'RsTable.spec.ts',
    featured: true,
  },
  {
    path: '/table-cell-edit',
    name: 'table-cell-edit',
    title: 'RsTable · 单元格编辑',
    group: 'data',
    description: '表格单元格就地编辑。',
    testFile: 'RsTable.spec.ts',
  },
  {
    path: '/table-row-commit',
    name: 'table-row-commit',
    title: 'RsTable · 行提交',
    group: 'data',
    description: '表格行级编辑与提交。',
    testFile: 'RsTable.spec.ts',
  },
  {
    path: '/table-row-select',
    name: 'table-row-select',
    title: 'RsTable · 行多选',
    group: 'data',
    description: '无 Checkbox 的行多选交互。',
    testFile: 'RsTable.spec.ts',
  },
  {
    path: '/table-tree',
    name: 'table-tree',
    title: 'RsTable · 树列表',
    group: 'data',
    description: '树表：缩进展开、过滤、懒加载与虚拟。',
    testFile: 'RsTable.spec.ts / table-utils.spec.ts',
    featured: true,
  },
  {
    path: '/virtual-list',
    name: 'virtual-list',
    title: 'RsVirtualList',
    group: 'data',
    description: '虚拟列表。',
    testFile: 'RsVirtualList.spec.ts',
  },
  {
    path: '/popover',
    name: 'popover',
    title: 'RsPopover',
    group: 'feedback',
    description: '气泡卡片浮层。',
    testFile: 'RsPopover.spec.ts',
  },
  {
    path: '/container',
    name: 'container',
    title: 'RsContainer',
    group: 'basic',
    description: '响应式宽度与内边距容器。',
    testFile: 'RsContainer.spec.ts',
  },
  {
    path: '/sidebar',
    name: 'sidebar',
    title: 'RsSidebar',
    group: 'nav',
    description: '侧边栏导航。',
    testFile: 'RsSidebar.spec.ts',
  },
  {
    path: '/split-pane',
    name: 'split-pane',
    title: 'RsSplitPane',
    group: 'nav',
    description: '可拖拽分栏布局。',
    testFile: 'RsSplitPane.spec.ts',
  },
  {
    path: '/context-menu',
    name: 'context-menu',
    title: 'RsContextMenu',
    group: 'feedback',
    description: '右键菜单。',
    testFile: 'RsContextMenu.spec.ts',
  },
  {
    path: '/calendar-grid',
    name: 'calendar-grid',
    title: 'RsCalendarGrid',
    group: 'form',
    description: '日历网格原语。',
    testFile: 'RsCalendarGrid.spec.ts',
  },
  {
    path: '/date-picker',
    name: 'date-picker',
    title: 'RsDatePicker',
    group: 'form',
    description: '日期选择。',
    testFile: 'RsDatePicker.spec.ts',
  },
  {
    path: '/datetime-picker',
    name: 'datetime-picker',
    title: 'RsDateTimePicker',
    group: 'form',
    description: '日期时间选择。',
    testFile: 'RsDateTimePicker.spec.ts',
  },
  {
    path: '/time-picker',
    name: 'time-picker',
    title: 'RsTimePicker',
    group: 'form',
    description: '时间选择。',
    testFile: 'RsTimePicker.spec.ts',
  },
  {
    path: '/tooltip',
    name: 'tooltip',
    title: 'RsTooltip',
    group: 'feedback',
    description: '文字提示。',
    testFile: 'RsTooltip.spec.ts',
  },
  {
    path: '/tree',
    name: 'tree',
    title: 'RsTree',
    group: 'data',
    description: '树：勾选、拖拽、过滤与虚拟。',
    testFile: 'RsTree.spec.ts',
    featured: true,
  },
  {
    path: '/upload',
    name: 'upload',
    title: 'RsUpload',
    group: 'form',
    description: '文件选择与校验。',
    testFile: 'RsUpload.spec.ts',
  },
  {
    path: '/confirm-dialog',
    name: 'confirm-dialog',
    title: 'RsConfirmDialog',
    group: 'feedback',
    description: '确认对话框。',
    testFile: 'RsConfirmDialog.spec.ts',
  },
  {
    path: '/dialog',
    name: 'dialog',
    title: 'RsDialog',
    group: 'feedback',
    description: '通用对话框。',
    testFile: 'RsDialog.spec.ts',
    featured: true,
  },
  {
    path: '/drawer',
    name: 'drawer',
    title: 'RsDrawer',
    group: 'feedback',
    description: '侧滑抽屉：四向动画、生命周期、modal/遮罩语义解耦。',
    testFile: 'RsDrawer.spec.ts',
  },
  {
    path: '/code-editor',
    name: 'code-editor',
    title: 'RsCodeEditor',
    group: 'editor',
    description: '基于 CodeMirror 的轻量编辑器。',
    testFile: 'RsCodeEditor.spec.ts',
  },
  {
    path: '/monaco-editor',
    name: 'monaco-editor',
    title: 'RsMonacoEditor',
    group: 'editor',
    description: '基于 Monaco 的重型编辑器。',
    testFile: '—',
  },
  {
    path: '/code-block',
    name: 'code-block',
    title: 'RsCodeBlock',
    group: 'editor',
    description: '只读代码块与复制。',
    testFile: 'RsCodeBlock.spec.ts',
  },
  {
    path: '/markdown',
    name: 'markdown',
    title: 'RsMarkdown',
    group: 'editor',
    description: 'Markdown 渲染与编辑预览。',
    testFile: 'RsMarkdown.spec.ts',
  },
  {
    path: '/studio-components',
    name: 'studio-components',
    title: '全量组件速览',
    group: 'lab',
    description: '多组件同屏冒烟验收。',
    testFile: '—',
  },
  {
    path: '/theme',
    name: 'theme',
    title: '主题 / 多语言',
    group: 'lab',
    description: 'RsConfigProvider 主题与 locale。',
    testFile: '—',
  },
]

export function getPlaygroundRoute(path: string): PlaygroundRoute | undefined {
  return playgroundRoutes.find((route) => route.path === path)
}
